/*
netbill places-svc API

API documentation for managing places and their classes.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
	"github.com/google/uuid"
	"strings"
	"reflect"
)


// PlaceClassesAPIService PlaceClassesAPI service
type PlaceClassesAPIService service

type ApiPlacesSvcV1PlacesClassesGetRequest struct {
	ctx context.Context
	ApiService *PlaceClassesAPIService
	size *int32
	page *int32
	text *string
	parentId *uuid.UUID
	withParents *bool
	withChild *bool
	deprecated *bool
	include *[]string
}

// Pagination limit. Cannot be greater than 100.
func (r ApiPlacesSvcV1PlacesClassesGetRequest) Size(size int32) ApiPlacesSvcV1PlacesClassesGetRequest {
	r.size = &size
	return r
}

// Pagination offset.
func (r ApiPlacesSvcV1PlacesClassesGetRequest) Page(page int32) ApiPlacesSvcV1PlacesClassesGetRequest {
	r.page = &page
	return r
}

// Full-text search query. Returns best-matching place classes.
func (r ApiPlacesSvcV1PlacesClassesGetRequest) Text(text string) ApiPlacesSvcV1PlacesClassesGetRequest {
	r.text = &text
	return r
}

// Filter place classes by parent class ID.
func (r ApiPlacesSvcV1PlacesClassesGetRequest) ParentId(parentId uuid.UUID) ApiPlacesSvcV1PlacesClassesGetRequest {
	r.parentId = &parentId
	return r
}

// When filtering by parent_id, also include ancestor classes up the hierarchy. Requires &#x60;parent_id&#x60; to be set. 
func (r ApiPlacesSvcV1PlacesClassesGetRequest) WithParents(withParents bool) ApiPlacesSvcV1PlacesClassesGetRequest {
	r.withParents = &withParents
	return r
}

// When filtering by parent_id, also include descendant classes down the hierarchy. Requires &#x60;parent_id&#x60; to be set. 
func (r ApiPlacesSvcV1PlacesClassesGetRequest) WithChild(withChild bool) ApiPlacesSvcV1PlacesClassesGetRequest {
	r.withChild = &withChild
	return r
}

// Filter place classes by deprecated flag.
func (r ApiPlacesSvcV1PlacesClassesGetRequest) Deprecated(deprecated bool) ApiPlacesSvcV1PlacesClassesGetRequest {
	r.deprecated = &deprecated
	return r
}

// List of related resources to include in the response. Supported values: &#x60;parents&#x60;. 
func (r ApiPlacesSvcV1PlacesClassesGetRequest) Include(include []string) ApiPlacesSvcV1PlacesClassesGetRequest {
	r.include = &include
	return r
}

func (r ApiPlacesSvcV1PlacesClassesGetRequest) Execute() (*PlaceClassesCollection, *http.Response, error) {
	return r.ApiService.PlacesSvcV1PlacesClassesGetExecute(r)
}

/*
PlacesSvcV1PlacesClassesGet Get place classes list

Returns a paginated list of place classes with optional filters.


 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiPlacesSvcV1PlacesClassesGetRequest
*/
func (a *PlaceClassesAPIService) PlacesSvcV1PlacesClassesGet(ctx context.Context) ApiPlacesSvcV1PlacesClassesGetRequest {
	return ApiPlacesSvcV1PlacesClassesGetRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return PlaceClassesCollection
func (a *PlaceClassesAPIService) PlacesSvcV1PlacesClassesGetExecute(r ApiPlacesSvcV1PlacesClassesGetRequest) (*PlaceClassesCollection, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *PlaceClassesCollection
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "PlaceClassesAPIService.PlacesSvcV1PlacesClassesGet")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/places-svc/v1/places/classes/"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.size != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "size", r.size, "form", "")
	}
	if r.page != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "page", r.page, "form", "")
	}
	if r.text != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "text", r.text, "form", "")
	}
	if r.parentId != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "parent_id", r.parentId, "form", "")
	}
	if r.withParents != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "with_parents", r.withParents, "form", "")
	}
	if r.withChild != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "with_child", r.withChild, "form", "")
	}
	if r.deprecated != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "deprecated", r.deprecated, "form", "")
	}
	if r.include != nil {
		t := *r.include
		if reflect.TypeOf(t).Kind() == reflect.Slice {
			s := reflect.ValueOf(t)
			for i := 0; i < s.Len(); i++ {
				parameterAddToHeaderOrQuery(localVarQueryParams, "include", s.Index(i).Interface(), "form", "multi")
			}
		} else {
			parameterAddToHeaderOrQuery(localVarQueryParams, "include", t, "form", "multi")
		}
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 400 {
			var v PlacesSvcV1PlacesGet400Response
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 500 {
			var v PlacesSvcV1PlacesGet400Response
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiPlacesSvcV1PlacesClassesPlaceClassIdDeprecatedDeleteRequest struct {
	ctx context.Context
	ApiService *PlaceClassesAPIService
	placeClassId uuid.UUID
}

func (r ApiPlacesSvcV1PlacesClassesPlaceClassIdDeprecatedDeleteRequest) Execute() (*PlaceClass, *http.Response, error) {
	return r.ApiService.PlacesSvcV1PlacesClassesPlaceClassIdDeprecatedDeleteExecute(r)
}

/*
PlacesSvcV1PlacesClassesPlaceClassIdDeprecatedDelete Undeprecate place class

Removes the deprecated mark from a place class. Accessible by system moderators only.


 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param placeClassId Place class ID
 @return ApiPlacesSvcV1PlacesClassesPlaceClassIdDeprecatedDeleteRequest
*/
func (a *PlaceClassesAPIService) PlacesSvcV1PlacesClassesPlaceClassIdDeprecatedDelete(ctx context.Context, placeClassId uuid.UUID) ApiPlacesSvcV1PlacesClassesPlaceClassIdDeprecatedDeleteRequest {
	return ApiPlacesSvcV1PlacesClassesPlaceClassIdDeprecatedDeleteRequest{
		ApiService: a,
		ctx: ctx,
		placeClassId: placeClassId,
	}
}

// Execute executes the request
//  @return PlaceClass
func (a *PlaceClassesAPIService) PlacesSvcV1PlacesClassesPlaceClassIdDeprecatedDeleteExecute(r ApiPlacesSvcV1PlacesClassesPlaceClassIdDeprecatedDeleteRequest) (*PlaceClass, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodDelete
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *PlaceClass
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "PlaceClassesAPIService.PlacesSvcV1PlacesClassesPlaceClassIdDeprecatedDelete")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/places-svc/v1/places/classes/{place_class_id}/deprecated"
	localVarPath = strings.Replace(localVarPath, "{"+"place_class_id"+"}", url.PathEscape(parameterValueToString(r.placeClassId, "placeClassId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 400 {
			var v PlacesSvcV1PlacesGet400Response
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 401 {
			var v PlacesSvcV1PlacesGet400Response
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 403 {
			var v PlacesSvcV1PlacesGet400Response
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 404 {
			var v PlacesSvcV1PlacesGet400Response
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 500 {
			var v PlacesSvcV1PlacesGet400Response
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiPlacesSvcV1PlacesClassesPlaceClassIdDeprecatedPatchRequest struct {
	ctx context.Context
	ApiService *PlaceClassesAPIService
	placeClassId uuid.UUID
}

func (r ApiPlacesSvcV1PlacesClassesPlaceClassIdDeprecatedPatchRequest) Execute() (*PlaceClass, *http.Response, error) {
	return r.ApiService.PlacesSvcV1PlacesClassesPlaceClassIdDeprecatedPatchExecute(r)
}

/*
PlacesSvcV1PlacesClassesPlaceClassIdDeprecatedPatch Deprecate place class

Marks a place class as deprecated. Accessible by system moderators only. Deprecated place classes cannot be assigned to new places.


 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param placeClassId Place class ID
 @return ApiPlacesSvcV1PlacesClassesPlaceClassIdDeprecatedPatchRequest
*/
func (a *PlaceClassesAPIService) PlacesSvcV1PlacesClassesPlaceClassIdDeprecatedPatch(ctx context.Context, placeClassId uuid.UUID) ApiPlacesSvcV1PlacesClassesPlaceClassIdDeprecatedPatchRequest {
	return ApiPlacesSvcV1PlacesClassesPlaceClassIdDeprecatedPatchRequest{
		ApiService: a,
		ctx: ctx,
		placeClassId: placeClassId,
	}
}

// Execute executes the request
//  @return PlaceClass
func (a *PlaceClassesAPIService) PlacesSvcV1PlacesClassesPlaceClassIdDeprecatedPatchExecute(r ApiPlacesSvcV1PlacesClassesPlaceClassIdDeprecatedPatchRequest) (*PlaceClass, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPatch
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *PlaceClass
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "PlaceClassesAPIService.PlacesSvcV1PlacesClassesPlaceClassIdDeprecatedPatch")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/places-svc/v1/places/classes/{place_class_id}/deprecated"
	localVarPath = strings.Replace(localVarPath, "{"+"place_class_id"+"}", url.PathEscape(parameterValueToString(r.placeClassId, "placeClassId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 400 {
			var v PlacesSvcV1PlacesGet400Response
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 401 {
			var v PlacesSvcV1PlacesGet400Response
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 403 {
			var v PlacesSvcV1PlacesGet400Response
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 404 {
			var v PlacesSvcV1PlacesGet400Response
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 500 {
			var v PlacesSvcV1PlacesGet400Response
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiPlacesSvcV1PlacesClassesPlaceClassIdGetRequest struct {
	ctx context.Context
	ApiService *PlaceClassesAPIService
	placeClassId uuid.UUID
	include *[]string
}

// List of related resources to include in the response. Supported values: &#x60;parent&#x60;. 
func (r ApiPlacesSvcV1PlacesClassesPlaceClassIdGetRequest) Include(include []string) ApiPlacesSvcV1PlacesClassesPlaceClassIdGetRequest {
	r.include = &include
	return r
}

func (r ApiPlacesSvcV1PlacesClassesPlaceClassIdGetRequest) Execute() (*PlaceClass, *http.Response, error) {
	return r.ApiService.PlacesSvcV1PlacesClassesPlaceClassIdGetExecute(r)
}

/*
PlacesSvcV1PlacesClassesPlaceClassIdGet Get place class

Returns a place class by ID.


 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param placeClassId Place class ID
 @return ApiPlacesSvcV1PlacesClassesPlaceClassIdGetRequest
*/
func (a *PlaceClassesAPIService) PlacesSvcV1PlacesClassesPlaceClassIdGet(ctx context.Context, placeClassId uuid.UUID) ApiPlacesSvcV1PlacesClassesPlaceClassIdGetRequest {
	return ApiPlacesSvcV1PlacesClassesPlaceClassIdGetRequest{
		ApiService: a,
		ctx: ctx,
		placeClassId: placeClassId,
	}
}

// Execute executes the request
//  @return PlaceClass
func (a *PlaceClassesAPIService) PlacesSvcV1PlacesClassesPlaceClassIdGetExecute(r ApiPlacesSvcV1PlacesClassesPlaceClassIdGetRequest) (*PlaceClass, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *PlaceClass
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "PlaceClassesAPIService.PlacesSvcV1PlacesClassesPlaceClassIdGet")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/places-svc/v1/places/classes/{place_class_id}"
	localVarPath = strings.Replace(localVarPath, "{"+"place_class_id"+"}", url.PathEscape(parameterValueToString(r.placeClassId, "placeClassId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.include != nil {
		t := *r.include
		if reflect.TypeOf(t).Kind() == reflect.Slice {
			s := reflect.ValueOf(t)
			for i := 0; i < s.Len(); i++ {
				parameterAddToHeaderOrQuery(localVarQueryParams, "include", s.Index(i).Interface(), "form", "multi")
			}
		} else {
			parameterAddToHeaderOrQuery(localVarQueryParams, "include", t, "form", "multi")
		}
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 400 {
			var v PlacesSvcV1PlacesGet400Response
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 404 {
			var v PlacesSvcV1PlacesGet400Response
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 500 {
			var v PlacesSvcV1PlacesGet400Response
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiPlacesSvcV1PlacesClassesPlaceClassIdMediaDeleteRequest struct {
	ctx context.Context
	ApiService *PlaceClassesAPIService
	placeClassId uuid.UUID
	deleteUploadPlaceClassMedia *DeleteUploadPlaceClassMedia
}

func (r ApiPlacesSvcV1PlacesClassesPlaceClassIdMediaDeleteRequest) DeleteUploadPlaceClassMedia(deleteUploadPlaceClassMedia DeleteUploadPlaceClassMedia) ApiPlacesSvcV1PlacesClassesPlaceClassIdMediaDeleteRequest {
	r.deleteUploadPlaceClassMedia = &deleteUploadPlaceClassMedia
	return r
}

func (r ApiPlacesSvcV1PlacesClassesPlaceClassIdMediaDeleteRequest) Execute() (*http.Response, error) {
	return r.ApiService.PlacesSvcV1PlacesClassesPlaceClassIdMediaDeleteExecute(r)
}

/*
PlacesSvcV1PlacesClassesPlaceClassIdMediaDelete Delete place class uploaded media

Deletes uploaded media (icon) from an active upload session for a place class. Accessible by system administrators only.


 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param placeClassId Place class ID
 @return ApiPlacesSvcV1PlacesClassesPlaceClassIdMediaDeleteRequest
*/
func (a *PlaceClassesAPIService) PlacesSvcV1PlacesClassesPlaceClassIdMediaDelete(ctx context.Context, placeClassId uuid.UUID) ApiPlacesSvcV1PlacesClassesPlaceClassIdMediaDeleteRequest {
	return ApiPlacesSvcV1PlacesClassesPlaceClassIdMediaDeleteRequest{
		ApiService: a,
		ctx: ctx,
		placeClassId: placeClassId,
	}
}

// Execute executes the request
func (a *PlaceClassesAPIService) PlacesSvcV1PlacesClassesPlaceClassIdMediaDeleteExecute(r ApiPlacesSvcV1PlacesClassesPlaceClassIdMediaDeleteRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodDelete
		localVarPostBody     interface{}
		formFiles            []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "PlaceClassesAPIService.PlacesSvcV1PlacesClassesPlaceClassIdMediaDelete")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/places-svc/v1/places/classes/{place_class_id}/media"
	localVarPath = strings.Replace(localVarPath, "{"+"place_class_id"+"}", url.PathEscape(parameterValueToString(r.placeClassId, "placeClassId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.deleteUploadPlaceClassMedia == nil {
		return nil, reportError("deleteUploadPlaceClassMedia is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.deleteUploadPlaceClassMedia
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 400 {
			var v PlacesSvcV1PlacesGet400Response
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 401 {
			var v PlacesSvcV1PlacesGet400Response
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 403 {
			var v PlacesSvcV1PlacesGet400Response
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 404 {
			var v PlacesSvcV1PlacesGet400Response
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 500 {
			var v PlacesSvcV1PlacesGet400Response
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}

type ApiPlacesSvcV1PlacesClassesPlaceClassIdMediaPostRequest struct {
	ctx context.Context
	ApiService *PlaceClassesAPIService
	placeClassId uuid.UUID
}

func (r ApiPlacesSvcV1PlacesClassesPlaceClassIdMediaPostRequest) Execute() (*UploadPlaceClassMediaLinks, *http.Response, error) {
	return r.ApiService.PlacesSvcV1PlacesClassesPlaceClassIdMediaPostExecute(r)
}

/*
PlacesSvcV1PlacesClassesPlaceClassIdMediaPost Create place class upload media link

Generates an upload media link (icon) for a place class. Accessible by system administrators only.


 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param placeClassId Place class ID
 @return ApiPlacesSvcV1PlacesClassesPlaceClassIdMediaPostRequest
*/
func (a *PlaceClassesAPIService) PlacesSvcV1PlacesClassesPlaceClassIdMediaPost(ctx context.Context, placeClassId uuid.UUID) ApiPlacesSvcV1PlacesClassesPlaceClassIdMediaPostRequest {
	return ApiPlacesSvcV1PlacesClassesPlaceClassIdMediaPostRequest{
		ApiService: a,
		ctx: ctx,
		placeClassId: placeClassId,
	}
}

// Execute executes the request
//  @return UploadPlaceClassMediaLinks
func (a *PlaceClassesAPIService) PlacesSvcV1PlacesClassesPlaceClassIdMediaPostExecute(r ApiPlacesSvcV1PlacesClassesPlaceClassIdMediaPostRequest) (*UploadPlaceClassMediaLinks, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *UploadPlaceClassMediaLinks
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "PlaceClassesAPIService.PlacesSvcV1PlacesClassesPlaceClassIdMediaPost")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/places-svc/v1/places/classes/{place_class_id}/media"
	localVarPath = strings.Replace(localVarPath, "{"+"place_class_id"+"}", url.PathEscape(parameterValueToString(r.placeClassId, "placeClassId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 400 {
			var v PlacesSvcV1PlacesGet400Response
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 401 {
			var v PlacesSvcV1PlacesGet400Response
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 403 {
			var v PlacesSvcV1PlacesGet400Response
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 404 {
			var v PlacesSvcV1PlacesGet400Response
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 500 {
			var v PlacesSvcV1PlacesGet400Response
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiPlacesSvcV1PlacesClassesPlaceClassIdPatchRequest struct {
	ctx context.Context
	ApiService *PlaceClassesAPIService
	placeClassId uuid.UUID
	updatePlaceClass *UpdatePlaceClass
}

func (r ApiPlacesSvcV1PlacesClassesPlaceClassIdPatchRequest) UpdatePlaceClass(updatePlaceClass UpdatePlaceClass) ApiPlacesSvcV1PlacesClassesPlaceClassIdPatchRequest {
	r.updatePlaceClass = &updatePlaceClass
	return r
}

func (r ApiPlacesSvcV1PlacesClassesPlaceClassIdPatchRequest) Execute() (*PlaceClass, *http.Response, error) {
	return r.ApiService.PlacesSvcV1PlacesClassesPlaceClassIdPatchExecute(r)
}

/*
PlacesSvcV1PlacesClassesPlaceClassIdPatch Update place class

Updates a place class by ID. Accessible by system moderators only.


 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param placeClassId Place class ID
 @return ApiPlacesSvcV1PlacesClassesPlaceClassIdPatchRequest
*/
func (a *PlaceClassesAPIService) PlacesSvcV1PlacesClassesPlaceClassIdPatch(ctx context.Context, placeClassId uuid.UUID) ApiPlacesSvcV1PlacesClassesPlaceClassIdPatchRequest {
	return ApiPlacesSvcV1PlacesClassesPlaceClassIdPatchRequest{
		ApiService: a,
		ctx: ctx,
		placeClassId: placeClassId,
	}
}

// Execute executes the request
//  @return PlaceClass
func (a *PlaceClassesAPIService) PlacesSvcV1PlacesClassesPlaceClassIdPatchExecute(r ApiPlacesSvcV1PlacesClassesPlaceClassIdPatchRequest) (*PlaceClass, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPatch
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *PlaceClass
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "PlaceClassesAPIService.PlacesSvcV1PlacesClassesPlaceClassIdPatch")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/places-svc/v1/places/classes/{place_class_id}"
	localVarPath = strings.Replace(localVarPath, "{"+"place_class_id"+"}", url.PathEscape(parameterValueToString(r.placeClassId, "placeClassId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.updatePlaceClass == nil {
		return localVarReturnValue, nil, reportError("updatePlaceClass is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.updatePlaceClass
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 400 {
			var v PlacesSvcV1PlacesGet400Response
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 401 {
			var v PlacesSvcV1PlacesGet400Response
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 403 {
			var v PlacesSvcV1PlacesGet400Response
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 404 {
			var v PlacesSvcV1PlacesGet400Response
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 409 {
			var v PlacesSvcV1PlacesGet400Response
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 500 {
			var v PlacesSvcV1PlacesGet400Response
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiPlacesSvcV1PlacesClassesPostRequest struct {
	ctx context.Context
	ApiService *PlaceClassesAPIService
	createPlaceClass *CreatePlaceClass
}

func (r ApiPlacesSvcV1PlacesClassesPostRequest) CreatePlaceClass(createPlaceClass CreatePlaceClass) ApiPlacesSvcV1PlacesClassesPostRequest {
	r.createPlaceClass = &createPlaceClass
	return r
}

func (r ApiPlacesSvcV1PlacesClassesPostRequest) Execute() (*PlaceClass, *http.Response, error) {
	return r.ApiService.PlacesSvcV1PlacesClassesPostExecute(r)
}

/*
PlacesSvcV1PlacesClassesPost Create place class

Creates a new place class. Accessible by system administrators only.


 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiPlacesSvcV1PlacesClassesPostRequest
*/
func (a *PlaceClassesAPIService) PlacesSvcV1PlacesClassesPost(ctx context.Context) ApiPlacesSvcV1PlacesClassesPostRequest {
	return ApiPlacesSvcV1PlacesClassesPostRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return PlaceClass
func (a *PlaceClassesAPIService) PlacesSvcV1PlacesClassesPostExecute(r ApiPlacesSvcV1PlacesClassesPostRequest) (*PlaceClass, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *PlaceClass
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "PlaceClassesAPIService.PlacesSvcV1PlacesClassesPost")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/places-svc/v1/places/classes/"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.createPlaceClass == nil {
		return localVarReturnValue, nil, reportError("createPlaceClass is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.createPlaceClass
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 400 {
			var v PlacesSvcV1PlacesGet400Response
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 401 {
			var v PlacesSvcV1PlacesGet400Response
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 403 {
			var v PlacesSvcV1PlacesGet400Response
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 404 {
			var v PlacesSvcV1PlacesGet400Response
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 409 {
			var v PlacesSvcV1PlacesGet400Response
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
			return localVarReturnValue, localVarHTTPResponse, newErr
		}
		if localVarHTTPResponse.StatusCode == 500 {
			var v PlacesSvcV1PlacesGet400Response
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
