/*
Place Service API

API for managing places and their classes.

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreatePlaceClass type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreatePlaceClass{}

// CreatePlaceClass struct for CreatePlaceClass
type CreatePlaceClass struct {
	Data CreatePlaceClassData `json:"data"`
}

type _CreatePlaceClass CreatePlaceClass

// NewCreatePlaceClass instantiates a new CreatePlaceClass object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreatePlaceClass(data CreatePlaceClassData) *CreatePlaceClass {
	this := CreatePlaceClass{}
	this.Data = data
	return &this
}

// NewCreatePlaceClassWithDefaults instantiates a new CreatePlaceClass object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreatePlaceClassWithDefaults() *CreatePlaceClass {
	this := CreatePlaceClass{}
	return &this
}

// GetData returns the Data field value
func (o *CreatePlaceClass) GetData() CreatePlaceClassData {
	if o == nil {
		var ret CreatePlaceClassData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *CreatePlaceClass) GetDataOk() (*CreatePlaceClassData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *CreatePlaceClass) SetData(v CreatePlaceClassData) {
	o.Data = v
}

func (o CreatePlaceClass) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreatePlaceClass) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *CreatePlaceClass) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreatePlaceClass := _CreatePlaceClass{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreatePlaceClass)

	if err != nil {
		return err
	}

	*o = CreatePlaceClass(varCreatePlaceClass)

	return err
}

type NullableCreatePlaceClass struct {
	value *CreatePlaceClass
	isSet bool
}

func (v NullableCreatePlaceClass) Get() *CreatePlaceClass {
	return v.value
}

func (v *NullableCreatePlaceClass) Set(val *CreatePlaceClass) {
	v.value = val
	v.isSet = true
}

func (v NullableCreatePlaceClass) IsSet() bool {
	return v.isSet
}

func (v *NullableCreatePlaceClass) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreatePlaceClass(val *CreatePlaceClass) *NullableCreatePlaceClass {
	return &NullableCreatePlaceClass{value: val, isSet: true}
}

func (v NullableCreatePlaceClass) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreatePlaceClass) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


