/*
Place Service API

API for managing places and their classes.

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UploadPlaceMediaLinksDataAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UploadPlaceMediaLinksDataAttributes{}

// UploadPlaceMediaLinksDataAttributes struct for UploadPlaceMediaLinksDataAttributes
type UploadPlaceMediaLinksDataAttributes struct {
	Icon UploadResourcesLink `json:"icon"`
	Banner UploadResourcesLink `json:"banner"`
}

type _UploadPlaceMediaLinksDataAttributes UploadPlaceMediaLinksDataAttributes

// NewUploadPlaceMediaLinksDataAttributes instantiates a new UploadPlaceMediaLinksDataAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUploadPlaceMediaLinksDataAttributes(icon UploadResourcesLink, banner UploadResourcesLink) *UploadPlaceMediaLinksDataAttributes {
	this := UploadPlaceMediaLinksDataAttributes{}
	this.Icon = icon
	this.Banner = banner
	return &this
}

// NewUploadPlaceMediaLinksDataAttributesWithDefaults instantiates a new UploadPlaceMediaLinksDataAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUploadPlaceMediaLinksDataAttributesWithDefaults() *UploadPlaceMediaLinksDataAttributes {
	this := UploadPlaceMediaLinksDataAttributes{}
	return &this
}

// GetIcon returns the Icon field value
func (o *UploadPlaceMediaLinksDataAttributes) GetIcon() UploadResourcesLink {
	if o == nil {
		var ret UploadResourcesLink
		return ret
	}

	return o.Icon
}

// GetIconOk returns a tuple with the Icon field value
// and a boolean to check if the value has been set.
func (o *UploadPlaceMediaLinksDataAttributes) GetIconOk() (*UploadResourcesLink, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Icon, true
}

// SetIcon sets field value
func (o *UploadPlaceMediaLinksDataAttributes) SetIcon(v UploadResourcesLink) {
	o.Icon = v
}

// GetBanner returns the Banner field value
func (o *UploadPlaceMediaLinksDataAttributes) GetBanner() UploadResourcesLink {
	if o == nil {
		var ret UploadResourcesLink
		return ret
	}

	return o.Banner
}

// GetBannerOk returns a tuple with the Banner field value
// and a boolean to check if the value has been set.
func (o *UploadPlaceMediaLinksDataAttributes) GetBannerOk() (*UploadResourcesLink, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Banner, true
}

// SetBanner sets field value
func (o *UploadPlaceMediaLinksDataAttributes) SetBanner(v UploadResourcesLink) {
	o.Banner = v
}

func (o UploadPlaceMediaLinksDataAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UploadPlaceMediaLinksDataAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["icon"] = o.Icon
	toSerialize["banner"] = o.Banner
	return toSerialize, nil
}

func (o *UploadPlaceMediaLinksDataAttributes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"icon",
		"banner",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUploadPlaceMediaLinksDataAttributes := _UploadPlaceMediaLinksDataAttributes{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUploadPlaceMediaLinksDataAttributes)

	if err != nil {
		return err
	}

	*o = UploadPlaceMediaLinksDataAttributes(varUploadPlaceMediaLinksDataAttributes)

	return err
}

type NullableUploadPlaceMediaLinksDataAttributes struct {
	value *UploadPlaceMediaLinksDataAttributes
	isSet bool
}

func (v NullableUploadPlaceMediaLinksDataAttributes) Get() *UploadPlaceMediaLinksDataAttributes {
	return v.value
}

func (v *NullableUploadPlaceMediaLinksDataAttributes) Set(val *UploadPlaceMediaLinksDataAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableUploadPlaceMediaLinksDataAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableUploadPlaceMediaLinksDataAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUploadPlaceMediaLinksDataAttributes(val *UploadPlaceMediaLinksDataAttributes) *NullableUploadPlaceMediaLinksDataAttributes {
	return &NullableUploadPlaceMediaLinksDataAttributes{value: val, isSet: true}
}

func (v NullableUploadPlaceMediaLinksDataAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUploadPlaceMediaLinksDataAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


