/*
Place Service API

API for managing places and their classes.

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UploadPlaceClassMediaLinksDataRelationshipsPlaceClass type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UploadPlaceClassMediaLinksDataRelationshipsPlaceClass{}

// UploadPlaceClassMediaLinksDataRelationshipsPlaceClass struct for UploadPlaceClassMediaLinksDataRelationshipsPlaceClass
type UploadPlaceClassMediaLinksDataRelationshipsPlaceClass struct {
	Data UploadPlaceClassMediaLinksDataRelationshipsPlaceClassData `json:"data"`
}

type _UploadPlaceClassMediaLinksDataRelationshipsPlaceClass UploadPlaceClassMediaLinksDataRelationshipsPlaceClass

// NewUploadPlaceClassMediaLinksDataRelationshipsPlaceClass instantiates a new UploadPlaceClassMediaLinksDataRelationshipsPlaceClass object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUploadPlaceClassMediaLinksDataRelationshipsPlaceClass(data UploadPlaceClassMediaLinksDataRelationshipsPlaceClassData) *UploadPlaceClassMediaLinksDataRelationshipsPlaceClass {
	this := UploadPlaceClassMediaLinksDataRelationshipsPlaceClass{}
	this.Data = data
	return &this
}

// NewUploadPlaceClassMediaLinksDataRelationshipsPlaceClassWithDefaults instantiates a new UploadPlaceClassMediaLinksDataRelationshipsPlaceClass object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUploadPlaceClassMediaLinksDataRelationshipsPlaceClassWithDefaults() *UploadPlaceClassMediaLinksDataRelationshipsPlaceClass {
	this := UploadPlaceClassMediaLinksDataRelationshipsPlaceClass{}
	return &this
}

// GetData returns the Data field value
func (o *UploadPlaceClassMediaLinksDataRelationshipsPlaceClass) GetData() UploadPlaceClassMediaLinksDataRelationshipsPlaceClassData {
	if o == nil {
		var ret UploadPlaceClassMediaLinksDataRelationshipsPlaceClassData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *UploadPlaceClassMediaLinksDataRelationshipsPlaceClass) GetDataOk() (*UploadPlaceClassMediaLinksDataRelationshipsPlaceClassData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *UploadPlaceClassMediaLinksDataRelationshipsPlaceClass) SetData(v UploadPlaceClassMediaLinksDataRelationshipsPlaceClassData) {
	o.Data = v
}

func (o UploadPlaceClassMediaLinksDataRelationshipsPlaceClass) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UploadPlaceClassMediaLinksDataRelationshipsPlaceClass) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *UploadPlaceClassMediaLinksDataRelationshipsPlaceClass) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUploadPlaceClassMediaLinksDataRelationshipsPlaceClass := _UploadPlaceClassMediaLinksDataRelationshipsPlaceClass{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUploadPlaceClassMediaLinksDataRelationshipsPlaceClass)

	if err != nil {
		return err
	}

	*o = UploadPlaceClassMediaLinksDataRelationshipsPlaceClass(varUploadPlaceClassMediaLinksDataRelationshipsPlaceClass)

	return err
}

type NullableUploadPlaceClassMediaLinksDataRelationshipsPlaceClass struct {
	value *UploadPlaceClassMediaLinksDataRelationshipsPlaceClass
	isSet bool
}

func (v NullableUploadPlaceClassMediaLinksDataRelationshipsPlaceClass) Get() *UploadPlaceClassMediaLinksDataRelationshipsPlaceClass {
	return v.value
}

func (v *NullableUploadPlaceClassMediaLinksDataRelationshipsPlaceClass) Set(val *UploadPlaceClassMediaLinksDataRelationshipsPlaceClass) {
	v.value = val
	v.isSet = true
}

func (v NullableUploadPlaceClassMediaLinksDataRelationshipsPlaceClass) IsSet() bool {
	return v.isSet
}

func (v *NullableUploadPlaceClassMediaLinksDataRelationshipsPlaceClass) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUploadPlaceClassMediaLinksDataRelationshipsPlaceClass(val *UploadPlaceClassMediaLinksDataRelationshipsPlaceClass) *NullableUploadPlaceClassMediaLinksDataRelationshipsPlaceClass {
	return &NullableUploadPlaceClassMediaLinksDataRelationshipsPlaceClass{value: val, isSet: true}
}

func (v NullableUploadPlaceClassMediaLinksDataRelationshipsPlaceClass) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUploadPlaceClassMediaLinksDataRelationshipsPlaceClass) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


