/*
Place Service API

API for managing places and their classes.

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UploadPlaceClassMediaLinksDataAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UploadPlaceClassMediaLinksDataAttributes{}

// UploadPlaceClassMediaLinksDataAttributes struct for UploadPlaceClassMediaLinksDataAttributes
type UploadPlaceClassMediaLinksDataAttributes struct {
	Icon UploadResourcesLink `json:"icon"`
}

type _UploadPlaceClassMediaLinksDataAttributes UploadPlaceClassMediaLinksDataAttributes

// NewUploadPlaceClassMediaLinksDataAttributes instantiates a new UploadPlaceClassMediaLinksDataAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUploadPlaceClassMediaLinksDataAttributes(icon UploadResourcesLink) *UploadPlaceClassMediaLinksDataAttributes {
	this := UploadPlaceClassMediaLinksDataAttributes{}
	this.Icon = icon
	return &this
}

// NewUploadPlaceClassMediaLinksDataAttributesWithDefaults instantiates a new UploadPlaceClassMediaLinksDataAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUploadPlaceClassMediaLinksDataAttributesWithDefaults() *UploadPlaceClassMediaLinksDataAttributes {
	this := UploadPlaceClassMediaLinksDataAttributes{}
	return &this
}

// GetIcon returns the Icon field value
func (o *UploadPlaceClassMediaLinksDataAttributes) GetIcon() UploadResourcesLink {
	if o == nil {
		var ret UploadResourcesLink
		return ret
	}

	return o.Icon
}

// GetIconOk returns a tuple with the Icon field value
// and a boolean to check if the value has been set.
func (o *UploadPlaceClassMediaLinksDataAttributes) GetIconOk() (*UploadResourcesLink, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Icon, true
}

// SetIcon sets field value
func (o *UploadPlaceClassMediaLinksDataAttributes) SetIcon(v UploadResourcesLink) {
	o.Icon = v
}

func (o UploadPlaceClassMediaLinksDataAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UploadPlaceClassMediaLinksDataAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["icon"] = o.Icon
	return toSerialize, nil
}

func (o *UploadPlaceClassMediaLinksDataAttributes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"icon",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUploadPlaceClassMediaLinksDataAttributes := _UploadPlaceClassMediaLinksDataAttributes{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUploadPlaceClassMediaLinksDataAttributes)

	if err != nil {
		return err
	}

	*o = UploadPlaceClassMediaLinksDataAttributes(varUploadPlaceClassMediaLinksDataAttributes)

	return err
}

type NullableUploadPlaceClassMediaLinksDataAttributes struct {
	value *UploadPlaceClassMediaLinksDataAttributes
	isSet bool
}

func (v NullableUploadPlaceClassMediaLinksDataAttributes) Get() *UploadPlaceClassMediaLinksDataAttributes {
	return v.value
}

func (v *NullableUploadPlaceClassMediaLinksDataAttributes) Set(val *UploadPlaceClassMediaLinksDataAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableUploadPlaceClassMediaLinksDataAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableUploadPlaceClassMediaLinksDataAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUploadPlaceClassMediaLinksDataAttributes(val *UploadPlaceClassMediaLinksDataAttributes) *NullableUploadPlaceClassMediaLinksDataAttributes {
	return &NullableUploadPlaceClassMediaLinksDataAttributes{value: val, isSet: true}
}

func (v NullableUploadPlaceClassMediaLinksDataAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUploadPlaceClassMediaLinksDataAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


