/*
Place Service API

API for managing places and their classes.

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UploadResourcesLink type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UploadResourcesLink{}

// UploadResourcesLink struct for UploadResourcesLink
type UploadResourcesLink struct {
	// Key for the avatar in the storage service
	Key string `json:"key"`
	// Pre-signed URL for uploading the avatar
	UploadUrl string `json:"upload_url"`
	// URL for preloading the avatar after upload
	PreloadUrl string `json:"preload_url"`
}

type _UploadResourcesLink UploadResourcesLink

// NewUploadResourcesLink instantiates a new UploadResourcesLink object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUploadResourcesLink(key string, uploadUrl string, preloadUrl string) *UploadResourcesLink {
	this := UploadResourcesLink{}
	this.Key = key
	this.UploadUrl = uploadUrl
	this.PreloadUrl = preloadUrl
	return &this
}

// NewUploadResourcesLinkWithDefaults instantiates a new UploadResourcesLink object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUploadResourcesLinkWithDefaults() *UploadResourcesLink {
	this := UploadResourcesLink{}
	return &this
}

// GetKey returns the Key field value
func (o *UploadResourcesLink) GetKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Key
}

// GetKeyOk returns a tuple with the Key field value
// and a boolean to check if the value has been set.
func (o *UploadResourcesLink) GetKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Key, true
}

// SetKey sets field value
func (o *UploadResourcesLink) SetKey(v string) {
	o.Key = v
}

// GetUploadUrl returns the UploadUrl field value
func (o *UploadResourcesLink) GetUploadUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UploadUrl
}

// GetUploadUrlOk returns a tuple with the UploadUrl field value
// and a boolean to check if the value has been set.
func (o *UploadResourcesLink) GetUploadUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UploadUrl, true
}

// SetUploadUrl sets field value
func (o *UploadResourcesLink) SetUploadUrl(v string) {
	o.UploadUrl = v
}

// GetPreloadUrl returns the PreloadUrl field value
func (o *UploadResourcesLink) GetPreloadUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PreloadUrl
}

// GetPreloadUrlOk returns a tuple with the PreloadUrl field value
// and a boolean to check if the value has been set.
func (o *UploadResourcesLink) GetPreloadUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PreloadUrl, true
}

// SetPreloadUrl sets field value
func (o *UploadResourcesLink) SetPreloadUrl(v string) {
	o.PreloadUrl = v
}

func (o UploadResourcesLink) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UploadResourcesLink) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["key"] = o.Key
	toSerialize["upload_url"] = o.UploadUrl
	toSerialize["preload_url"] = o.PreloadUrl
	return toSerialize, nil
}

func (o *UploadResourcesLink) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"key",
		"upload_url",
		"preload_url",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUploadResourcesLink := _UploadResourcesLink{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUploadResourcesLink)

	if err != nil {
		return err
	}

	*o = UploadResourcesLink(varUploadResourcesLink)

	return err
}

type NullableUploadResourcesLink struct {
	value *UploadResourcesLink
	isSet bool
}

func (v NullableUploadResourcesLink) Get() *UploadResourcesLink {
	return v.value
}

func (v *NullableUploadResourcesLink) Set(val *UploadResourcesLink) {
	v.value = val
	v.isSet = true
}

func (v NullableUploadResourcesLink) IsSet() bool {
	return v.isSet
}

func (v *NullableUploadResourcesLink) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUploadResourcesLink(val *UploadResourcesLink) *NullableUploadResourcesLink {
	return &NullableUploadResourcesLink{value: val, isSet: true}
}

func (v NullableUploadResourcesLink) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUploadResourcesLink) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


