/*
Place Service API

API for managing places and their classes.

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
)

// checks if the UploadPlaceMediaLinksDataRelationships type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UploadPlaceMediaLinksDataRelationships{}

// UploadPlaceMediaLinksDataRelationships struct for UploadPlaceMediaLinksDataRelationships
type UploadPlaceMediaLinksDataRelationships struct {
	Place *UploadPlaceMediaLinksDataRelationshipsPlace `json:"place,omitempty"`
}

// NewUploadPlaceMediaLinksDataRelationships instantiates a new UploadPlaceMediaLinksDataRelationships object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUploadPlaceMediaLinksDataRelationships() *UploadPlaceMediaLinksDataRelationships {
	this := UploadPlaceMediaLinksDataRelationships{}
	return &this
}

// NewUploadPlaceMediaLinksDataRelationshipsWithDefaults instantiates a new UploadPlaceMediaLinksDataRelationships object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUploadPlaceMediaLinksDataRelationshipsWithDefaults() *UploadPlaceMediaLinksDataRelationships {
	this := UploadPlaceMediaLinksDataRelationships{}
	return &this
}

// GetPlace returns the Place field value if set, zero value otherwise.
func (o *UploadPlaceMediaLinksDataRelationships) GetPlace() UploadPlaceMediaLinksDataRelationshipsPlace {
	if o == nil || IsNil(o.Place) {
		var ret UploadPlaceMediaLinksDataRelationshipsPlace
		return ret
	}
	return *o.Place
}

// GetPlaceOk returns a tuple with the Place field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UploadPlaceMediaLinksDataRelationships) GetPlaceOk() (*UploadPlaceMediaLinksDataRelationshipsPlace, bool) {
	if o == nil || IsNil(o.Place) {
		return nil, false
	}
	return o.Place, true
}

// HasPlace returns a boolean if a field has been set.
func (o *UploadPlaceMediaLinksDataRelationships) HasPlace() bool {
	if o != nil && !IsNil(o.Place) {
		return true
	}

	return false
}

// SetPlace gets a reference to the given UploadPlaceMediaLinksDataRelationshipsPlace and assigns it to the Place field.
func (o *UploadPlaceMediaLinksDataRelationships) SetPlace(v UploadPlaceMediaLinksDataRelationshipsPlace) {
	o.Place = &v
}

func (o UploadPlaceMediaLinksDataRelationships) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UploadPlaceMediaLinksDataRelationships) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Place) {
		toSerialize["place"] = o.Place
	}
	return toSerialize, nil
}

type NullableUploadPlaceMediaLinksDataRelationships struct {
	value *UploadPlaceMediaLinksDataRelationships
	isSet bool
}

func (v NullableUploadPlaceMediaLinksDataRelationships) Get() *UploadPlaceMediaLinksDataRelationships {
	return v.value
}

func (v *NullableUploadPlaceMediaLinksDataRelationships) Set(val *UploadPlaceMediaLinksDataRelationships) {
	v.value = val
	v.isSet = true
}

func (v NullableUploadPlaceMediaLinksDataRelationships) IsSet() bool {
	return v.isSet
}

func (v *NullableUploadPlaceMediaLinksDataRelationships) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUploadPlaceMediaLinksDataRelationships(val *UploadPlaceMediaLinksDataRelationships) *NullableUploadPlaceMediaLinksDataRelationships {
	return &NullableUploadPlaceMediaLinksDataRelationships{value: val, isSet: true}
}

func (v NullableUploadPlaceMediaLinksDataRelationships) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUploadPlaceMediaLinksDataRelationships) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


