/*
netbill places-svc API

API documentation for managing places and their classes.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"github.com/google/uuid"
)

// checks if the UpdatePlaceClassDataAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdatePlaceClassDataAttributes{}

// UpdatePlaceClassDataAttributes struct for UpdatePlaceClassDataAttributes
type UpdatePlaceClassDataAttributes struct {
	// The ID of the parent class, if any
	ParentId *uuid.UUID `json:"parent_id,omitempty"`
	// The name of the class
	Name *string `json:"name,omitempty"`
	// A brief description of the class
	Description *string `json:"description,omitempty"`
	// The S3 key for the class icon
	IconKey *string `json:"icon_key,omitempty"`
}

// NewUpdatePlaceClassDataAttributes instantiates a new UpdatePlaceClassDataAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdatePlaceClassDataAttributes() *UpdatePlaceClassDataAttributes {
	this := UpdatePlaceClassDataAttributes{}
	return &this
}

// NewUpdatePlaceClassDataAttributesWithDefaults instantiates a new UpdatePlaceClassDataAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdatePlaceClassDataAttributesWithDefaults() *UpdatePlaceClassDataAttributes {
	this := UpdatePlaceClassDataAttributes{}
	return &this
}

// GetParentId returns the ParentId field value if set, zero value otherwise.
func (o *UpdatePlaceClassDataAttributes) GetParentId() uuid.UUID {
	if o == nil || IsNil(o.ParentId) {
		var ret uuid.UUID
		return ret
	}
	return *o.ParentId
}

// GetParentIdOk returns a tuple with the ParentId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdatePlaceClassDataAttributes) GetParentIdOk() (*uuid.UUID, bool) {
	if o == nil || IsNil(o.ParentId) {
		return nil, false
	}
	return o.ParentId, true
}

// HasParentId returns a boolean if a field has been set.
func (o *UpdatePlaceClassDataAttributes) HasParentId() bool {
	if o != nil && !IsNil(o.ParentId) {
		return true
	}

	return false
}

// SetParentId gets a reference to the given uuid.UUID and assigns it to the ParentId field.
func (o *UpdatePlaceClassDataAttributes) SetParentId(v uuid.UUID) {
	o.ParentId = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *UpdatePlaceClassDataAttributes) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdatePlaceClassDataAttributes) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *UpdatePlaceClassDataAttributes) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *UpdatePlaceClassDataAttributes) SetName(v string) {
	o.Name = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *UpdatePlaceClassDataAttributes) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdatePlaceClassDataAttributes) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *UpdatePlaceClassDataAttributes) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *UpdatePlaceClassDataAttributes) SetDescription(v string) {
	o.Description = &v
}

// GetIconKey returns the IconKey field value if set, zero value otherwise.
func (o *UpdatePlaceClassDataAttributes) GetIconKey() string {
	if o == nil || IsNil(o.IconKey) {
		var ret string
		return ret
	}
	return *o.IconKey
}

// GetIconKeyOk returns a tuple with the IconKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdatePlaceClassDataAttributes) GetIconKeyOk() (*string, bool) {
	if o == nil || IsNil(o.IconKey) {
		return nil, false
	}
	return o.IconKey, true
}

// HasIconKey returns a boolean if a field has been set.
func (o *UpdatePlaceClassDataAttributes) HasIconKey() bool {
	if o != nil && !IsNil(o.IconKey) {
		return true
	}

	return false
}

// SetIconKey gets a reference to the given string and assigns it to the IconKey field.
func (o *UpdatePlaceClassDataAttributes) SetIconKey(v string) {
	o.IconKey = &v
}

func (o UpdatePlaceClassDataAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdatePlaceClassDataAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ParentId) {
		toSerialize["parent_id"] = o.ParentId
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.IconKey) {
		toSerialize["icon_key"] = o.IconKey
	}
	return toSerialize, nil
}

type NullableUpdatePlaceClassDataAttributes struct {
	value *UpdatePlaceClassDataAttributes
	isSet bool
}

func (v NullableUpdatePlaceClassDataAttributes) Get() *UpdatePlaceClassDataAttributes {
	return v.value
}

func (v *NullableUpdatePlaceClassDataAttributes) Set(val *UpdatePlaceClassDataAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdatePlaceClassDataAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdatePlaceClassDataAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdatePlaceClassDataAttributes(val *UpdatePlaceClassDataAttributes) *NullableUpdatePlaceClassDataAttributes {
	return &NullableUpdatePlaceClassDataAttributes{value: val, isSet: true}
}

func (v NullableUpdatePlaceClassDataAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdatePlaceClassDataAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


