/*
Place Service API

API for managing places and their classes.

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UpdatePlace type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdatePlace{}

// UpdatePlace struct for UpdatePlace
type UpdatePlace struct {
	Data UpdatePlaceData `json:"data"`
}

type _UpdatePlace UpdatePlace

// NewUpdatePlace instantiates a new UpdatePlace object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdatePlace(data UpdatePlaceData) *UpdatePlace {
	this := UpdatePlace{}
	this.Data = data
	return &this
}

// NewUpdatePlaceWithDefaults instantiates a new UpdatePlace object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdatePlaceWithDefaults() *UpdatePlace {
	this := UpdatePlace{}
	return &this
}

// GetData returns the Data field value
func (o *UpdatePlace) GetData() UpdatePlaceData {
	if o == nil {
		var ret UpdatePlaceData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *UpdatePlace) GetDataOk() (*UpdatePlaceData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *UpdatePlace) SetData(v UpdatePlaceData) {
	o.Data = v
}

func (o UpdatePlace) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdatePlace) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *UpdatePlace) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdatePlace := _UpdatePlace{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdatePlace)

	if err != nil {
		return err
	}

	*o = UpdatePlace(varUpdatePlace)

	return err
}

type NullableUpdatePlace struct {
	value *UpdatePlace
	isSet bool
}

func (v NullableUpdatePlace) Get() *UpdatePlace {
	return v.value
}

func (v *NullableUpdatePlace) Set(val *UpdatePlace) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdatePlace) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdatePlace) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdatePlace(val *UpdatePlace) *NullableUpdatePlace {
	return &NullableUpdatePlace{value: val, isSet: true}
}

func (v NullableUpdatePlace) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdatePlace) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


