/*
Place Service API

API for managing places and their classes.

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PlaceDataRelationships type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PlaceDataRelationships{}

// PlaceDataRelationships struct for PlaceDataRelationships
type PlaceDataRelationships struct {
	Organization PlaceDataRelationshipsOrganization `json:"organization"`
	PlaceClass PlaceDataRelationshipsPlaceClass `json:"place_class"`
}

type _PlaceDataRelationships PlaceDataRelationships

// NewPlaceDataRelationships instantiates a new PlaceDataRelationships object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPlaceDataRelationships(organization PlaceDataRelationshipsOrganization, placeClass PlaceDataRelationshipsPlaceClass) *PlaceDataRelationships {
	this := PlaceDataRelationships{}
	this.Organization = organization
	this.PlaceClass = placeClass
	return &this
}

// NewPlaceDataRelationshipsWithDefaults instantiates a new PlaceDataRelationships object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPlaceDataRelationshipsWithDefaults() *PlaceDataRelationships {
	this := PlaceDataRelationships{}
	return &this
}

// GetOrganization returns the Organization field value
func (o *PlaceDataRelationships) GetOrganization() PlaceDataRelationshipsOrganization {
	if o == nil {
		var ret PlaceDataRelationshipsOrganization
		return ret
	}

	return o.Organization
}

// GetOrganizationOk returns a tuple with the Organization field value
// and a boolean to check if the value has been set.
func (o *PlaceDataRelationships) GetOrganizationOk() (*PlaceDataRelationshipsOrganization, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Organization, true
}

// SetOrganization sets field value
func (o *PlaceDataRelationships) SetOrganization(v PlaceDataRelationshipsOrganization) {
	o.Organization = v
}

// GetPlaceClass returns the PlaceClass field value
func (o *PlaceDataRelationships) GetPlaceClass() PlaceDataRelationshipsPlaceClass {
	if o == nil {
		var ret PlaceDataRelationshipsPlaceClass
		return ret
	}

	return o.PlaceClass
}

// GetPlaceClassOk returns a tuple with the PlaceClass field value
// and a boolean to check if the value has been set.
func (o *PlaceDataRelationships) GetPlaceClassOk() (*PlaceDataRelationshipsPlaceClass, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PlaceClass, true
}

// SetPlaceClass sets field value
func (o *PlaceDataRelationships) SetPlaceClass(v PlaceDataRelationshipsPlaceClass) {
	o.PlaceClass = v
}

func (o PlaceDataRelationships) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PlaceDataRelationships) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["organization"] = o.Organization
	toSerialize["place_class"] = o.PlaceClass
	return toSerialize, nil
}

func (o *PlaceDataRelationships) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"organization",
		"place_class",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPlaceDataRelationships := _PlaceDataRelationships{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPlaceDataRelationships)

	if err != nil {
		return err
	}

	*o = PlaceDataRelationships(varPlaceDataRelationships)

	return err
}

type NullablePlaceDataRelationships struct {
	value *PlaceDataRelationships
	isSet bool
}

func (v NullablePlaceDataRelationships) Get() *PlaceDataRelationships {
	return v.value
}

func (v *NullablePlaceDataRelationships) Set(val *PlaceDataRelationships) {
	v.value = val
	v.isSet = true
}

func (v NullablePlaceDataRelationships) IsSet() bool {
	return v.isSet
}

func (v *NullablePlaceDataRelationships) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePlaceDataRelationships(val *PlaceDataRelationships) *NullablePlaceDataRelationships {
	return &NullablePlaceDataRelationships{value: val, isSet: true}
}

func (v NullablePlaceDataRelationships) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePlaceDataRelationships) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


