/*
Place Service API

API for managing places and their classes.

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"github.com/google/uuid"
	"bytes"
	"fmt"
)

// checks if the PlaceDataRelationshipsPlaceClass type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PlaceDataRelationshipsPlaceClass{}

// PlaceDataRelationshipsPlaceClass struct for PlaceDataRelationshipsPlaceClass
type PlaceDataRelationshipsPlaceClass struct {
	// The ID of the class associated with the place
	Id uuid.UUID `json:"id"`
	Type string `json:"type"`
}

type _PlaceDataRelationshipsPlaceClass PlaceDataRelationshipsPlaceClass

// NewPlaceDataRelationshipsPlaceClass instantiates a new PlaceDataRelationshipsPlaceClass object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPlaceDataRelationshipsPlaceClass(id uuid.UUID, type_ string) *PlaceDataRelationshipsPlaceClass {
	this := PlaceDataRelationshipsPlaceClass{}
	this.Id = id
	this.Type = type_
	return &this
}

// NewPlaceDataRelationshipsPlaceClassWithDefaults instantiates a new PlaceDataRelationshipsPlaceClass object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPlaceDataRelationshipsPlaceClassWithDefaults() *PlaceDataRelationshipsPlaceClass {
	this := PlaceDataRelationshipsPlaceClass{}
	return &this
}

// GetId returns the Id field value
func (o *PlaceDataRelationshipsPlaceClass) GetId() uuid.UUID {
	if o == nil {
		var ret uuid.UUID
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *PlaceDataRelationshipsPlaceClass) GetIdOk() (*uuid.UUID, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *PlaceDataRelationshipsPlaceClass) SetId(v uuid.UUID) {
	o.Id = v
}

// GetType returns the Type field value
func (o *PlaceDataRelationshipsPlaceClass) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *PlaceDataRelationshipsPlaceClass) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *PlaceDataRelationshipsPlaceClass) SetType(v string) {
	o.Type = v
}

func (o PlaceDataRelationshipsPlaceClass) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PlaceDataRelationshipsPlaceClass) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["type"] = o.Type
	return toSerialize, nil
}

func (o *PlaceDataRelationshipsPlaceClass) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPlaceDataRelationshipsPlaceClass := _PlaceDataRelationshipsPlaceClass{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPlaceDataRelationshipsPlaceClass)

	if err != nil {
		return err
	}

	*o = PlaceDataRelationshipsPlaceClass(varPlaceDataRelationshipsPlaceClass)

	return err
}

type NullablePlaceDataRelationshipsPlaceClass struct {
	value *PlaceDataRelationshipsPlaceClass
	isSet bool
}

func (v NullablePlaceDataRelationshipsPlaceClass) Get() *PlaceDataRelationshipsPlaceClass {
	return v.value
}

func (v *NullablePlaceDataRelationshipsPlaceClass) Set(val *PlaceDataRelationshipsPlaceClass) {
	v.value = val
	v.isSet = true
}

func (v NullablePlaceDataRelationshipsPlaceClass) IsSet() bool {
	return v.isSet
}

func (v *NullablePlaceDataRelationshipsPlaceClass) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePlaceDataRelationshipsPlaceClass(val *PlaceDataRelationshipsPlaceClass) *NullablePlaceDataRelationshipsPlaceClass {
	return &NullablePlaceDataRelationshipsPlaceClass{value: val, isSet: true}
}

func (v NullablePlaceDataRelationshipsPlaceClass) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePlaceDataRelationshipsPlaceClass) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


