/*
Place Service API

API for managing places and their classes.

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
)

// checks if the DeleteUploadPlaceMediaDataAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeleteUploadPlaceMediaDataAttributes{}

// DeleteUploadPlaceMediaDataAttributes struct for DeleteUploadPlaceMediaDataAttributes
type DeleteUploadPlaceMediaDataAttributes struct {
	// icon media key
	IconKey *string `json:"icon_key,omitempty"`
	// banner media key
	BannerKey *string `json:"banner_key,omitempty"`
}

// NewDeleteUploadPlaceMediaDataAttributes instantiates a new DeleteUploadPlaceMediaDataAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeleteUploadPlaceMediaDataAttributes() *DeleteUploadPlaceMediaDataAttributes {
	this := DeleteUploadPlaceMediaDataAttributes{}
	return &this
}

// NewDeleteUploadPlaceMediaDataAttributesWithDefaults instantiates a new DeleteUploadPlaceMediaDataAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeleteUploadPlaceMediaDataAttributesWithDefaults() *DeleteUploadPlaceMediaDataAttributes {
	this := DeleteUploadPlaceMediaDataAttributes{}
	return &this
}

// GetIconKey returns the IconKey field value if set, zero value otherwise.
func (o *DeleteUploadPlaceMediaDataAttributes) GetIconKey() string {
	if o == nil || IsNil(o.IconKey) {
		var ret string
		return ret
	}
	return *o.IconKey
}

// GetIconKeyOk returns a tuple with the IconKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeleteUploadPlaceMediaDataAttributes) GetIconKeyOk() (*string, bool) {
	if o == nil || IsNil(o.IconKey) {
		return nil, false
	}
	return o.IconKey, true
}

// HasIconKey returns a boolean if a field has been set.
func (o *DeleteUploadPlaceMediaDataAttributes) HasIconKey() bool {
	if o != nil && !IsNil(o.IconKey) {
		return true
	}

	return false
}

// SetIconKey gets a reference to the given string and assigns it to the IconKey field.
func (o *DeleteUploadPlaceMediaDataAttributes) SetIconKey(v string) {
	o.IconKey = &v
}

// GetBannerKey returns the BannerKey field value if set, zero value otherwise.
func (o *DeleteUploadPlaceMediaDataAttributes) GetBannerKey() string {
	if o == nil || IsNil(o.BannerKey) {
		var ret string
		return ret
	}
	return *o.BannerKey
}

// GetBannerKeyOk returns a tuple with the BannerKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeleteUploadPlaceMediaDataAttributes) GetBannerKeyOk() (*string, bool) {
	if o == nil || IsNil(o.BannerKey) {
		return nil, false
	}
	return o.BannerKey, true
}

// HasBannerKey returns a boolean if a field has been set.
func (o *DeleteUploadPlaceMediaDataAttributes) HasBannerKey() bool {
	if o != nil && !IsNil(o.BannerKey) {
		return true
	}

	return false
}

// SetBannerKey gets a reference to the given string and assigns it to the BannerKey field.
func (o *DeleteUploadPlaceMediaDataAttributes) SetBannerKey(v string) {
	o.BannerKey = &v
}

func (o DeleteUploadPlaceMediaDataAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeleteUploadPlaceMediaDataAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.IconKey) {
		toSerialize["icon_key"] = o.IconKey
	}
	if !IsNil(o.BannerKey) {
		toSerialize["banner_key"] = o.BannerKey
	}
	return toSerialize, nil
}

type NullableDeleteUploadPlaceMediaDataAttributes struct {
	value *DeleteUploadPlaceMediaDataAttributes
	isSet bool
}

func (v NullableDeleteUploadPlaceMediaDataAttributes) Get() *DeleteUploadPlaceMediaDataAttributes {
	return v.value
}

func (v *NullableDeleteUploadPlaceMediaDataAttributes) Set(val *DeleteUploadPlaceMediaDataAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableDeleteUploadPlaceMediaDataAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableDeleteUploadPlaceMediaDataAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeleteUploadPlaceMediaDataAttributes(val *DeleteUploadPlaceMediaDataAttributes) *NullableDeleteUploadPlaceMediaDataAttributes {
	return &NullableDeleteUploadPlaceMediaDataAttributes{value: val, isSet: true}
}

func (v NullableDeleteUploadPlaceMediaDataAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeleteUploadPlaceMediaDataAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


