/*
Place Service API

API for managing places and their classes.

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DeprecatedPlaceClass type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeprecatedPlaceClass{}

// DeprecatedPlaceClass struct for DeprecatedPlaceClass
type DeprecatedPlaceClass struct {
	Data DeprecatedPlaceClassData `json:"data"`
}

type _DeprecatedPlaceClass DeprecatedPlaceClass

// NewDeprecatedPlaceClass instantiates a new DeprecatedPlaceClass object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeprecatedPlaceClass(data DeprecatedPlaceClassData) *DeprecatedPlaceClass {
	this := DeprecatedPlaceClass{}
	this.Data = data
	return &this
}

// NewDeprecatedPlaceClassWithDefaults instantiates a new DeprecatedPlaceClass object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeprecatedPlaceClassWithDefaults() *DeprecatedPlaceClass {
	this := DeprecatedPlaceClass{}
	return &this
}

// GetData returns the Data field value
func (o *DeprecatedPlaceClass) GetData() DeprecatedPlaceClassData {
	if o == nil {
		var ret DeprecatedPlaceClassData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *DeprecatedPlaceClass) GetDataOk() (*DeprecatedPlaceClassData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *DeprecatedPlaceClass) SetData(v DeprecatedPlaceClassData) {
	o.Data = v
}

func (o DeprecatedPlaceClass) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeprecatedPlaceClass) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *DeprecatedPlaceClass) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDeprecatedPlaceClass := _DeprecatedPlaceClass{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDeprecatedPlaceClass)

	if err != nil {
		return err
	}

	*o = DeprecatedPlaceClass(varDeprecatedPlaceClass)

	return err
}

type NullableDeprecatedPlaceClass struct {
	value *DeprecatedPlaceClass
	isSet bool
}

func (v NullableDeprecatedPlaceClass) Get() *DeprecatedPlaceClass {
	return v.value
}

func (v *NullableDeprecatedPlaceClass) Set(val *DeprecatedPlaceClass) {
	v.value = val
	v.isSet = true
}

func (v NullableDeprecatedPlaceClass) IsSet() bool {
	return v.isSet
}

func (v *NullableDeprecatedPlaceClass) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeprecatedPlaceClass(val *DeprecatedPlaceClass) *NullableDeprecatedPlaceClass {
	return &NullableDeprecatedPlaceClass{value: val, isSet: true}
}

func (v NullableDeprecatedPlaceClass) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeprecatedPlaceClass) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


