/*
Place Service API

API for managing places and their classes.

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DeprecatedPlaceClassDataAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeprecatedPlaceClassDataAttributes{}

// DeprecatedPlaceClassDataAttributes struct for DeprecatedPlaceClassDataAttributes
type DeprecatedPlaceClassDataAttributes struct {
	// place class is deprecated?
	Deprecated bool `json:"deprecated"`
}

type _DeprecatedPlaceClassDataAttributes DeprecatedPlaceClassDataAttributes

// NewDeprecatedPlaceClassDataAttributes instantiates a new DeprecatedPlaceClassDataAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeprecatedPlaceClassDataAttributes(deprecated bool) *DeprecatedPlaceClassDataAttributes {
	this := DeprecatedPlaceClassDataAttributes{}
	this.Deprecated = deprecated
	return &this
}

// NewDeprecatedPlaceClassDataAttributesWithDefaults instantiates a new DeprecatedPlaceClassDataAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeprecatedPlaceClassDataAttributesWithDefaults() *DeprecatedPlaceClassDataAttributes {
	this := DeprecatedPlaceClassDataAttributes{}
	return &this
}

// GetDeprecated returns the Deprecated field value
func (o *DeprecatedPlaceClassDataAttributes) GetDeprecated() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Deprecated
}

// GetDeprecatedOk returns a tuple with the Deprecated field value
// and a boolean to check if the value has been set.
func (o *DeprecatedPlaceClassDataAttributes) GetDeprecatedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Deprecated, true
}

// SetDeprecated sets field value
func (o *DeprecatedPlaceClassDataAttributes) SetDeprecated(v bool) {
	o.Deprecated = v
}

func (o DeprecatedPlaceClassDataAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeprecatedPlaceClassDataAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["deprecated"] = o.Deprecated
	return toSerialize, nil
}

func (o *DeprecatedPlaceClassDataAttributes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"deprecated",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDeprecatedPlaceClassDataAttributes := _DeprecatedPlaceClassDataAttributes{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDeprecatedPlaceClassDataAttributes)

	if err != nil {
		return err
	}

	*o = DeprecatedPlaceClassDataAttributes(varDeprecatedPlaceClassDataAttributes)

	return err
}

type NullableDeprecatedPlaceClassDataAttributes struct {
	value *DeprecatedPlaceClassDataAttributes
	isSet bool
}

func (v NullableDeprecatedPlaceClassDataAttributes) Get() *DeprecatedPlaceClassDataAttributes {
	return v.value
}

func (v *NullableDeprecatedPlaceClassDataAttributes) Set(val *DeprecatedPlaceClassDataAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableDeprecatedPlaceClassDataAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableDeprecatedPlaceClassDataAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeprecatedPlaceClassDataAttributes(val *DeprecatedPlaceClassDataAttributes) *NullableDeprecatedPlaceClassDataAttributes {
	return &NullableDeprecatedPlaceClassDataAttributes{value: val, isSet: true}
}

func (v NullableDeprecatedPlaceClassDataAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeprecatedPlaceClassDataAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


