/*
Place Service API

API for managing places and their classes.

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"github.com/google/uuid"
	"bytes"
	"fmt"
)

// checks if the CreatePlaceClassDataAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreatePlaceClassDataAttributes{}

// CreatePlaceClassDataAttributes struct for CreatePlaceClassDataAttributes
type CreatePlaceClassDataAttributes struct {
	// The ID of the parent class, if any
	ParentId *uuid.UUID `json:"parent_id,omitempty"`
	// The name of the class
	Name string `json:"name"`
	// A brief description of the class
	Description string `json:"description"`
}

type _CreatePlaceClassDataAttributes CreatePlaceClassDataAttributes

// NewCreatePlaceClassDataAttributes instantiates a new CreatePlaceClassDataAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreatePlaceClassDataAttributes(name string, description string) *CreatePlaceClassDataAttributes {
	this := CreatePlaceClassDataAttributes{}
	this.Name = name
	this.Description = description
	return &this
}

// NewCreatePlaceClassDataAttributesWithDefaults instantiates a new CreatePlaceClassDataAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreatePlaceClassDataAttributesWithDefaults() *CreatePlaceClassDataAttributes {
	this := CreatePlaceClassDataAttributes{}
	return &this
}

// GetParentId returns the ParentId field value if set, zero value otherwise.
func (o *CreatePlaceClassDataAttributes) GetParentId() uuid.UUID {
	if o == nil || IsNil(o.ParentId) {
		var ret uuid.UUID
		return ret
	}
	return *o.ParentId
}

// GetParentIdOk returns a tuple with the ParentId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreatePlaceClassDataAttributes) GetParentIdOk() (*uuid.UUID, bool) {
	if o == nil || IsNil(o.ParentId) {
		return nil, false
	}
	return o.ParentId, true
}

// HasParentId returns a boolean if a field has been set.
func (o *CreatePlaceClassDataAttributes) HasParentId() bool {
	if o != nil && !IsNil(o.ParentId) {
		return true
	}

	return false
}

// SetParentId gets a reference to the given uuid.UUID and assigns it to the ParentId field.
func (o *CreatePlaceClassDataAttributes) SetParentId(v uuid.UUID) {
	o.ParentId = &v
}

// GetName returns the Name field value
func (o *CreatePlaceClassDataAttributes) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreatePlaceClassDataAttributes) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreatePlaceClassDataAttributes) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value
func (o *CreatePlaceClassDataAttributes) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *CreatePlaceClassDataAttributes) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *CreatePlaceClassDataAttributes) SetDescription(v string) {
	o.Description = v
}

func (o CreatePlaceClassDataAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreatePlaceClassDataAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ParentId) {
		toSerialize["parent_id"] = o.ParentId
	}
	toSerialize["name"] = o.Name
	toSerialize["description"] = o.Description
	return toSerialize, nil
}

func (o *CreatePlaceClassDataAttributes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"description",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreatePlaceClassDataAttributes := _CreatePlaceClassDataAttributes{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreatePlaceClassDataAttributes)

	if err != nil {
		return err
	}

	*o = CreatePlaceClassDataAttributes(varCreatePlaceClassDataAttributes)

	return err
}

type NullableCreatePlaceClassDataAttributes struct {
	value *CreatePlaceClassDataAttributes
	isSet bool
}

func (v NullableCreatePlaceClassDataAttributes) Get() *CreatePlaceClassDataAttributes {
	return v.value
}

func (v *NullableCreatePlaceClassDataAttributes) Set(val *CreatePlaceClassDataAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableCreatePlaceClassDataAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableCreatePlaceClassDataAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreatePlaceClassDataAttributes(val *CreatePlaceClassDataAttributes) *NullableCreatePlaceClassDataAttributes {
	return &NullableCreatePlaceClassDataAttributes{value: val, isSet: true}
}

func (v NullableCreatePlaceClassDataAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreatePlaceClassDataAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


