/*
Place Service API

API for managing places and their classes.

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the PlaceClassDataAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PlaceClassDataAttributes{}

// PlaceClassDataAttributes struct for PlaceClassDataAttributes
type PlaceClassDataAttributes struct {
	// The name of the class
	Name string `json:"name"`
	// A brief description of the class
	Description string `json:"description"`
	// A URL to an icon representing the class
	IconKey *string `json:"icon_key,omitempty"`
	// The version number of the class data, used for concurrency control
	Version int32 `json:"version"`
	// The date and time when the class was created
	CreatedAt time.Time `json:"created_at"`
	// The date and time when the class was last updated
	UpdatedAt time.Time `json:"updated_at"`
	// The date and time when the class was deprecated, if applicable
	DeprecatedAt *time.Time `json:"deprecated_at,omitempty"`
}

type _PlaceClassDataAttributes PlaceClassDataAttributes

// NewPlaceClassDataAttributes instantiates a new PlaceClassDataAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPlaceClassDataAttributes(name string, description string, version int32, createdAt time.Time, updatedAt time.Time) *PlaceClassDataAttributes {
	this := PlaceClassDataAttributes{}
	this.Name = name
	this.Description = description
	this.Version = version
	this.CreatedAt = createdAt
	this.UpdatedAt = updatedAt
	return &this
}

// NewPlaceClassDataAttributesWithDefaults instantiates a new PlaceClassDataAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPlaceClassDataAttributesWithDefaults() *PlaceClassDataAttributes {
	this := PlaceClassDataAttributes{}
	return &this
}

// GetName returns the Name field value
func (o *PlaceClassDataAttributes) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *PlaceClassDataAttributes) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *PlaceClassDataAttributes) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value
func (o *PlaceClassDataAttributes) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *PlaceClassDataAttributes) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *PlaceClassDataAttributes) SetDescription(v string) {
	o.Description = v
}

// GetIconKey returns the IconKey field value if set, zero value otherwise.
func (o *PlaceClassDataAttributes) GetIconKey() string {
	if o == nil || IsNil(o.IconKey) {
		var ret string
		return ret
	}
	return *o.IconKey
}

// GetIconKeyOk returns a tuple with the IconKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlaceClassDataAttributes) GetIconKeyOk() (*string, bool) {
	if o == nil || IsNil(o.IconKey) {
		return nil, false
	}
	return o.IconKey, true
}

// HasIconKey returns a boolean if a field has been set.
func (o *PlaceClassDataAttributes) HasIconKey() bool {
	if o != nil && !IsNil(o.IconKey) {
		return true
	}

	return false
}

// SetIconKey gets a reference to the given string and assigns it to the IconKey field.
func (o *PlaceClassDataAttributes) SetIconKey(v string) {
	o.IconKey = &v
}

// GetVersion returns the Version field value
func (o *PlaceClassDataAttributes) GetVersion() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Version
}

// GetVersionOk returns a tuple with the Version field value
// and a boolean to check if the value has been set.
func (o *PlaceClassDataAttributes) GetVersionOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Version, true
}

// SetVersion sets field value
func (o *PlaceClassDataAttributes) SetVersion(v int32) {
	o.Version = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *PlaceClassDataAttributes) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *PlaceClassDataAttributes) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *PlaceClassDataAttributes) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *PlaceClassDataAttributes) GetUpdatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *PlaceClassDataAttributes) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *PlaceClassDataAttributes) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = v
}

// GetDeprecatedAt returns the DeprecatedAt field value if set, zero value otherwise.
func (o *PlaceClassDataAttributes) GetDeprecatedAt() time.Time {
	if o == nil || IsNil(o.DeprecatedAt) {
		var ret time.Time
		return ret
	}
	return *o.DeprecatedAt
}

// GetDeprecatedAtOk returns a tuple with the DeprecatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlaceClassDataAttributes) GetDeprecatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.DeprecatedAt) {
		return nil, false
	}
	return o.DeprecatedAt, true
}

// HasDeprecatedAt returns a boolean if a field has been set.
func (o *PlaceClassDataAttributes) HasDeprecatedAt() bool {
	if o != nil && !IsNil(o.DeprecatedAt) {
		return true
	}

	return false
}

// SetDeprecatedAt gets a reference to the given time.Time and assigns it to the DeprecatedAt field.
func (o *PlaceClassDataAttributes) SetDeprecatedAt(v time.Time) {
	o.DeprecatedAt = &v
}

func (o PlaceClassDataAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PlaceClassDataAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["description"] = o.Description
	if !IsNil(o.IconKey) {
		toSerialize["icon_key"] = o.IconKey
	}
	toSerialize["version"] = o.Version
	toSerialize["created_at"] = o.CreatedAt
	toSerialize["updated_at"] = o.UpdatedAt
	if !IsNil(o.DeprecatedAt) {
		toSerialize["deprecated_at"] = o.DeprecatedAt
	}
	return toSerialize, nil
}

func (o *PlaceClassDataAttributes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"description",
		"version",
		"created_at",
		"updated_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPlaceClassDataAttributes := _PlaceClassDataAttributes{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPlaceClassDataAttributes)

	if err != nil {
		return err
	}

	*o = PlaceClassDataAttributes(varPlaceClassDataAttributes)

	return err
}

type NullablePlaceClassDataAttributes struct {
	value *PlaceClassDataAttributes
	isSet bool
}

func (v NullablePlaceClassDataAttributes) Get() *PlaceClassDataAttributes {
	return v.value
}

func (v *NullablePlaceClassDataAttributes) Set(val *PlaceClassDataAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullablePlaceClassDataAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullablePlaceClassDataAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePlaceClassDataAttributes(val *PlaceClassDataAttributes) *NullablePlaceClassDataAttributes {
	return &NullablePlaceClassDataAttributes{value: val, isSet: true}
}

func (v NullablePlaceClassDataAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePlaceClassDataAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


