/*
Place Service API

API for managing places and their classes.

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DeleteUploadPlaceClassIcon type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeleteUploadPlaceClassIcon{}

// DeleteUploadPlaceClassIcon struct for DeleteUploadPlaceClassIcon
type DeleteUploadPlaceClassIcon struct {
	Data DeleteUploadPlaceClassIconData `json:"data"`
}

type _DeleteUploadPlaceClassIcon DeleteUploadPlaceClassIcon

// NewDeleteUploadPlaceClassIcon instantiates a new DeleteUploadPlaceClassIcon object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeleteUploadPlaceClassIcon(data DeleteUploadPlaceClassIconData) *DeleteUploadPlaceClassIcon {
	this := DeleteUploadPlaceClassIcon{}
	this.Data = data
	return &this
}

// NewDeleteUploadPlaceClassIconWithDefaults instantiates a new DeleteUploadPlaceClassIcon object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeleteUploadPlaceClassIconWithDefaults() *DeleteUploadPlaceClassIcon {
	this := DeleteUploadPlaceClassIcon{}
	return &this
}

// GetData returns the Data field value
func (o *DeleteUploadPlaceClassIcon) GetData() DeleteUploadPlaceClassIconData {
	if o == nil {
		var ret DeleteUploadPlaceClassIconData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *DeleteUploadPlaceClassIcon) GetDataOk() (*DeleteUploadPlaceClassIconData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *DeleteUploadPlaceClassIcon) SetData(v DeleteUploadPlaceClassIconData) {
	o.Data = v
}

func (o DeleteUploadPlaceClassIcon) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeleteUploadPlaceClassIcon) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *DeleteUploadPlaceClassIcon) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDeleteUploadPlaceClassIcon := _DeleteUploadPlaceClassIcon{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDeleteUploadPlaceClassIcon)

	if err != nil {
		return err
	}

	*o = DeleteUploadPlaceClassIcon(varDeleteUploadPlaceClassIcon)

	return err
}

type NullableDeleteUploadPlaceClassIcon struct {
	value *DeleteUploadPlaceClassIcon
	isSet bool
}

func (v NullableDeleteUploadPlaceClassIcon) Get() *DeleteUploadPlaceClassIcon {
	return v.value
}

func (v *NullableDeleteUploadPlaceClassIcon) Set(val *DeleteUploadPlaceClassIcon) {
	v.value = val
	v.isSet = true
}

func (v NullableDeleteUploadPlaceClassIcon) IsSet() bool {
	return v.isSet
}

func (v *NullableDeleteUploadPlaceClassIcon) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeleteUploadPlaceClassIcon(val *DeleteUploadPlaceClassIcon) *NullableDeleteUploadPlaceClassIcon {
	return &NullableDeleteUploadPlaceClassIcon{value: val, isSet: true}
}

func (v NullableDeleteUploadPlaceClassIcon) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeleteUploadPlaceClassIcon) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


