/*
netbill places-svc API

API documentation for managing places and their classes.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"github.com/google/uuid"
)

// checks if the UpdatePlaceDataAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdatePlaceDataAttributes{}

// UpdatePlaceDataAttributes struct for UpdatePlaceDataAttributes
type UpdatePlaceDataAttributes struct {
	// The class ID of the place (e.g., restaurant, park)
	ClassId *uuid.UUID `json:"class_id,omitempty"`
	// The name of the place
	Name *string `json:"name,omitempty"`
	// The address of the place
	Address *string `json:"address,omitempty"`
	// A brief description of the place
	Description *string `json:"description,omitempty"`
	// The S3 key for the place's icon image
	IconKey *string `json:"icon_key,omitempty"`
	// The S3 key for the place's banner image
	BannerKey *string `json:"banner_key,omitempty"`
	// The website URL of the place
	Website *string `json:"website,omitempty"`
	// The contact phone number of the place
	Phone *string `json:"phone,omitempty"`
}

// NewUpdatePlaceDataAttributes instantiates a new UpdatePlaceDataAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdatePlaceDataAttributes() *UpdatePlaceDataAttributes {
	this := UpdatePlaceDataAttributes{}
	return &this
}

// NewUpdatePlaceDataAttributesWithDefaults instantiates a new UpdatePlaceDataAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdatePlaceDataAttributesWithDefaults() *UpdatePlaceDataAttributes {
	this := UpdatePlaceDataAttributes{}
	return &this
}

// GetClassId returns the ClassId field value if set, zero value otherwise.
func (o *UpdatePlaceDataAttributes) GetClassId() uuid.UUID {
	if o == nil || IsNil(o.ClassId) {
		var ret uuid.UUID
		return ret
	}
	return *o.ClassId
}

// GetClassIdOk returns a tuple with the ClassId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdatePlaceDataAttributes) GetClassIdOk() (*uuid.UUID, bool) {
	if o == nil || IsNil(o.ClassId) {
		return nil, false
	}
	return o.ClassId, true
}

// HasClassId returns a boolean if a field has been set.
func (o *UpdatePlaceDataAttributes) HasClassId() bool {
	if o != nil && !IsNil(o.ClassId) {
		return true
	}

	return false
}

// SetClassId gets a reference to the given uuid.UUID and assigns it to the ClassId field.
func (o *UpdatePlaceDataAttributes) SetClassId(v uuid.UUID) {
	o.ClassId = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *UpdatePlaceDataAttributes) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdatePlaceDataAttributes) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *UpdatePlaceDataAttributes) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *UpdatePlaceDataAttributes) SetName(v string) {
	o.Name = &v
}

// GetAddress returns the Address field value if set, zero value otherwise.
func (o *UpdatePlaceDataAttributes) GetAddress() string {
	if o == nil || IsNil(o.Address) {
		var ret string
		return ret
	}
	return *o.Address
}

// GetAddressOk returns a tuple with the Address field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdatePlaceDataAttributes) GetAddressOk() (*string, bool) {
	if o == nil || IsNil(o.Address) {
		return nil, false
	}
	return o.Address, true
}

// HasAddress returns a boolean if a field has been set.
func (o *UpdatePlaceDataAttributes) HasAddress() bool {
	if o != nil && !IsNil(o.Address) {
		return true
	}

	return false
}

// SetAddress gets a reference to the given string and assigns it to the Address field.
func (o *UpdatePlaceDataAttributes) SetAddress(v string) {
	o.Address = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *UpdatePlaceDataAttributes) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdatePlaceDataAttributes) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *UpdatePlaceDataAttributes) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *UpdatePlaceDataAttributes) SetDescription(v string) {
	o.Description = &v
}

// GetIconKey returns the IconKey field value if set, zero value otherwise.
func (o *UpdatePlaceDataAttributes) GetIconKey() string {
	if o == nil || IsNil(o.IconKey) {
		var ret string
		return ret
	}
	return *o.IconKey
}

// GetIconKeyOk returns a tuple with the IconKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdatePlaceDataAttributes) GetIconKeyOk() (*string, bool) {
	if o == nil || IsNil(o.IconKey) {
		return nil, false
	}
	return o.IconKey, true
}

// HasIconKey returns a boolean if a field has been set.
func (o *UpdatePlaceDataAttributes) HasIconKey() bool {
	if o != nil && !IsNil(o.IconKey) {
		return true
	}

	return false
}

// SetIconKey gets a reference to the given string and assigns it to the IconKey field.
func (o *UpdatePlaceDataAttributes) SetIconKey(v string) {
	o.IconKey = &v
}

// GetBannerKey returns the BannerKey field value if set, zero value otherwise.
func (o *UpdatePlaceDataAttributes) GetBannerKey() string {
	if o == nil || IsNil(o.BannerKey) {
		var ret string
		return ret
	}
	return *o.BannerKey
}

// GetBannerKeyOk returns a tuple with the BannerKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdatePlaceDataAttributes) GetBannerKeyOk() (*string, bool) {
	if o == nil || IsNil(o.BannerKey) {
		return nil, false
	}
	return o.BannerKey, true
}

// HasBannerKey returns a boolean if a field has been set.
func (o *UpdatePlaceDataAttributes) HasBannerKey() bool {
	if o != nil && !IsNil(o.BannerKey) {
		return true
	}

	return false
}

// SetBannerKey gets a reference to the given string and assigns it to the BannerKey field.
func (o *UpdatePlaceDataAttributes) SetBannerKey(v string) {
	o.BannerKey = &v
}

// GetWebsite returns the Website field value if set, zero value otherwise.
func (o *UpdatePlaceDataAttributes) GetWebsite() string {
	if o == nil || IsNil(o.Website) {
		var ret string
		return ret
	}
	return *o.Website
}

// GetWebsiteOk returns a tuple with the Website field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdatePlaceDataAttributes) GetWebsiteOk() (*string, bool) {
	if o == nil || IsNil(o.Website) {
		return nil, false
	}
	return o.Website, true
}

// HasWebsite returns a boolean if a field has been set.
func (o *UpdatePlaceDataAttributes) HasWebsite() bool {
	if o != nil && !IsNil(o.Website) {
		return true
	}

	return false
}

// SetWebsite gets a reference to the given string and assigns it to the Website field.
func (o *UpdatePlaceDataAttributes) SetWebsite(v string) {
	o.Website = &v
}

// GetPhone returns the Phone field value if set, zero value otherwise.
func (o *UpdatePlaceDataAttributes) GetPhone() string {
	if o == nil || IsNil(o.Phone) {
		var ret string
		return ret
	}
	return *o.Phone
}

// GetPhoneOk returns a tuple with the Phone field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdatePlaceDataAttributes) GetPhoneOk() (*string, bool) {
	if o == nil || IsNil(o.Phone) {
		return nil, false
	}
	return o.Phone, true
}

// HasPhone returns a boolean if a field has been set.
func (o *UpdatePlaceDataAttributes) HasPhone() bool {
	if o != nil && !IsNil(o.Phone) {
		return true
	}

	return false
}

// SetPhone gets a reference to the given string and assigns it to the Phone field.
func (o *UpdatePlaceDataAttributes) SetPhone(v string) {
	o.Phone = &v
}

func (o UpdatePlaceDataAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdatePlaceDataAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ClassId) {
		toSerialize["class_id"] = o.ClassId
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Address) {
		toSerialize["address"] = o.Address
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.IconKey) {
		toSerialize["icon_key"] = o.IconKey
	}
	if !IsNil(o.BannerKey) {
		toSerialize["banner_key"] = o.BannerKey
	}
	if !IsNil(o.Website) {
		toSerialize["website"] = o.Website
	}
	if !IsNil(o.Phone) {
		toSerialize["phone"] = o.Phone
	}
	return toSerialize, nil
}

type NullableUpdatePlaceDataAttributes struct {
	value *UpdatePlaceDataAttributes
	isSet bool
}

func (v NullableUpdatePlaceDataAttributes) Get() *UpdatePlaceDataAttributes {
	return v.value
}

func (v *NullableUpdatePlaceDataAttributes) Set(val *UpdatePlaceDataAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdatePlaceDataAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdatePlaceDataAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdatePlaceDataAttributes(val *UpdatePlaceDataAttributes) *NullableUpdatePlaceDataAttributes {
	return &NullableUpdatePlaceDataAttributes{value: val, isSet: true}
}

func (v NullableUpdatePlaceDataAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdatePlaceDataAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


