/*
Place Service API

API for managing places and their classes.

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UpdatePlaceClass type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdatePlaceClass{}

// UpdatePlaceClass struct for UpdatePlaceClass
type UpdatePlaceClass struct {
	Data UpdatePlaceClassData `json:"data"`
}

type _UpdatePlaceClass UpdatePlaceClass

// NewUpdatePlaceClass instantiates a new UpdatePlaceClass object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdatePlaceClass(data UpdatePlaceClassData) *UpdatePlaceClass {
	this := UpdatePlaceClass{}
	this.Data = data
	return &this
}

// NewUpdatePlaceClassWithDefaults instantiates a new UpdatePlaceClass object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdatePlaceClassWithDefaults() *UpdatePlaceClass {
	this := UpdatePlaceClass{}
	return &this
}

// GetData returns the Data field value
func (o *UpdatePlaceClass) GetData() UpdatePlaceClassData {
	if o == nil {
		var ret UpdatePlaceClassData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *UpdatePlaceClass) GetDataOk() (*UpdatePlaceClassData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *UpdatePlaceClass) SetData(v UpdatePlaceClassData) {
	o.Data = v
}

func (o UpdatePlaceClass) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdatePlaceClass) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *UpdatePlaceClass) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdatePlaceClass := _UpdatePlaceClass{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdatePlaceClass)

	if err != nil {
		return err
	}

	*o = UpdatePlaceClass(varUpdatePlaceClass)

	return err
}

type NullableUpdatePlaceClass struct {
	value *UpdatePlaceClass
	isSet bool
}

func (v NullableUpdatePlaceClass) Get() *UpdatePlaceClass {
	return v.value
}

func (v *NullableUpdatePlaceClass) Set(val *UpdatePlaceClass) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdatePlaceClass) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdatePlaceClass) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdatePlaceClass(val *UpdatePlaceClass) *NullableUpdatePlaceClass {
	return &NullableUpdatePlaceClass{value: val, isSet: true}
}

func (v NullableUpdatePlaceClass) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdatePlaceClass) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


