/*
Place Service API

API for managing places and their classes.

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreatePlaceDataAttributesPoint type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreatePlaceDataAttributesPoint{}

// CreatePlaceDataAttributesPoint struct for CreatePlaceDataAttributesPoint
type CreatePlaceDataAttributesPoint struct {
	// The latitude coordinate of the place
	Latitude float64 `json:"latitude"`
	// The longitude coordinate of the place
	Longitude float64 `json:"longitude"`
}

type _CreatePlaceDataAttributesPoint CreatePlaceDataAttributesPoint

// NewCreatePlaceDataAttributesPoint instantiates a new CreatePlaceDataAttributesPoint object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreatePlaceDataAttributesPoint(latitude float64, longitude float64) *CreatePlaceDataAttributesPoint {
	this := CreatePlaceDataAttributesPoint{}
	this.Latitude = latitude
	this.Longitude = longitude
	return &this
}

// NewCreatePlaceDataAttributesPointWithDefaults instantiates a new CreatePlaceDataAttributesPoint object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreatePlaceDataAttributesPointWithDefaults() *CreatePlaceDataAttributesPoint {
	this := CreatePlaceDataAttributesPoint{}
	return &this
}

// GetLatitude returns the Latitude field value
func (o *CreatePlaceDataAttributesPoint) GetLatitude() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.Latitude
}

// GetLatitudeOk returns a tuple with the Latitude field value
// and a boolean to check if the value has been set.
func (o *CreatePlaceDataAttributesPoint) GetLatitudeOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Latitude, true
}

// SetLatitude sets field value
func (o *CreatePlaceDataAttributesPoint) SetLatitude(v float64) {
	o.Latitude = v
}

// GetLongitude returns the Longitude field value
func (o *CreatePlaceDataAttributesPoint) GetLongitude() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.Longitude
}

// GetLongitudeOk returns a tuple with the Longitude field value
// and a boolean to check if the value has been set.
func (o *CreatePlaceDataAttributesPoint) GetLongitudeOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Longitude, true
}

// SetLongitude sets field value
func (o *CreatePlaceDataAttributesPoint) SetLongitude(v float64) {
	o.Longitude = v
}

func (o CreatePlaceDataAttributesPoint) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreatePlaceDataAttributesPoint) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["latitude"] = o.Latitude
	toSerialize["longitude"] = o.Longitude
	return toSerialize, nil
}

func (o *CreatePlaceDataAttributesPoint) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"latitude",
		"longitude",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreatePlaceDataAttributesPoint := _CreatePlaceDataAttributesPoint{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreatePlaceDataAttributesPoint)

	if err != nil {
		return err
	}

	*o = CreatePlaceDataAttributesPoint(varCreatePlaceDataAttributesPoint)

	return err
}

type NullableCreatePlaceDataAttributesPoint struct {
	value *CreatePlaceDataAttributesPoint
	isSet bool
}

func (v NullableCreatePlaceDataAttributesPoint) Get() *CreatePlaceDataAttributesPoint {
	return v.value
}

func (v *NullableCreatePlaceDataAttributesPoint) Set(val *CreatePlaceDataAttributesPoint) {
	v.value = val
	v.isSet = true
}

func (v NullableCreatePlaceDataAttributesPoint) IsSet() bool {
	return v.isSet
}

func (v *NullableCreatePlaceDataAttributesPoint) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreatePlaceDataAttributesPoint(val *CreatePlaceDataAttributesPoint) *NullableCreatePlaceDataAttributesPoint {
	return &NullableCreatePlaceDataAttributesPoint{value: val, isSet: true}
}

func (v NullableCreatePlaceDataAttributesPoint) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreatePlaceDataAttributesPoint) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


