/*
Place Service API

API for managing places and their classes.

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the OrganizationDataAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OrganizationDataAttributes{}

// OrganizationDataAttributes struct for OrganizationDataAttributes
type OrganizationDataAttributes struct {
	// The status of the organization
	Status string `json:"status"`
	// The name of the organization
	Name string `json:"name"`
	// The media key for the organization's icon
	IconKey *string `json:"icon_key,omitempty"`
	// The media key for the organization's banner
	BannerKey *string `json:"banner_key,omitempty"`
	// The version number of the organization, used for optimistic concurrency control
	Version int32 `json:"version"`
	// The date and time when the organization was created
	CreatedAt time.Time `json:"created_at"`
	// The date and time when the organization was last updated
	UpdatedAt time.Time `json:"updated_at"`
}

type _OrganizationDataAttributes OrganizationDataAttributes

// NewOrganizationDataAttributes instantiates a new OrganizationDataAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrganizationDataAttributes(status string, name string, version int32, createdAt time.Time, updatedAt time.Time) *OrganizationDataAttributes {
	this := OrganizationDataAttributes{}
	this.Status = status
	this.Name = name
	this.Version = version
	this.CreatedAt = createdAt
	this.UpdatedAt = updatedAt
	return &this
}

// NewOrganizationDataAttributesWithDefaults instantiates a new OrganizationDataAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrganizationDataAttributesWithDefaults() *OrganizationDataAttributes {
	this := OrganizationDataAttributes{}
	return &this
}

// GetStatus returns the Status field value
func (o *OrganizationDataAttributes) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *OrganizationDataAttributes) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *OrganizationDataAttributes) SetStatus(v string) {
	o.Status = v
}

// GetName returns the Name field value
func (o *OrganizationDataAttributes) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *OrganizationDataAttributes) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *OrganizationDataAttributes) SetName(v string) {
	o.Name = v
}

// GetIconKey returns the IconKey field value if set, zero value otherwise.
func (o *OrganizationDataAttributes) GetIconKey() string {
	if o == nil || IsNil(o.IconKey) {
		var ret string
		return ret
	}
	return *o.IconKey
}

// GetIconKeyOk returns a tuple with the IconKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganizationDataAttributes) GetIconKeyOk() (*string, bool) {
	if o == nil || IsNil(o.IconKey) {
		return nil, false
	}
	return o.IconKey, true
}

// HasIconKey returns a boolean if a field has been set.
func (o *OrganizationDataAttributes) HasIconKey() bool {
	if o != nil && !IsNil(o.IconKey) {
		return true
	}

	return false
}

// SetIconKey gets a reference to the given string and assigns it to the IconKey field.
func (o *OrganizationDataAttributes) SetIconKey(v string) {
	o.IconKey = &v
}

// GetBannerKey returns the BannerKey field value if set, zero value otherwise.
func (o *OrganizationDataAttributes) GetBannerKey() string {
	if o == nil || IsNil(o.BannerKey) {
		var ret string
		return ret
	}
	return *o.BannerKey
}

// GetBannerKeyOk returns a tuple with the BannerKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganizationDataAttributes) GetBannerKeyOk() (*string, bool) {
	if o == nil || IsNil(o.BannerKey) {
		return nil, false
	}
	return o.BannerKey, true
}

// HasBannerKey returns a boolean if a field has been set.
func (o *OrganizationDataAttributes) HasBannerKey() bool {
	if o != nil && !IsNil(o.BannerKey) {
		return true
	}

	return false
}

// SetBannerKey gets a reference to the given string and assigns it to the BannerKey field.
func (o *OrganizationDataAttributes) SetBannerKey(v string) {
	o.BannerKey = &v
}

// GetVersion returns the Version field value
func (o *OrganizationDataAttributes) GetVersion() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Version
}

// GetVersionOk returns a tuple with the Version field value
// and a boolean to check if the value has been set.
func (o *OrganizationDataAttributes) GetVersionOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Version, true
}

// SetVersion sets field value
func (o *OrganizationDataAttributes) SetVersion(v int32) {
	o.Version = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *OrganizationDataAttributes) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *OrganizationDataAttributes) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *OrganizationDataAttributes) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *OrganizationDataAttributes) GetUpdatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *OrganizationDataAttributes) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *OrganizationDataAttributes) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = v
}

func (o OrganizationDataAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OrganizationDataAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["status"] = o.Status
	toSerialize["name"] = o.Name
	if !IsNil(o.IconKey) {
		toSerialize["icon_key"] = o.IconKey
	}
	if !IsNil(o.BannerKey) {
		toSerialize["banner_key"] = o.BannerKey
	}
	toSerialize["version"] = o.Version
	toSerialize["created_at"] = o.CreatedAt
	toSerialize["updated_at"] = o.UpdatedAt
	return toSerialize, nil
}

func (o *OrganizationDataAttributes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"status",
		"name",
		"version",
		"created_at",
		"updated_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOrganizationDataAttributes := _OrganizationDataAttributes{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOrganizationDataAttributes)

	if err != nil {
		return err
	}

	*o = OrganizationDataAttributes(varOrganizationDataAttributes)

	return err
}

type NullableOrganizationDataAttributes struct {
	value *OrganizationDataAttributes
	isSet bool
}

func (v NullableOrganizationDataAttributes) Get() *OrganizationDataAttributes {
	return v.value
}

func (v *NullableOrganizationDataAttributes) Set(val *OrganizationDataAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableOrganizationDataAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableOrganizationDataAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrganizationDataAttributes(val *OrganizationDataAttributes) *NullableOrganizationDataAttributes {
	return &NullableOrganizationDataAttributes{value: val, isSet: true}
}

func (v NullableOrganizationDataAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrganizationDataAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


