/*
Place Service API

API for managing places and their classes.

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DeleteUploadPlaceIconDataAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeleteUploadPlaceIconDataAttributes{}

// DeleteUploadPlaceIconDataAttributes struct for DeleteUploadPlaceIconDataAttributes
type DeleteUploadPlaceIconDataAttributes struct {
	// icon media key
	IconKey string `json:"icon_key"`
}

type _DeleteUploadPlaceIconDataAttributes DeleteUploadPlaceIconDataAttributes

// NewDeleteUploadPlaceIconDataAttributes instantiates a new DeleteUploadPlaceIconDataAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeleteUploadPlaceIconDataAttributes(iconKey string) *DeleteUploadPlaceIconDataAttributes {
	this := DeleteUploadPlaceIconDataAttributes{}
	this.IconKey = iconKey
	return &this
}

// NewDeleteUploadPlaceIconDataAttributesWithDefaults instantiates a new DeleteUploadPlaceIconDataAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeleteUploadPlaceIconDataAttributesWithDefaults() *DeleteUploadPlaceIconDataAttributes {
	this := DeleteUploadPlaceIconDataAttributes{}
	return &this
}

// GetIconKey returns the IconKey field value
func (o *DeleteUploadPlaceIconDataAttributes) GetIconKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.IconKey
}

// GetIconKeyOk returns a tuple with the IconKey field value
// and a boolean to check if the value has been set.
func (o *DeleteUploadPlaceIconDataAttributes) GetIconKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IconKey, true
}

// SetIconKey sets field value
func (o *DeleteUploadPlaceIconDataAttributes) SetIconKey(v string) {
	o.IconKey = v
}

func (o DeleteUploadPlaceIconDataAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeleteUploadPlaceIconDataAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["icon_key"] = o.IconKey
	return toSerialize, nil
}

func (o *DeleteUploadPlaceIconDataAttributes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"icon_key",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDeleteUploadPlaceIconDataAttributes := _DeleteUploadPlaceIconDataAttributes{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDeleteUploadPlaceIconDataAttributes)

	if err != nil {
		return err
	}

	*o = DeleteUploadPlaceIconDataAttributes(varDeleteUploadPlaceIconDataAttributes)

	return err
}

type NullableDeleteUploadPlaceIconDataAttributes struct {
	value *DeleteUploadPlaceIconDataAttributes
	isSet bool
}

func (v NullableDeleteUploadPlaceIconDataAttributes) Get() *DeleteUploadPlaceIconDataAttributes {
	return v.value
}

func (v *NullableDeleteUploadPlaceIconDataAttributes) Set(val *DeleteUploadPlaceIconDataAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableDeleteUploadPlaceIconDataAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableDeleteUploadPlaceIconDataAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeleteUploadPlaceIconDataAttributes(val *DeleteUploadPlaceIconDataAttributes) *NullableDeleteUploadPlaceIconDataAttributes {
	return &NullableDeleteUploadPlaceIconDataAttributes{value: val, isSet: true}
}

func (v NullableDeleteUploadPlaceIconDataAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeleteUploadPlaceIconDataAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


