/*
Place Service API

API for managing places and their classes.

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"github.com/google/uuid"
	"bytes"
	"fmt"
)

// checks if the PlaceClassDataRelationshipsParent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PlaceClassDataRelationshipsParent{}

// PlaceClassDataRelationshipsParent struct for PlaceClassDataRelationshipsParent
type PlaceClassDataRelationshipsParent struct {
	// The ID of the parent class
	Id uuid.UUID `json:"id"`
	Type string `json:"type"`
}

type _PlaceClassDataRelationshipsParent PlaceClassDataRelationshipsParent

// NewPlaceClassDataRelationshipsParent instantiates a new PlaceClassDataRelationshipsParent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPlaceClassDataRelationshipsParent(id uuid.UUID, type_ string) *PlaceClassDataRelationshipsParent {
	this := PlaceClassDataRelationshipsParent{}
	this.Id = id
	this.Type = type_
	return &this
}

// NewPlaceClassDataRelationshipsParentWithDefaults instantiates a new PlaceClassDataRelationshipsParent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPlaceClassDataRelationshipsParentWithDefaults() *PlaceClassDataRelationshipsParent {
	this := PlaceClassDataRelationshipsParent{}
	return &this
}

// GetId returns the Id field value
func (o *PlaceClassDataRelationshipsParent) GetId() uuid.UUID {
	if o == nil {
		var ret uuid.UUID
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *PlaceClassDataRelationshipsParent) GetIdOk() (*uuid.UUID, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *PlaceClassDataRelationshipsParent) SetId(v uuid.UUID) {
	o.Id = v
}

// GetType returns the Type field value
func (o *PlaceClassDataRelationshipsParent) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *PlaceClassDataRelationshipsParent) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *PlaceClassDataRelationshipsParent) SetType(v string) {
	o.Type = v
}

func (o PlaceClassDataRelationshipsParent) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PlaceClassDataRelationshipsParent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["type"] = o.Type
	return toSerialize, nil
}

func (o *PlaceClassDataRelationshipsParent) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPlaceClassDataRelationshipsParent := _PlaceClassDataRelationshipsParent{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPlaceClassDataRelationshipsParent)

	if err != nil {
		return err
	}

	*o = PlaceClassDataRelationshipsParent(varPlaceClassDataRelationshipsParent)

	return err
}

type NullablePlaceClassDataRelationshipsParent struct {
	value *PlaceClassDataRelationshipsParent
	isSet bool
}

func (v NullablePlaceClassDataRelationshipsParent) Get() *PlaceClassDataRelationshipsParent {
	return v.value
}

func (v *NullablePlaceClassDataRelationshipsParent) Set(val *PlaceClassDataRelationshipsParent) {
	v.value = val
	v.isSet = true
}

func (v NullablePlaceClassDataRelationshipsParent) IsSet() bool {
	return v.isSet
}

func (v *NullablePlaceClassDataRelationshipsParent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePlaceClassDataRelationshipsParent(val *PlaceClassDataRelationshipsParent) *NullablePlaceClassDataRelationshipsParent {
	return &NullablePlaceClassDataRelationshipsParent{value: val, isSet: true}
}

func (v NullablePlaceClassDataRelationshipsParent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePlaceClassDataRelationshipsParent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


