/*
Place Service API

API for managing places and their classes.

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"github.com/google/uuid"
	"bytes"
	"fmt"
)

// checks if the DeleteUploadPlaceMediaData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeleteUploadPlaceMediaData{}

// DeleteUploadPlaceMediaData struct for DeleteUploadPlaceMediaData
type DeleteUploadPlaceMediaData struct {
	// place id
	Id uuid.UUID `json:"id"`
	Type string `json:"type"`
	Attributes DeleteUploadPlaceMediaDataAttributes `json:"attributes"`
}

type _DeleteUploadPlaceMediaData DeleteUploadPlaceMediaData

// NewDeleteUploadPlaceMediaData instantiates a new DeleteUploadPlaceMediaData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeleteUploadPlaceMediaData(id uuid.UUID, type_ string, attributes DeleteUploadPlaceMediaDataAttributes) *DeleteUploadPlaceMediaData {
	this := DeleteUploadPlaceMediaData{}
	this.Id = id
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewDeleteUploadPlaceMediaDataWithDefaults instantiates a new DeleteUploadPlaceMediaData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeleteUploadPlaceMediaDataWithDefaults() *DeleteUploadPlaceMediaData {
	this := DeleteUploadPlaceMediaData{}
	return &this
}

// GetId returns the Id field value
func (o *DeleteUploadPlaceMediaData) GetId() uuid.UUID {
	if o == nil {
		var ret uuid.UUID
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *DeleteUploadPlaceMediaData) GetIdOk() (*uuid.UUID, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *DeleteUploadPlaceMediaData) SetId(v uuid.UUID) {
	o.Id = v
}

// GetType returns the Type field value
func (o *DeleteUploadPlaceMediaData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *DeleteUploadPlaceMediaData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *DeleteUploadPlaceMediaData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *DeleteUploadPlaceMediaData) GetAttributes() DeleteUploadPlaceMediaDataAttributes {
	if o == nil {
		var ret DeleteUploadPlaceMediaDataAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *DeleteUploadPlaceMediaData) GetAttributesOk() (*DeleteUploadPlaceMediaDataAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *DeleteUploadPlaceMediaData) SetAttributes(v DeleteUploadPlaceMediaDataAttributes) {
	o.Attributes = v
}

func (o DeleteUploadPlaceMediaData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeleteUploadPlaceMediaData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	return toSerialize, nil
}

func (o *DeleteUploadPlaceMediaData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDeleteUploadPlaceMediaData := _DeleteUploadPlaceMediaData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDeleteUploadPlaceMediaData)

	if err != nil {
		return err
	}

	*o = DeleteUploadPlaceMediaData(varDeleteUploadPlaceMediaData)

	return err
}

type NullableDeleteUploadPlaceMediaData struct {
	value *DeleteUploadPlaceMediaData
	isSet bool
}

func (v NullableDeleteUploadPlaceMediaData) Get() *DeleteUploadPlaceMediaData {
	return v.value
}

func (v *NullableDeleteUploadPlaceMediaData) Set(val *DeleteUploadPlaceMediaData) {
	v.value = val
	v.isSet = true
}

func (v NullableDeleteUploadPlaceMediaData) IsSet() bool {
	return v.isSet
}

func (v *NullableDeleteUploadPlaceMediaData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeleteUploadPlaceMediaData(val *DeleteUploadPlaceMediaData) *NullableDeleteUploadPlaceMediaData {
	return &NullableDeleteUploadPlaceMediaData{value: val, isSet: true}
}

func (v NullableDeleteUploadPlaceMediaData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeleteUploadPlaceMediaData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


