/*
netbill places-svc API

API documentation for managing places and their classes.

API version: 0.1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DeleteUploadPlaceMedia type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeleteUploadPlaceMedia{}

// DeleteUploadPlaceMedia struct for DeleteUploadPlaceMedia
type DeleteUploadPlaceMedia struct {
	Data DeleteUploadPlaceMediaData `json:"data"`
}

type _DeleteUploadPlaceMedia DeleteUploadPlaceMedia

// NewDeleteUploadPlaceMedia instantiates a new DeleteUploadPlaceMedia object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeleteUploadPlaceMedia(data DeleteUploadPlaceMediaData) *DeleteUploadPlaceMedia {
	this := DeleteUploadPlaceMedia{}
	this.Data = data
	return &this
}

// NewDeleteUploadPlaceMediaWithDefaults instantiates a new DeleteUploadPlaceMedia object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeleteUploadPlaceMediaWithDefaults() *DeleteUploadPlaceMedia {
	this := DeleteUploadPlaceMedia{}
	return &this
}

// GetData returns the Data field value
func (o *DeleteUploadPlaceMedia) GetData() DeleteUploadPlaceMediaData {
	if o == nil {
		var ret DeleteUploadPlaceMediaData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *DeleteUploadPlaceMedia) GetDataOk() (*DeleteUploadPlaceMediaData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *DeleteUploadPlaceMedia) SetData(v DeleteUploadPlaceMediaData) {
	o.Data = v
}

func (o DeleteUploadPlaceMedia) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeleteUploadPlaceMedia) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *DeleteUploadPlaceMedia) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDeleteUploadPlaceMedia := _DeleteUploadPlaceMedia{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDeleteUploadPlaceMedia)

	if err != nil {
		return err
	}

	*o = DeleteUploadPlaceMedia(varDeleteUploadPlaceMedia)

	return err
}

type NullableDeleteUploadPlaceMedia struct {
	value *DeleteUploadPlaceMedia
	isSet bool
}

func (v NullableDeleteUploadPlaceMedia) Get() *DeleteUploadPlaceMedia {
	return v.value
}

func (v *NullableDeleteUploadPlaceMedia) Set(val *DeleteUploadPlaceMedia) {
	v.value = val
	v.isSet = true
}

func (v NullableDeleteUploadPlaceMedia) IsSet() bool {
	return v.isSet
}

func (v *NullableDeleteUploadPlaceMedia) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeleteUploadPlaceMedia(val *DeleteUploadPlaceMedia) *NullableDeleteUploadPlaceMedia {
	return &NullableDeleteUploadPlaceMedia{value: val, isSet: true}
}

func (v NullableDeleteUploadPlaceMedia) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeleteUploadPlaceMedia) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


