/*
Place Service API

API for managing places and their classes.

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
)

// checks if the DeleteUploadPlaceClassMediaDataAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeleteUploadPlaceClassMediaDataAttributes{}

// DeleteUploadPlaceClassMediaDataAttributes struct for DeleteUploadPlaceClassMediaDataAttributes
type DeleteUploadPlaceClassMediaDataAttributes struct {
	// icon media key
	IconKey *string `json:"icon_key,omitempty"`
}

// NewDeleteUploadPlaceClassMediaDataAttributes instantiates a new DeleteUploadPlaceClassMediaDataAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeleteUploadPlaceClassMediaDataAttributes() *DeleteUploadPlaceClassMediaDataAttributes {
	this := DeleteUploadPlaceClassMediaDataAttributes{}
	return &this
}

// NewDeleteUploadPlaceClassMediaDataAttributesWithDefaults instantiates a new DeleteUploadPlaceClassMediaDataAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeleteUploadPlaceClassMediaDataAttributesWithDefaults() *DeleteUploadPlaceClassMediaDataAttributes {
	this := DeleteUploadPlaceClassMediaDataAttributes{}
	return &this
}

// GetIconKey returns the IconKey field value if set, zero value otherwise.
func (o *DeleteUploadPlaceClassMediaDataAttributes) GetIconKey() string {
	if o == nil || IsNil(o.IconKey) {
		var ret string
		return ret
	}
	return *o.IconKey
}

// GetIconKeyOk returns a tuple with the IconKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeleteUploadPlaceClassMediaDataAttributes) GetIconKeyOk() (*string, bool) {
	if o == nil || IsNil(o.IconKey) {
		return nil, false
	}
	return o.IconKey, true
}

// HasIconKey returns a boolean if a field has been set.
func (o *DeleteUploadPlaceClassMediaDataAttributes) HasIconKey() bool {
	if o != nil && !IsNil(o.IconKey) {
		return true
	}

	return false
}

// SetIconKey gets a reference to the given string and assigns it to the IconKey field.
func (o *DeleteUploadPlaceClassMediaDataAttributes) SetIconKey(v string) {
	o.IconKey = &v
}

func (o DeleteUploadPlaceClassMediaDataAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeleteUploadPlaceClassMediaDataAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.IconKey) {
		toSerialize["icon_key"] = o.IconKey
	}
	return toSerialize, nil
}

type NullableDeleteUploadPlaceClassMediaDataAttributes struct {
	value *DeleteUploadPlaceClassMediaDataAttributes
	isSet bool
}

func (v NullableDeleteUploadPlaceClassMediaDataAttributes) Get() *DeleteUploadPlaceClassMediaDataAttributes {
	return v.value
}

func (v *NullableDeleteUploadPlaceClassMediaDataAttributes) Set(val *DeleteUploadPlaceClassMediaDataAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableDeleteUploadPlaceClassMediaDataAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableDeleteUploadPlaceClassMediaDataAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeleteUploadPlaceClassMediaDataAttributes(val *DeleteUploadPlaceClassMediaDataAttributes) *NullableDeleteUploadPlaceClassMediaDataAttributes {
	return &NullableDeleteUploadPlaceClassMediaDataAttributes{value: val, isSet: true}
}

func (v NullableDeleteUploadPlaceClassMediaDataAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeleteUploadPlaceClassMediaDataAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


