/*
Place Service API

API for managing places and their classes.

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"github.com/google/uuid"
	"bytes"
	"fmt"
)

// checks if the UpdatePlaceClassDataAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdatePlaceClassDataAttributes{}

// UpdatePlaceClassDataAttributes struct for UpdatePlaceClassDataAttributes
type UpdatePlaceClassDataAttributes struct {
	// The ID of the parent class, if any
	ParentId *uuid.UUID `json:"parent_id,omitempty"`
	// The name of the class
	Name string `json:"name"`
	// A brief description of the class
	Description string `json:"description"`
	// The S3 key for the class icon
	IconKey *string `json:"icon_key,omitempty"`
}

type _UpdatePlaceClassDataAttributes UpdatePlaceClassDataAttributes

// NewUpdatePlaceClassDataAttributes instantiates a new UpdatePlaceClassDataAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdatePlaceClassDataAttributes(name string, description string) *UpdatePlaceClassDataAttributes {
	this := UpdatePlaceClassDataAttributes{}
	this.Name = name
	this.Description = description
	return &this
}

// NewUpdatePlaceClassDataAttributesWithDefaults instantiates a new UpdatePlaceClassDataAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdatePlaceClassDataAttributesWithDefaults() *UpdatePlaceClassDataAttributes {
	this := UpdatePlaceClassDataAttributes{}
	return &this
}

// GetParentId returns the ParentId field value if set, zero value otherwise.
func (o *UpdatePlaceClassDataAttributes) GetParentId() uuid.UUID {
	if o == nil || IsNil(o.ParentId) {
		var ret uuid.UUID
		return ret
	}
	return *o.ParentId
}

// GetParentIdOk returns a tuple with the ParentId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdatePlaceClassDataAttributes) GetParentIdOk() (*uuid.UUID, bool) {
	if o == nil || IsNil(o.ParentId) {
		return nil, false
	}
	return o.ParentId, true
}

// HasParentId returns a boolean if a field has been set.
func (o *UpdatePlaceClassDataAttributes) HasParentId() bool {
	if o != nil && !IsNil(o.ParentId) {
		return true
	}

	return false
}

// SetParentId gets a reference to the given uuid.UUID and assigns it to the ParentId field.
func (o *UpdatePlaceClassDataAttributes) SetParentId(v uuid.UUID) {
	o.ParentId = &v
}

// GetName returns the Name field value
func (o *UpdatePlaceClassDataAttributes) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *UpdatePlaceClassDataAttributes) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *UpdatePlaceClassDataAttributes) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value
func (o *UpdatePlaceClassDataAttributes) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *UpdatePlaceClassDataAttributes) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *UpdatePlaceClassDataAttributes) SetDescription(v string) {
	o.Description = v
}

// GetIconKey returns the IconKey field value if set, zero value otherwise.
func (o *UpdatePlaceClassDataAttributes) GetIconKey() string {
	if o == nil || IsNil(o.IconKey) {
		var ret string
		return ret
	}
	return *o.IconKey
}

// GetIconKeyOk returns a tuple with the IconKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdatePlaceClassDataAttributes) GetIconKeyOk() (*string, bool) {
	if o == nil || IsNil(o.IconKey) {
		return nil, false
	}
	return o.IconKey, true
}

// HasIconKey returns a boolean if a field has been set.
func (o *UpdatePlaceClassDataAttributes) HasIconKey() bool {
	if o != nil && !IsNil(o.IconKey) {
		return true
	}

	return false
}

// SetIconKey gets a reference to the given string and assigns it to the IconKey field.
func (o *UpdatePlaceClassDataAttributes) SetIconKey(v string) {
	o.IconKey = &v
}

func (o UpdatePlaceClassDataAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdatePlaceClassDataAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ParentId) {
		toSerialize["parent_id"] = o.ParentId
	}
	toSerialize["name"] = o.Name
	toSerialize["description"] = o.Description
	if !IsNil(o.IconKey) {
		toSerialize["icon_key"] = o.IconKey
	}
	return toSerialize, nil
}

func (o *UpdatePlaceClassDataAttributes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"description",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdatePlaceClassDataAttributes := _UpdatePlaceClassDataAttributes{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdatePlaceClassDataAttributes)

	if err != nil {
		return err
	}

	*o = UpdatePlaceClassDataAttributes(varUpdatePlaceClassDataAttributes)

	return err
}

type NullableUpdatePlaceClassDataAttributes struct {
	value *UpdatePlaceClassDataAttributes
	isSet bool
}

func (v NullableUpdatePlaceClassDataAttributes) Get() *UpdatePlaceClassDataAttributes {
	return v.value
}

func (v *NullableUpdatePlaceClassDataAttributes) Set(val *UpdatePlaceClassDataAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdatePlaceClassDataAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdatePlaceClassDataAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdatePlaceClassDataAttributes(val *UpdatePlaceClassDataAttributes) *NullableUpdatePlaceClassDataAttributes {
	return &NullableUpdatePlaceClassDataAttributes{value: val, isSet: true}
}

func (v NullableUpdatePlaceClassDataAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdatePlaceClassDataAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


