/*
Place Service API

API for managing places and their classes.

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
)

// checks if the PlaceClassDataRelationships type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PlaceClassDataRelationships{}

// PlaceClassDataRelationships struct for PlaceClassDataRelationships
type PlaceClassDataRelationships struct {
	Parent *PlaceClassDataRelationshipsParent `json:"parent,omitempty"`
}

// NewPlaceClassDataRelationships instantiates a new PlaceClassDataRelationships object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPlaceClassDataRelationships() *PlaceClassDataRelationships {
	this := PlaceClassDataRelationships{}
	return &this
}

// NewPlaceClassDataRelationshipsWithDefaults instantiates a new PlaceClassDataRelationships object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPlaceClassDataRelationshipsWithDefaults() *PlaceClassDataRelationships {
	this := PlaceClassDataRelationships{}
	return &this
}

// GetParent returns the Parent field value if set, zero value otherwise.
func (o *PlaceClassDataRelationships) GetParent() PlaceClassDataRelationshipsParent {
	if o == nil || IsNil(o.Parent) {
		var ret PlaceClassDataRelationshipsParent
		return ret
	}
	return *o.Parent
}

// GetParentOk returns a tuple with the Parent field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlaceClassDataRelationships) GetParentOk() (*PlaceClassDataRelationshipsParent, bool) {
	if o == nil || IsNil(o.Parent) {
		return nil, false
	}
	return o.Parent, true
}

// HasParent returns a boolean if a field has been set.
func (o *PlaceClassDataRelationships) HasParent() bool {
	if o != nil && !IsNil(o.Parent) {
		return true
	}

	return false
}

// SetParent gets a reference to the given PlaceClassDataRelationshipsParent and assigns it to the Parent field.
func (o *PlaceClassDataRelationships) SetParent(v PlaceClassDataRelationshipsParent) {
	o.Parent = &v
}

func (o PlaceClassDataRelationships) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PlaceClassDataRelationships) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Parent) {
		toSerialize["parent"] = o.Parent
	}
	return toSerialize, nil
}

type NullablePlaceClassDataRelationships struct {
	value *PlaceClassDataRelationships
	isSet bool
}

func (v NullablePlaceClassDataRelationships) Get() *PlaceClassDataRelationships {
	return v.value
}

func (v *NullablePlaceClassDataRelationships) Set(val *PlaceClassDataRelationships) {
	v.value = val
	v.isSet = true
}

func (v NullablePlaceClassDataRelationships) IsSet() bool {
	return v.isSet
}

func (v *NullablePlaceClassDataRelationships) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePlaceClassDataRelationships(val *PlaceClassDataRelationships) *NullablePlaceClassDataRelationships {
	return &NullablePlaceClassDataRelationships{value: val, isSet: true}
}

func (v NullablePlaceClassDataRelationships) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePlaceClassDataRelationships) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


