/*
Place Service API

API for managing places and their classes.

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DeleteUploadPlaceBannerDataAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeleteUploadPlaceBannerDataAttributes{}

// DeleteUploadPlaceBannerDataAttributes struct for DeleteUploadPlaceBannerDataAttributes
type DeleteUploadPlaceBannerDataAttributes struct {
	// icon media key
	BannerKey string `json:"banner_key"`
}

type _DeleteUploadPlaceBannerDataAttributes DeleteUploadPlaceBannerDataAttributes

// NewDeleteUploadPlaceBannerDataAttributes instantiates a new DeleteUploadPlaceBannerDataAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeleteUploadPlaceBannerDataAttributes(bannerKey string) *DeleteUploadPlaceBannerDataAttributes {
	this := DeleteUploadPlaceBannerDataAttributes{}
	this.BannerKey = bannerKey
	return &this
}

// NewDeleteUploadPlaceBannerDataAttributesWithDefaults instantiates a new DeleteUploadPlaceBannerDataAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeleteUploadPlaceBannerDataAttributesWithDefaults() *DeleteUploadPlaceBannerDataAttributes {
	this := DeleteUploadPlaceBannerDataAttributes{}
	return &this
}

// GetBannerKey returns the BannerKey field value
func (o *DeleteUploadPlaceBannerDataAttributes) GetBannerKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BannerKey
}

// GetBannerKeyOk returns a tuple with the BannerKey field value
// and a boolean to check if the value has been set.
func (o *DeleteUploadPlaceBannerDataAttributes) GetBannerKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BannerKey, true
}

// SetBannerKey sets field value
func (o *DeleteUploadPlaceBannerDataAttributes) SetBannerKey(v string) {
	o.BannerKey = v
}

func (o DeleteUploadPlaceBannerDataAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeleteUploadPlaceBannerDataAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["banner_key"] = o.BannerKey
	return toSerialize, nil
}

func (o *DeleteUploadPlaceBannerDataAttributes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"banner_key",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDeleteUploadPlaceBannerDataAttributes := _DeleteUploadPlaceBannerDataAttributes{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDeleteUploadPlaceBannerDataAttributes)

	if err != nil {
		return err
	}

	*o = DeleteUploadPlaceBannerDataAttributes(varDeleteUploadPlaceBannerDataAttributes)

	return err
}

type NullableDeleteUploadPlaceBannerDataAttributes struct {
	value *DeleteUploadPlaceBannerDataAttributes
	isSet bool
}

func (v NullableDeleteUploadPlaceBannerDataAttributes) Get() *DeleteUploadPlaceBannerDataAttributes {
	return v.value
}

func (v *NullableDeleteUploadPlaceBannerDataAttributes) Set(val *DeleteUploadPlaceBannerDataAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableDeleteUploadPlaceBannerDataAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableDeleteUploadPlaceBannerDataAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeleteUploadPlaceBannerDataAttributes(val *DeleteUploadPlaceBannerDataAttributes) *NullableDeleteUploadPlaceBannerDataAttributes {
	return &NullableDeleteUploadPlaceBannerDataAttributes{value: val, isSet: true}
}

func (v NullableDeleteUploadPlaceBannerDataAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeleteUploadPlaceBannerDataAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


