/*
Place Service API

API for managing places and their classes.

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreatePlace type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreatePlace{}

// CreatePlace struct for CreatePlace
type CreatePlace struct {
	Data CreatePlaceData `json:"data"`
}

type _CreatePlace CreatePlace

// NewCreatePlace instantiates a new CreatePlace object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreatePlace(data CreatePlaceData) *CreatePlace {
	this := CreatePlace{}
	this.Data = data
	return &this
}

// NewCreatePlaceWithDefaults instantiates a new CreatePlace object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreatePlaceWithDefaults() *CreatePlace {
	this := CreatePlace{}
	return &this
}

// GetData returns the Data field value
func (o *CreatePlace) GetData() CreatePlaceData {
	if o == nil {
		var ret CreatePlaceData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *CreatePlace) GetDataOk() (*CreatePlaceData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *CreatePlace) SetData(v CreatePlaceData) {
	o.Data = v
}

func (o CreatePlace) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreatePlace) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *CreatePlace) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreatePlace := _CreatePlace{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreatePlace)

	if err != nil {
		return err
	}

	*o = CreatePlace(varCreatePlace)

	return err
}

type NullableCreatePlace struct {
	value *CreatePlace
	isSet bool
}

func (v NullableCreatePlace) Get() *CreatePlace {
	return v.value
}

func (v *NullableCreatePlace) Set(val *CreatePlace) {
	v.value = val
	v.isSet = true
}

func (v NullableCreatePlace) IsSet() bool {
	return v.isSet
}

func (v *NullableCreatePlace) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreatePlace(val *CreatePlace) *NullableCreatePlace {
	return &NullableCreatePlace{value: val, isSet: true}
}

func (v NullableCreatePlace) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreatePlace) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


