/*
Place Service API

API for managing places and their classes.

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UpdatePlaceStatus type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdatePlaceStatus{}

// UpdatePlaceStatus struct for UpdatePlaceStatus
type UpdatePlaceStatus struct {
	Data UpdatePlaceStatusData `json:"data"`
}

type _UpdatePlaceStatus UpdatePlaceStatus

// NewUpdatePlaceStatus instantiates a new UpdatePlaceStatus object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdatePlaceStatus(data UpdatePlaceStatusData) *UpdatePlaceStatus {
	this := UpdatePlaceStatus{}
	this.Data = data
	return &this
}

// NewUpdatePlaceStatusWithDefaults instantiates a new UpdatePlaceStatus object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdatePlaceStatusWithDefaults() *UpdatePlaceStatus {
	this := UpdatePlaceStatus{}
	return &this
}

// GetData returns the Data field value
func (o *UpdatePlaceStatus) GetData() UpdatePlaceStatusData {
	if o == nil {
		var ret UpdatePlaceStatusData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *UpdatePlaceStatus) GetDataOk() (*UpdatePlaceStatusData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *UpdatePlaceStatus) SetData(v UpdatePlaceStatusData) {
	o.Data = v
}

func (o UpdatePlaceStatus) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdatePlaceStatus) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *UpdatePlaceStatus) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdatePlaceStatus := _UpdatePlaceStatus{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdatePlaceStatus)

	if err != nil {
		return err
	}

	*o = UpdatePlaceStatus(varUpdatePlaceStatus)

	return err
}

type NullableUpdatePlaceStatus struct {
	value *UpdatePlaceStatus
	isSet bool
}

func (v NullableUpdatePlaceStatus) Get() *UpdatePlaceStatus {
	return v.value
}

func (v *NullableUpdatePlaceStatus) Set(val *UpdatePlaceStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdatePlaceStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdatePlaceStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdatePlaceStatus(val *UpdatePlaceStatus) *NullableUpdatePlaceStatus {
	return &NullableUpdatePlaceStatus{value: val, isSet: true}
}

func (v NullableUpdatePlaceStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdatePlaceStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


