/*
Place Service API

API for managing places and their classes.

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ConfirmUpdatePlaceClass type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConfirmUpdatePlaceClass{}

// ConfirmUpdatePlaceClass struct for ConfirmUpdatePlaceClass
type ConfirmUpdatePlaceClass struct {
	Data ConfirmUpdatePlaceClassData `json:"data"`
}

type _ConfirmUpdatePlaceClass ConfirmUpdatePlaceClass

// NewConfirmUpdatePlaceClass instantiates a new ConfirmUpdatePlaceClass object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConfirmUpdatePlaceClass(data ConfirmUpdatePlaceClassData) *ConfirmUpdatePlaceClass {
	this := ConfirmUpdatePlaceClass{}
	this.Data = data
	return &this
}

// NewConfirmUpdatePlaceClassWithDefaults instantiates a new ConfirmUpdatePlaceClass object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConfirmUpdatePlaceClassWithDefaults() *ConfirmUpdatePlaceClass {
	this := ConfirmUpdatePlaceClass{}
	return &this
}

// GetData returns the Data field value
func (o *ConfirmUpdatePlaceClass) GetData() ConfirmUpdatePlaceClassData {
	if o == nil {
		var ret ConfirmUpdatePlaceClassData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *ConfirmUpdatePlaceClass) GetDataOk() (*ConfirmUpdatePlaceClassData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *ConfirmUpdatePlaceClass) SetData(v ConfirmUpdatePlaceClassData) {
	o.Data = v
}

func (o ConfirmUpdatePlaceClass) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConfirmUpdatePlaceClass) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *ConfirmUpdatePlaceClass) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varConfirmUpdatePlaceClass := _ConfirmUpdatePlaceClass{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varConfirmUpdatePlaceClass)

	if err != nil {
		return err
	}

	*o = ConfirmUpdatePlaceClass(varConfirmUpdatePlaceClass)

	return err
}

type NullableConfirmUpdatePlaceClass struct {
	value *ConfirmUpdatePlaceClass
	isSet bool
}

func (v NullableConfirmUpdatePlaceClass) Get() *ConfirmUpdatePlaceClass {
	return v.value
}

func (v *NullableConfirmUpdatePlaceClass) Set(val *ConfirmUpdatePlaceClass) {
	v.value = val
	v.isSet = true
}

func (v NullableConfirmUpdatePlaceClass) IsSet() bool {
	return v.isSet
}

func (v *NullableConfirmUpdatePlaceClass) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConfirmUpdatePlaceClass(val *ConfirmUpdatePlaceClass) *NullableConfirmUpdatePlaceClass {
	return &NullableConfirmUpdatePlaceClass{value: val, isSet: true}
}

func (v NullableConfirmUpdatePlaceClass) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConfirmUpdatePlaceClass) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


