/*
Place Service API

API for managing places and their classes.

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"github.com/google/uuid"
	"bytes"
	"fmt"
)

// checks if the UpdateClassForPlaceDataAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateClassForPlaceDataAttributes{}

// UpdateClassForPlaceDataAttributes struct for UpdateClassForPlaceDataAttributes
type UpdateClassForPlaceDataAttributes struct {
	// The ID of the class this place belongs to
	ClassId uuid.UUID `json:"class_id"`
}

type _UpdateClassForPlaceDataAttributes UpdateClassForPlaceDataAttributes

// NewUpdateClassForPlaceDataAttributes instantiates a new UpdateClassForPlaceDataAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateClassForPlaceDataAttributes(classId uuid.UUID) *UpdateClassForPlaceDataAttributes {
	this := UpdateClassForPlaceDataAttributes{}
	this.ClassId = classId
	return &this
}

// NewUpdateClassForPlaceDataAttributesWithDefaults instantiates a new UpdateClassForPlaceDataAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateClassForPlaceDataAttributesWithDefaults() *UpdateClassForPlaceDataAttributes {
	this := UpdateClassForPlaceDataAttributes{}
	return &this
}

// GetClassId returns the ClassId field value
func (o *UpdateClassForPlaceDataAttributes) GetClassId() uuid.UUID {
	if o == nil {
		var ret uuid.UUID
		return ret
	}

	return o.ClassId
}

// GetClassIdOk returns a tuple with the ClassId field value
// and a boolean to check if the value has been set.
func (o *UpdateClassForPlaceDataAttributes) GetClassIdOk() (*uuid.UUID, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ClassId, true
}

// SetClassId sets field value
func (o *UpdateClassForPlaceDataAttributes) SetClassId(v uuid.UUID) {
	o.ClassId = v
}

func (o UpdateClassForPlaceDataAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateClassForPlaceDataAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["class_id"] = o.ClassId
	return toSerialize, nil
}

func (o *UpdateClassForPlaceDataAttributes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"class_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateClassForPlaceDataAttributes := _UpdateClassForPlaceDataAttributes{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdateClassForPlaceDataAttributes)

	if err != nil {
		return err
	}

	*o = UpdateClassForPlaceDataAttributes(varUpdateClassForPlaceDataAttributes)

	return err
}

type NullableUpdateClassForPlaceDataAttributes struct {
	value *UpdateClassForPlaceDataAttributes
	isSet bool
}

func (v NullableUpdateClassForPlaceDataAttributes) Get() *UpdateClassForPlaceDataAttributes {
	return v.value
}

func (v *NullableUpdateClassForPlaceDataAttributes) Set(val *UpdateClassForPlaceDataAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateClassForPlaceDataAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateClassForPlaceDataAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateClassForPlaceDataAttributes(val *UpdateClassForPlaceDataAttributes) *NullableUpdateClassForPlaceDataAttributes {
	return &NullableUpdateClassForPlaceDataAttributes{value: val, isSet: true}
}

func (v NullableUpdateClassForPlaceDataAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateClassForPlaceDataAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


