/*
Place Service API

API for managing places and their classes.

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
)

// checks if the ClassDataRelationships type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ClassDataRelationships{}

// ClassDataRelationships struct for ClassDataRelationships
type ClassDataRelationships struct {
	Parent *ClassDataRelationshipsParent `json:"parent,omitempty"`
}

// NewClassDataRelationships instantiates a new ClassDataRelationships object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewClassDataRelationships() *ClassDataRelationships {
	this := ClassDataRelationships{}
	return &this
}

// NewClassDataRelationshipsWithDefaults instantiates a new ClassDataRelationships object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewClassDataRelationshipsWithDefaults() *ClassDataRelationships {
	this := ClassDataRelationships{}
	return &this
}

// GetParent returns the Parent field value if set, zero value otherwise.
func (o *ClassDataRelationships) GetParent() ClassDataRelationshipsParent {
	if o == nil || IsNil(o.Parent) {
		var ret ClassDataRelationshipsParent
		return ret
	}
	return *o.Parent
}

// GetParentOk returns a tuple with the Parent field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClassDataRelationships) GetParentOk() (*ClassDataRelationshipsParent, bool) {
	if o == nil || IsNil(o.Parent) {
		return nil, false
	}
	return o.Parent, true
}

// HasParent returns a boolean if a field has been set.
func (o *ClassDataRelationships) HasParent() bool {
	if o != nil && !IsNil(o.Parent) {
		return true
	}

	return false
}

// SetParent gets a reference to the given ClassDataRelationshipsParent and assigns it to the Parent field.
func (o *ClassDataRelationships) SetParent(v ClassDataRelationshipsParent) {
	o.Parent = &v
}

func (o ClassDataRelationships) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ClassDataRelationships) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Parent) {
		toSerialize["parent"] = o.Parent
	}
	return toSerialize, nil
}

type NullableClassDataRelationships struct {
	value *ClassDataRelationships
	isSet bool
}

func (v NullableClassDataRelationships) Get() *ClassDataRelationships {
	return v.value
}

func (v *NullableClassDataRelationships) Set(val *ClassDataRelationships) {
	v.value = val
	v.isSet = true
}

func (v NullableClassDataRelationships) IsSet() bool {
	return v.isSet
}

func (v *NullableClassDataRelationships) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableClassDataRelationships(val *ClassDataRelationships) *NullableClassDataRelationships {
	return &NullableClassDataRelationships{value: val, isSet: true}
}

func (v NullableClassDataRelationships) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableClassDataRelationships) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


