/*
Place Service API

API for managing places and their classes.

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"github.com/google/uuid"
	"bytes"
	"fmt"
)

// checks if the CreatePlaceDataAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreatePlaceDataAttributes{}

// CreatePlaceDataAttributes struct for CreatePlaceDataAttributes
type CreatePlaceDataAttributes struct {
	// The ID of the class this place belongs to
	ClassId uuid.UUID `json:"class_id"`
	// The ID of the organization this place belongs to
	OrganizationId *uuid.UUID `json:"organization_id,omitempty"`
	Point CreatePlaceDataAttributesPoint `json:"point"`
	// The physical address of the place
	Address string `json:"address"`
	// The name of the place
	Name string `json:"name"`
	// A brief description of the place
	Description *string `json:"description,omitempty"`
	// A URL to an icon representing the place
	Icon *string `json:"icon,omitempty"`
	// A URL to a banner image for the place
	Banner *string `json:"banner,omitempty"`
	// The website URL of the place
	Website *string `json:"website,omitempty"`
	// The contact phone number of the place
	Phone *string `json:"phone,omitempty"`
}

type _CreatePlaceDataAttributes CreatePlaceDataAttributes

// NewCreatePlaceDataAttributes instantiates a new CreatePlaceDataAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreatePlaceDataAttributes(classId uuid.UUID, point CreatePlaceDataAttributesPoint, address string, name string) *CreatePlaceDataAttributes {
	this := CreatePlaceDataAttributes{}
	this.ClassId = classId
	this.Point = point
	this.Address = address
	this.Name = name
	return &this
}

// NewCreatePlaceDataAttributesWithDefaults instantiates a new CreatePlaceDataAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreatePlaceDataAttributesWithDefaults() *CreatePlaceDataAttributes {
	this := CreatePlaceDataAttributes{}
	return &this
}

// GetClassId returns the ClassId field value
func (o *CreatePlaceDataAttributes) GetClassId() uuid.UUID {
	if o == nil {
		var ret uuid.UUID
		return ret
	}

	return o.ClassId
}

// GetClassIdOk returns a tuple with the ClassId field value
// and a boolean to check if the value has been set.
func (o *CreatePlaceDataAttributes) GetClassIdOk() (*uuid.UUID, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ClassId, true
}

// SetClassId sets field value
func (o *CreatePlaceDataAttributes) SetClassId(v uuid.UUID) {
	o.ClassId = v
}

// GetOrganizationId returns the OrganizationId field value if set, zero value otherwise.
func (o *CreatePlaceDataAttributes) GetOrganizationId() uuid.UUID {
	if o == nil || IsNil(o.OrganizationId) {
		var ret uuid.UUID
		return ret
	}
	return *o.OrganizationId
}

// GetOrganizationIdOk returns a tuple with the OrganizationId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreatePlaceDataAttributes) GetOrganizationIdOk() (*uuid.UUID, bool) {
	if o == nil || IsNil(o.OrganizationId) {
		return nil, false
	}
	return o.OrganizationId, true
}

// HasOrganizationId returns a boolean if a field has been set.
func (o *CreatePlaceDataAttributes) HasOrganizationId() bool {
	if o != nil && !IsNil(o.OrganizationId) {
		return true
	}

	return false
}

// SetOrganizationId gets a reference to the given uuid.UUID and assigns it to the OrganizationId field.
func (o *CreatePlaceDataAttributes) SetOrganizationId(v uuid.UUID) {
	o.OrganizationId = &v
}

// GetPoint returns the Point field value
func (o *CreatePlaceDataAttributes) GetPoint() CreatePlaceDataAttributesPoint {
	if o == nil {
		var ret CreatePlaceDataAttributesPoint
		return ret
	}

	return o.Point
}

// GetPointOk returns a tuple with the Point field value
// and a boolean to check if the value has been set.
func (o *CreatePlaceDataAttributes) GetPointOk() (*CreatePlaceDataAttributesPoint, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Point, true
}

// SetPoint sets field value
func (o *CreatePlaceDataAttributes) SetPoint(v CreatePlaceDataAttributesPoint) {
	o.Point = v
}

// GetAddress returns the Address field value
func (o *CreatePlaceDataAttributes) GetAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Address
}

// GetAddressOk returns a tuple with the Address field value
// and a boolean to check if the value has been set.
func (o *CreatePlaceDataAttributes) GetAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Address, true
}

// SetAddress sets field value
func (o *CreatePlaceDataAttributes) SetAddress(v string) {
	o.Address = v
}

// GetName returns the Name field value
func (o *CreatePlaceDataAttributes) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreatePlaceDataAttributes) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreatePlaceDataAttributes) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *CreatePlaceDataAttributes) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreatePlaceDataAttributes) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *CreatePlaceDataAttributes) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *CreatePlaceDataAttributes) SetDescription(v string) {
	o.Description = &v
}

// GetIcon returns the Icon field value if set, zero value otherwise.
func (o *CreatePlaceDataAttributes) GetIcon() string {
	if o == nil || IsNil(o.Icon) {
		var ret string
		return ret
	}
	return *o.Icon
}

// GetIconOk returns a tuple with the Icon field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreatePlaceDataAttributes) GetIconOk() (*string, bool) {
	if o == nil || IsNil(o.Icon) {
		return nil, false
	}
	return o.Icon, true
}

// HasIcon returns a boolean if a field has been set.
func (o *CreatePlaceDataAttributes) HasIcon() bool {
	if o != nil && !IsNil(o.Icon) {
		return true
	}

	return false
}

// SetIcon gets a reference to the given string and assigns it to the Icon field.
func (o *CreatePlaceDataAttributes) SetIcon(v string) {
	o.Icon = &v
}

// GetBanner returns the Banner field value if set, zero value otherwise.
func (o *CreatePlaceDataAttributes) GetBanner() string {
	if o == nil || IsNil(o.Banner) {
		var ret string
		return ret
	}
	return *o.Banner
}

// GetBannerOk returns a tuple with the Banner field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreatePlaceDataAttributes) GetBannerOk() (*string, bool) {
	if o == nil || IsNil(o.Banner) {
		return nil, false
	}
	return o.Banner, true
}

// HasBanner returns a boolean if a field has been set.
func (o *CreatePlaceDataAttributes) HasBanner() bool {
	if o != nil && !IsNil(o.Banner) {
		return true
	}

	return false
}

// SetBanner gets a reference to the given string and assigns it to the Banner field.
func (o *CreatePlaceDataAttributes) SetBanner(v string) {
	o.Banner = &v
}

// GetWebsite returns the Website field value if set, zero value otherwise.
func (o *CreatePlaceDataAttributes) GetWebsite() string {
	if o == nil || IsNil(o.Website) {
		var ret string
		return ret
	}
	return *o.Website
}

// GetWebsiteOk returns a tuple with the Website field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreatePlaceDataAttributes) GetWebsiteOk() (*string, bool) {
	if o == nil || IsNil(o.Website) {
		return nil, false
	}
	return o.Website, true
}

// HasWebsite returns a boolean if a field has been set.
func (o *CreatePlaceDataAttributes) HasWebsite() bool {
	if o != nil && !IsNil(o.Website) {
		return true
	}

	return false
}

// SetWebsite gets a reference to the given string and assigns it to the Website field.
func (o *CreatePlaceDataAttributes) SetWebsite(v string) {
	o.Website = &v
}

// GetPhone returns the Phone field value if set, zero value otherwise.
func (o *CreatePlaceDataAttributes) GetPhone() string {
	if o == nil || IsNil(o.Phone) {
		var ret string
		return ret
	}
	return *o.Phone
}

// GetPhoneOk returns a tuple with the Phone field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreatePlaceDataAttributes) GetPhoneOk() (*string, bool) {
	if o == nil || IsNil(o.Phone) {
		return nil, false
	}
	return o.Phone, true
}

// HasPhone returns a boolean if a field has been set.
func (o *CreatePlaceDataAttributes) HasPhone() bool {
	if o != nil && !IsNil(o.Phone) {
		return true
	}

	return false
}

// SetPhone gets a reference to the given string and assigns it to the Phone field.
func (o *CreatePlaceDataAttributes) SetPhone(v string) {
	o.Phone = &v
}

func (o CreatePlaceDataAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreatePlaceDataAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["class_id"] = o.ClassId
	if !IsNil(o.OrganizationId) {
		toSerialize["organization_id"] = o.OrganizationId
	}
	toSerialize["point"] = o.Point
	toSerialize["address"] = o.Address
	toSerialize["name"] = o.Name
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Icon) {
		toSerialize["icon"] = o.Icon
	}
	if !IsNil(o.Banner) {
		toSerialize["banner"] = o.Banner
	}
	if !IsNil(o.Website) {
		toSerialize["website"] = o.Website
	}
	if !IsNil(o.Phone) {
		toSerialize["phone"] = o.Phone
	}
	return toSerialize, nil
}

func (o *CreatePlaceDataAttributes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"class_id",
		"point",
		"address",
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreatePlaceDataAttributes := _CreatePlaceDataAttributes{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreatePlaceDataAttributes)

	if err != nil {
		return err
	}

	*o = CreatePlaceDataAttributes(varCreatePlaceDataAttributes)

	return err
}

type NullableCreatePlaceDataAttributes struct {
	value *CreatePlaceDataAttributes
	isSet bool
}

func (v NullableCreatePlaceDataAttributes) Get() *CreatePlaceDataAttributes {
	return v.value
}

func (v *NullableCreatePlaceDataAttributes) Set(val *CreatePlaceDataAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableCreatePlaceDataAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableCreatePlaceDataAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreatePlaceDataAttributes(val *CreatePlaceDataAttributes) *NullableCreatePlaceDataAttributes {
	return &NullableCreatePlaceDataAttributes{value: val, isSet: true}
}

func (v NullableCreatePlaceDataAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreatePlaceDataAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


