/*
Place Service API

API for managing places and their classes.

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"github.com/google/uuid"
	"bytes"
	"fmt"
)

// checks if the OpenUpdatePlaceMediaLinksData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OpenUpdatePlaceMediaLinksData{}

// OpenUpdatePlaceMediaLinksData struct for OpenUpdatePlaceMediaLinksData
type OpenUpdatePlaceMediaLinksData struct {
	// Upload session id
	Id uuid.UUID `json:"id"`
	Type string `json:"type"`
	Attributes OpenUpdatePlaceMediaLinksDataAttributes `json:"attributes"`
	Relationships OpenUpdatePlaceMediaLinksDataRelationships `json:"relationships"`
}

type _OpenUpdatePlaceMediaLinksData OpenUpdatePlaceMediaLinksData

// NewOpenUpdatePlaceMediaLinksData instantiates a new OpenUpdatePlaceMediaLinksData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOpenUpdatePlaceMediaLinksData(id uuid.UUID, type_ string, attributes OpenUpdatePlaceMediaLinksDataAttributes, relationships OpenUpdatePlaceMediaLinksDataRelationships) *OpenUpdatePlaceMediaLinksData {
	this := OpenUpdatePlaceMediaLinksData{}
	this.Id = id
	this.Type = type_
	this.Attributes = attributes
	this.Relationships = relationships
	return &this
}

// NewOpenUpdatePlaceMediaLinksDataWithDefaults instantiates a new OpenUpdatePlaceMediaLinksData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOpenUpdatePlaceMediaLinksDataWithDefaults() *OpenUpdatePlaceMediaLinksData {
	this := OpenUpdatePlaceMediaLinksData{}
	return &this
}

// GetId returns the Id field value
func (o *OpenUpdatePlaceMediaLinksData) GetId() uuid.UUID {
	if o == nil {
		var ret uuid.UUID
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *OpenUpdatePlaceMediaLinksData) GetIdOk() (*uuid.UUID, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *OpenUpdatePlaceMediaLinksData) SetId(v uuid.UUID) {
	o.Id = v
}

// GetType returns the Type field value
func (o *OpenUpdatePlaceMediaLinksData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *OpenUpdatePlaceMediaLinksData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *OpenUpdatePlaceMediaLinksData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *OpenUpdatePlaceMediaLinksData) GetAttributes() OpenUpdatePlaceMediaLinksDataAttributes {
	if o == nil {
		var ret OpenUpdatePlaceMediaLinksDataAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *OpenUpdatePlaceMediaLinksData) GetAttributesOk() (*OpenUpdatePlaceMediaLinksDataAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *OpenUpdatePlaceMediaLinksData) SetAttributes(v OpenUpdatePlaceMediaLinksDataAttributes) {
	o.Attributes = v
}

// GetRelationships returns the Relationships field value
func (o *OpenUpdatePlaceMediaLinksData) GetRelationships() OpenUpdatePlaceMediaLinksDataRelationships {
	if o == nil {
		var ret OpenUpdatePlaceMediaLinksDataRelationships
		return ret
	}

	return o.Relationships
}

// GetRelationshipsOk returns a tuple with the Relationships field value
// and a boolean to check if the value has been set.
func (o *OpenUpdatePlaceMediaLinksData) GetRelationshipsOk() (*OpenUpdatePlaceMediaLinksDataRelationships, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Relationships, true
}

// SetRelationships sets field value
func (o *OpenUpdatePlaceMediaLinksData) SetRelationships(v OpenUpdatePlaceMediaLinksDataRelationships) {
	o.Relationships = v
}

func (o OpenUpdatePlaceMediaLinksData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OpenUpdatePlaceMediaLinksData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	toSerialize["relationships"] = o.Relationships
	return toSerialize, nil
}

func (o *OpenUpdatePlaceMediaLinksData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"type",
		"attributes",
		"relationships",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOpenUpdatePlaceMediaLinksData := _OpenUpdatePlaceMediaLinksData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOpenUpdatePlaceMediaLinksData)

	if err != nil {
		return err
	}

	*o = OpenUpdatePlaceMediaLinksData(varOpenUpdatePlaceMediaLinksData)

	return err
}

type NullableOpenUpdatePlaceMediaLinksData struct {
	value *OpenUpdatePlaceMediaLinksData
	isSet bool
}

func (v NullableOpenUpdatePlaceMediaLinksData) Get() *OpenUpdatePlaceMediaLinksData {
	return v.value
}

func (v *NullableOpenUpdatePlaceMediaLinksData) Set(val *OpenUpdatePlaceMediaLinksData) {
	v.value = val
	v.isSet = true
}

func (v NullableOpenUpdatePlaceMediaLinksData) IsSet() bool {
	return v.isSet
}

func (v *NullableOpenUpdatePlaceMediaLinksData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOpenUpdatePlaceMediaLinksData(val *OpenUpdatePlaceMediaLinksData) *NullableOpenUpdatePlaceMediaLinksData {
	return &NullableOpenUpdatePlaceMediaLinksData{value: val, isSet: true}
}

func (v NullableOpenUpdatePlaceMediaLinksData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOpenUpdatePlaceMediaLinksData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


