/*
Place Service API

API for managing places and their classes.

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreatePlaceData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreatePlaceData{}

// CreatePlaceData struct for CreatePlaceData
type CreatePlaceData struct {
	Type string `json:"type"`
	Attributes CreatePlaceDataAttributes `json:"attributes"`
}

type _CreatePlaceData CreatePlaceData

// NewCreatePlaceData instantiates a new CreatePlaceData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreatePlaceData(type_ string, attributes CreatePlaceDataAttributes) *CreatePlaceData {
	this := CreatePlaceData{}
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewCreatePlaceDataWithDefaults instantiates a new CreatePlaceData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreatePlaceDataWithDefaults() *CreatePlaceData {
	this := CreatePlaceData{}
	return &this
}

// GetType returns the Type field value
func (o *CreatePlaceData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *CreatePlaceData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *CreatePlaceData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *CreatePlaceData) GetAttributes() CreatePlaceDataAttributes {
	if o == nil {
		var ret CreatePlaceDataAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *CreatePlaceData) GetAttributesOk() (*CreatePlaceDataAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *CreatePlaceData) SetAttributes(v CreatePlaceDataAttributes) {
	o.Attributes = v
}

func (o CreatePlaceData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreatePlaceData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	return toSerialize, nil
}

func (o *CreatePlaceData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreatePlaceData := _CreatePlaceData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreatePlaceData)

	if err != nil {
		return err
	}

	*o = CreatePlaceData(varCreatePlaceData)

	return err
}

type NullableCreatePlaceData struct {
	value *CreatePlaceData
	isSet bool
}

func (v NullableCreatePlaceData) Get() *CreatePlaceData {
	return v.value
}

func (v *NullableCreatePlaceData) Set(val *CreatePlaceData) {
	v.value = val
	v.isSet = true
}

func (v NullableCreatePlaceData) IsSet() bool {
	return v.isSet
}

func (v *NullableCreatePlaceData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreatePlaceData(val *CreatePlaceData) *NullableCreatePlaceData {
	return &NullableCreatePlaceData{value: val, isSet: true}
}

func (v NullableCreatePlaceData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreatePlaceData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


