/*
Place Service API

API for managing places and their classes.

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UpdatePlaceVerify type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdatePlaceVerify{}

// UpdatePlaceVerify struct for UpdatePlaceVerify
type UpdatePlaceVerify struct {
	Data UpdatePlaceVerifyData `json:"data"`
}

type _UpdatePlaceVerify UpdatePlaceVerify

// NewUpdatePlaceVerify instantiates a new UpdatePlaceVerify object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdatePlaceVerify(data UpdatePlaceVerifyData) *UpdatePlaceVerify {
	this := UpdatePlaceVerify{}
	this.Data = data
	return &this
}

// NewUpdatePlaceVerifyWithDefaults instantiates a new UpdatePlaceVerify object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdatePlaceVerifyWithDefaults() *UpdatePlaceVerify {
	this := UpdatePlaceVerify{}
	return &this
}

// GetData returns the Data field value
func (o *UpdatePlaceVerify) GetData() UpdatePlaceVerifyData {
	if o == nil {
		var ret UpdatePlaceVerifyData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *UpdatePlaceVerify) GetDataOk() (*UpdatePlaceVerifyData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *UpdatePlaceVerify) SetData(v UpdatePlaceVerifyData) {
	o.Data = v
}

func (o UpdatePlaceVerify) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdatePlaceVerify) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *UpdatePlaceVerify) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdatePlaceVerify := _UpdatePlaceVerify{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdatePlaceVerify)

	if err != nil {
		return err
	}

	*o = UpdatePlaceVerify(varUpdatePlaceVerify)

	return err
}

type NullableUpdatePlaceVerify struct {
	value *UpdatePlaceVerify
	isSet bool
}

func (v NullableUpdatePlaceVerify) Get() *UpdatePlaceVerify {
	return v.value
}

func (v *NullableUpdatePlaceVerify) Set(val *UpdatePlaceVerify) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdatePlaceVerify) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdatePlaceVerify) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdatePlaceVerify(val *UpdatePlaceVerify) *NullableUpdatePlaceVerify {
	return &NullableUpdatePlaceVerify{value: val, isSet: true}
}

func (v NullableUpdatePlaceVerify) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdatePlaceVerify) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


