/*
Place Service API

API for managing places and their classes.

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UpdatePlaceStatusDataAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdatePlaceStatusDataAttributes{}

// UpdatePlaceStatusDataAttributes struct for UpdatePlaceStatusDataAttributes
type UpdatePlaceStatusDataAttributes struct {
	// The new status of the place
	Status string `json:"status"`
}

type _UpdatePlaceStatusDataAttributes UpdatePlaceStatusDataAttributes

// NewUpdatePlaceStatusDataAttributes instantiates a new UpdatePlaceStatusDataAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdatePlaceStatusDataAttributes(status string) *UpdatePlaceStatusDataAttributes {
	this := UpdatePlaceStatusDataAttributes{}
	this.Status = status
	return &this
}

// NewUpdatePlaceStatusDataAttributesWithDefaults instantiates a new UpdatePlaceStatusDataAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdatePlaceStatusDataAttributesWithDefaults() *UpdatePlaceStatusDataAttributes {
	this := UpdatePlaceStatusDataAttributes{}
	return &this
}

// GetStatus returns the Status field value
func (o *UpdatePlaceStatusDataAttributes) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *UpdatePlaceStatusDataAttributes) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *UpdatePlaceStatusDataAttributes) SetStatus(v string) {
	o.Status = v
}

func (o UpdatePlaceStatusDataAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdatePlaceStatusDataAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["status"] = o.Status
	return toSerialize, nil
}

func (o *UpdatePlaceStatusDataAttributes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdatePlaceStatusDataAttributes := _UpdatePlaceStatusDataAttributes{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdatePlaceStatusDataAttributes)

	if err != nil {
		return err
	}

	*o = UpdatePlaceStatusDataAttributes(varUpdatePlaceStatusDataAttributes)

	return err
}

type NullableUpdatePlaceStatusDataAttributes struct {
	value *UpdatePlaceStatusDataAttributes
	isSet bool
}

func (v NullableUpdatePlaceStatusDataAttributes) Get() *UpdatePlaceStatusDataAttributes {
	return v.value
}

func (v *NullableUpdatePlaceStatusDataAttributes) Set(val *UpdatePlaceStatusDataAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdatePlaceStatusDataAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdatePlaceStatusDataAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdatePlaceStatusDataAttributes(val *UpdatePlaceStatusDataAttributes) *NullableUpdatePlaceStatusDataAttributes {
	return &NullableUpdatePlaceStatusDataAttributes{value: val, isSet: true}
}

func (v NullableUpdatePlaceStatusDataAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdatePlaceStatusDataAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


