/*
Place Service API

API for managing places and their classes.

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the VerifyPlace type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VerifyPlace{}

// VerifyPlace struct for VerifyPlace
type VerifyPlace struct {
	Data VerifyPlaceData `json:"data"`
}

type _VerifyPlace VerifyPlace

// NewVerifyPlace instantiates a new VerifyPlace object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVerifyPlace(data VerifyPlaceData) *VerifyPlace {
	this := VerifyPlace{}
	this.Data = data
	return &this
}

// NewVerifyPlaceWithDefaults instantiates a new VerifyPlace object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVerifyPlaceWithDefaults() *VerifyPlace {
	this := VerifyPlace{}
	return &this
}

// GetData returns the Data field value
func (o *VerifyPlace) GetData() VerifyPlaceData {
	if o == nil {
		var ret VerifyPlaceData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *VerifyPlace) GetDataOk() (*VerifyPlaceData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *VerifyPlace) SetData(v VerifyPlaceData) {
	o.Data = v
}

func (o VerifyPlace) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VerifyPlace) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *VerifyPlace) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varVerifyPlace := _VerifyPlace{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varVerifyPlace)

	if err != nil {
		return err
	}

	*o = VerifyPlace(varVerifyPlace)

	return err
}

type NullableVerifyPlace struct {
	value *VerifyPlace
	isSet bool
}

func (v NullableVerifyPlace) Get() *VerifyPlace {
	return v.value
}

func (v *NullableVerifyPlace) Set(val *VerifyPlace) {
	v.value = val
	v.isSet = true
}

func (v NullableVerifyPlace) IsSet() bool {
	return v.isSet
}

func (v *NullableVerifyPlace) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVerifyPlace(val *VerifyPlace) *NullableVerifyPlace {
	return &NullableVerifyPlace{value: val, isSet: true}
}

func (v NullableVerifyPlace) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVerifyPlace) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


