/*
Place Service API

API for managing places and their classes.

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"github.com/google/uuid"
	"bytes"
	"fmt"
)

// checks if the ReplacePlaceClassData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ReplacePlaceClassData{}

// ReplacePlaceClassData struct for ReplacePlaceClassData
type ReplacePlaceClassData struct {
	// The unique identifier for the replace place class operation
	Id uuid.UUID `json:"id"`
	Type string `json:"type"`
	Attributes ReplacePlaceClassDataAttributes `json:"attributes"`
}

type _ReplacePlaceClassData ReplacePlaceClassData

// NewReplacePlaceClassData instantiates a new ReplacePlaceClassData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewReplacePlaceClassData(id uuid.UUID, type_ string, attributes ReplacePlaceClassDataAttributes) *ReplacePlaceClassData {
	this := ReplacePlaceClassData{}
	this.Id = id
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewReplacePlaceClassDataWithDefaults instantiates a new ReplacePlaceClassData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewReplacePlaceClassDataWithDefaults() *ReplacePlaceClassData {
	this := ReplacePlaceClassData{}
	return &this
}

// GetId returns the Id field value
func (o *ReplacePlaceClassData) GetId() uuid.UUID {
	if o == nil {
		var ret uuid.UUID
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ReplacePlaceClassData) GetIdOk() (*uuid.UUID, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ReplacePlaceClassData) SetId(v uuid.UUID) {
	o.Id = v
}

// GetType returns the Type field value
func (o *ReplacePlaceClassData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *ReplacePlaceClassData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *ReplacePlaceClassData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *ReplacePlaceClassData) GetAttributes() ReplacePlaceClassDataAttributes {
	if o == nil {
		var ret ReplacePlaceClassDataAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *ReplacePlaceClassData) GetAttributesOk() (*ReplacePlaceClassDataAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *ReplacePlaceClassData) SetAttributes(v ReplacePlaceClassDataAttributes) {
	o.Attributes = v
}

func (o ReplacePlaceClassData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ReplacePlaceClassData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	return toSerialize, nil
}

func (o *ReplacePlaceClassData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varReplacePlaceClassData := _ReplacePlaceClassData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varReplacePlaceClassData)

	if err != nil {
		return err
	}

	*o = ReplacePlaceClassData(varReplacePlaceClassData)

	return err
}

type NullableReplacePlaceClassData struct {
	value *ReplacePlaceClassData
	isSet bool
}

func (v NullableReplacePlaceClassData) Get() *ReplacePlaceClassData {
	return v.value
}

func (v *NullableReplacePlaceClassData) Set(val *ReplacePlaceClassData) {
	v.value = val
	v.isSet = true
}

func (v NullableReplacePlaceClassData) IsSet() bool {
	return v.isSet
}

func (v *NullableReplacePlaceClassData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableReplacePlaceClassData(val *ReplacePlaceClassData) *NullableReplacePlaceClassData {
	return &NullableReplacePlaceClassData{value: val, isSet: true}
}

func (v NullableReplacePlaceClassData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableReplacePlaceClassData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


