/*
Place Service API

API for managing places and their classes.

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"github.com/google/uuid"
	"bytes"
	"fmt"
)

// checks if the ClassData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ClassData{}

// ClassData struct for ClassData
type ClassData struct {
	// place ID
	Id uuid.UUID `json:"id"`
	Type string `json:"type"`
	Attributes ClassDataAttributes `json:"attributes"`
	Relationships *ClassDataRelationships `json:"relationships,omitempty"`
}

type _ClassData ClassData

// NewClassData instantiates a new ClassData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewClassData(id uuid.UUID, type_ string, attributes ClassDataAttributes) *ClassData {
	this := ClassData{}
	this.Id = id
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewClassDataWithDefaults instantiates a new ClassData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewClassDataWithDefaults() *ClassData {
	this := ClassData{}
	return &this
}

// GetId returns the Id field value
func (o *ClassData) GetId() uuid.UUID {
	if o == nil {
		var ret uuid.UUID
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ClassData) GetIdOk() (*uuid.UUID, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ClassData) SetId(v uuid.UUID) {
	o.Id = v
}

// GetType returns the Type field value
func (o *ClassData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *ClassData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *ClassData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *ClassData) GetAttributes() ClassDataAttributes {
	if o == nil {
		var ret ClassDataAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *ClassData) GetAttributesOk() (*ClassDataAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *ClassData) SetAttributes(v ClassDataAttributes) {
	o.Attributes = v
}

// GetRelationships returns the Relationships field value if set, zero value otherwise.
func (o *ClassData) GetRelationships() ClassDataRelationships {
	if o == nil || IsNil(o.Relationships) {
		var ret ClassDataRelationships
		return ret
	}
	return *o.Relationships
}

// GetRelationshipsOk returns a tuple with the Relationships field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClassData) GetRelationshipsOk() (*ClassDataRelationships, bool) {
	if o == nil || IsNil(o.Relationships) {
		return nil, false
	}
	return o.Relationships, true
}

// HasRelationships returns a boolean if a field has been set.
func (o *ClassData) HasRelationships() bool {
	if o != nil && !IsNil(o.Relationships) {
		return true
	}

	return false
}

// SetRelationships gets a reference to the given ClassDataRelationships and assigns it to the Relationships field.
func (o *ClassData) SetRelationships(v ClassDataRelationships) {
	o.Relationships = &v
}

func (o ClassData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ClassData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	if !IsNil(o.Relationships) {
		toSerialize["relationships"] = o.Relationships
	}
	return toSerialize, nil
}

func (o *ClassData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varClassData := _ClassData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varClassData)

	if err != nil {
		return err
	}

	*o = ClassData(varClassData)

	return err
}

type NullableClassData struct {
	value *ClassData
	isSet bool
}

func (v NullableClassData) Get() *ClassData {
	return v.value
}

func (v *NullableClassData) Set(val *ClassData) {
	v.value = val
	v.isSet = true
}

func (v NullableClassData) IsSet() bool {
	return v.isSet
}

func (v *NullableClassData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableClassData(val *ClassData) *NullableClassData {
	return &NullableClassData{value: val, isSet: true}
}

func (v NullableClassData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableClassData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


