/*
Place Service API

API for managing places and their classes.

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the OpenUpdatePlaceMediaLinksDataRelationshipsPlace type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OpenUpdatePlaceMediaLinksDataRelationshipsPlace{}

// OpenUpdatePlaceMediaLinksDataRelationshipsPlace struct for OpenUpdatePlaceMediaLinksDataRelationshipsPlace
type OpenUpdatePlaceMediaLinksDataRelationshipsPlace struct {
	Data OpenUpdatePlaceMediaLinksDataRelationshipsPlaceData `json:"data"`
}

type _OpenUpdatePlaceMediaLinksDataRelationshipsPlace OpenUpdatePlaceMediaLinksDataRelationshipsPlace

// NewOpenUpdatePlaceMediaLinksDataRelationshipsPlace instantiates a new OpenUpdatePlaceMediaLinksDataRelationshipsPlace object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOpenUpdatePlaceMediaLinksDataRelationshipsPlace(data OpenUpdatePlaceMediaLinksDataRelationshipsPlaceData) *OpenUpdatePlaceMediaLinksDataRelationshipsPlace {
	this := OpenUpdatePlaceMediaLinksDataRelationshipsPlace{}
	this.Data = data
	return &this
}

// NewOpenUpdatePlaceMediaLinksDataRelationshipsPlaceWithDefaults instantiates a new OpenUpdatePlaceMediaLinksDataRelationshipsPlace object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOpenUpdatePlaceMediaLinksDataRelationshipsPlaceWithDefaults() *OpenUpdatePlaceMediaLinksDataRelationshipsPlace {
	this := OpenUpdatePlaceMediaLinksDataRelationshipsPlace{}
	return &this
}

// GetData returns the Data field value
func (o *OpenUpdatePlaceMediaLinksDataRelationshipsPlace) GetData() OpenUpdatePlaceMediaLinksDataRelationshipsPlaceData {
	if o == nil {
		var ret OpenUpdatePlaceMediaLinksDataRelationshipsPlaceData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *OpenUpdatePlaceMediaLinksDataRelationshipsPlace) GetDataOk() (*OpenUpdatePlaceMediaLinksDataRelationshipsPlaceData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *OpenUpdatePlaceMediaLinksDataRelationshipsPlace) SetData(v OpenUpdatePlaceMediaLinksDataRelationshipsPlaceData) {
	o.Data = v
}

func (o OpenUpdatePlaceMediaLinksDataRelationshipsPlace) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OpenUpdatePlaceMediaLinksDataRelationshipsPlace) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *OpenUpdatePlaceMediaLinksDataRelationshipsPlace) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOpenUpdatePlaceMediaLinksDataRelationshipsPlace := _OpenUpdatePlaceMediaLinksDataRelationshipsPlace{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOpenUpdatePlaceMediaLinksDataRelationshipsPlace)

	if err != nil {
		return err
	}

	*o = OpenUpdatePlaceMediaLinksDataRelationshipsPlace(varOpenUpdatePlaceMediaLinksDataRelationshipsPlace)

	return err
}

type NullableOpenUpdatePlaceMediaLinksDataRelationshipsPlace struct {
	value *OpenUpdatePlaceMediaLinksDataRelationshipsPlace
	isSet bool
}

func (v NullableOpenUpdatePlaceMediaLinksDataRelationshipsPlace) Get() *OpenUpdatePlaceMediaLinksDataRelationshipsPlace {
	return v.value
}

func (v *NullableOpenUpdatePlaceMediaLinksDataRelationshipsPlace) Set(val *OpenUpdatePlaceMediaLinksDataRelationshipsPlace) {
	v.value = val
	v.isSet = true
}

func (v NullableOpenUpdatePlaceMediaLinksDataRelationshipsPlace) IsSet() bool {
	return v.isSet
}

func (v *NullableOpenUpdatePlaceMediaLinksDataRelationshipsPlace) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOpenUpdatePlaceMediaLinksDataRelationshipsPlace(val *OpenUpdatePlaceMediaLinksDataRelationshipsPlace) *NullableOpenUpdatePlaceMediaLinksDataRelationshipsPlace {
	return &NullableOpenUpdatePlaceMediaLinksDataRelationshipsPlace{value: val, isSet: true}
}

func (v NullableOpenUpdatePlaceMediaLinksDataRelationshipsPlace) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOpenUpdatePlaceMediaLinksDataRelationshipsPlace) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


