/*
Place Service API

API for managing places and their classes.

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the OpenUpdatePlaceMediaLinks type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OpenUpdatePlaceMediaLinks{}

// OpenUpdatePlaceMediaLinks struct for OpenUpdatePlaceMediaLinks
type OpenUpdatePlaceMediaLinks struct {
	Data OpenUpdatePlaceMediaLinksData `json:"data"`
	Included []PlaceData `json:"included"`
}

type _OpenUpdatePlaceMediaLinks OpenUpdatePlaceMediaLinks

// NewOpenUpdatePlaceMediaLinks instantiates a new OpenUpdatePlaceMediaLinks object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOpenUpdatePlaceMediaLinks(data OpenUpdatePlaceMediaLinksData, included []PlaceData) *OpenUpdatePlaceMediaLinks {
	this := OpenUpdatePlaceMediaLinks{}
	this.Data = data
	this.Included = included
	return &this
}

// NewOpenUpdatePlaceMediaLinksWithDefaults instantiates a new OpenUpdatePlaceMediaLinks object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOpenUpdatePlaceMediaLinksWithDefaults() *OpenUpdatePlaceMediaLinks {
	this := OpenUpdatePlaceMediaLinks{}
	return &this
}

// GetData returns the Data field value
func (o *OpenUpdatePlaceMediaLinks) GetData() OpenUpdatePlaceMediaLinksData {
	if o == nil {
		var ret OpenUpdatePlaceMediaLinksData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *OpenUpdatePlaceMediaLinks) GetDataOk() (*OpenUpdatePlaceMediaLinksData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *OpenUpdatePlaceMediaLinks) SetData(v OpenUpdatePlaceMediaLinksData) {
	o.Data = v
}

// GetIncluded returns the Included field value
func (o *OpenUpdatePlaceMediaLinks) GetIncluded() []PlaceData {
	if o == nil {
		var ret []PlaceData
		return ret
	}

	return o.Included
}

// GetIncludedOk returns a tuple with the Included field value
// and a boolean to check if the value has been set.
func (o *OpenUpdatePlaceMediaLinks) GetIncludedOk() ([]PlaceData, bool) {
	if o == nil {
		return nil, false
	}
	return o.Included, true
}

// SetIncluded sets field value
func (o *OpenUpdatePlaceMediaLinks) SetIncluded(v []PlaceData) {
	o.Included = v
}

func (o OpenUpdatePlaceMediaLinks) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OpenUpdatePlaceMediaLinks) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	toSerialize["included"] = o.Included
	return toSerialize, nil
}

func (o *OpenUpdatePlaceMediaLinks) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
		"included",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOpenUpdatePlaceMediaLinks := _OpenUpdatePlaceMediaLinks{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOpenUpdatePlaceMediaLinks)

	if err != nil {
		return err
	}

	*o = OpenUpdatePlaceMediaLinks(varOpenUpdatePlaceMediaLinks)

	return err
}

type NullableOpenUpdatePlaceMediaLinks struct {
	value *OpenUpdatePlaceMediaLinks
	isSet bool
}

func (v NullableOpenUpdatePlaceMediaLinks) Get() *OpenUpdatePlaceMediaLinks {
	return v.value
}

func (v *NullableOpenUpdatePlaceMediaLinks) Set(val *OpenUpdatePlaceMediaLinks) {
	v.value = val
	v.isSet = true
}

func (v NullableOpenUpdatePlaceMediaLinks) IsSet() bool {
	return v.isSet
}

func (v *NullableOpenUpdatePlaceMediaLinks) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOpenUpdatePlaceMediaLinks(val *OpenUpdatePlaceMediaLinks) *NullableOpenUpdatePlaceMediaLinks {
	return &NullableOpenUpdatePlaceMediaLinks{value: val, isSet: true}
}

func (v NullableOpenUpdatePlaceMediaLinks) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOpenUpdatePlaceMediaLinks) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


