/*
Place Service API

API for managing places and their classes.

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the ClassDataAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ClassDataAttributes{}

// ClassDataAttributes struct for ClassDataAttributes
type ClassDataAttributes struct {
	// The unique code of the class
	Code string `json:"code"`
	// The name of the class
	Name string `json:"name"`
	// A brief description of the class
	Description string `json:"description"`
	// A URL to an icon representing the class
	Icon *string `json:"icon,omitempty"`
	// The date and time when the class was last updated
	UpdatedAt time.Time `json:"updated_at"`
	// The date and time when the class was created
	CreatedAt time.Time `json:"created_at"`
}

type _ClassDataAttributes ClassDataAttributes

// NewClassDataAttributes instantiates a new ClassDataAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewClassDataAttributes(code string, name string, description string, updatedAt time.Time, createdAt time.Time) *ClassDataAttributes {
	this := ClassDataAttributes{}
	this.Code = code
	this.Name = name
	this.Description = description
	this.UpdatedAt = updatedAt
	this.CreatedAt = createdAt
	return &this
}

// NewClassDataAttributesWithDefaults instantiates a new ClassDataAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewClassDataAttributesWithDefaults() *ClassDataAttributes {
	this := ClassDataAttributes{}
	return &this
}

// GetCode returns the Code field value
func (o *ClassDataAttributes) GetCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Code
}

// GetCodeOk returns a tuple with the Code field value
// and a boolean to check if the value has been set.
func (o *ClassDataAttributes) GetCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Code, true
}

// SetCode sets field value
func (o *ClassDataAttributes) SetCode(v string) {
	o.Code = v
}

// GetName returns the Name field value
func (o *ClassDataAttributes) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ClassDataAttributes) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ClassDataAttributes) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value
func (o *ClassDataAttributes) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *ClassDataAttributes) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *ClassDataAttributes) SetDescription(v string) {
	o.Description = v
}

// GetIcon returns the Icon field value if set, zero value otherwise.
func (o *ClassDataAttributes) GetIcon() string {
	if o == nil || IsNil(o.Icon) {
		var ret string
		return ret
	}
	return *o.Icon
}

// GetIconOk returns a tuple with the Icon field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClassDataAttributes) GetIconOk() (*string, bool) {
	if o == nil || IsNil(o.Icon) {
		return nil, false
	}
	return o.Icon, true
}

// HasIcon returns a boolean if a field has been set.
func (o *ClassDataAttributes) HasIcon() bool {
	if o != nil && !IsNil(o.Icon) {
		return true
	}

	return false
}

// SetIcon gets a reference to the given string and assigns it to the Icon field.
func (o *ClassDataAttributes) SetIcon(v string) {
	o.Icon = &v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *ClassDataAttributes) GetUpdatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *ClassDataAttributes) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *ClassDataAttributes) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *ClassDataAttributes) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *ClassDataAttributes) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *ClassDataAttributes) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

func (o ClassDataAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ClassDataAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["code"] = o.Code
	toSerialize["name"] = o.Name
	toSerialize["description"] = o.Description
	if !IsNil(o.Icon) {
		toSerialize["icon"] = o.Icon
	}
	toSerialize["updated_at"] = o.UpdatedAt
	toSerialize["created_at"] = o.CreatedAt
	return toSerialize, nil
}

func (o *ClassDataAttributes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"code",
		"name",
		"description",
		"updated_at",
		"created_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varClassDataAttributes := _ClassDataAttributes{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varClassDataAttributes)

	if err != nil {
		return err
	}

	*o = ClassDataAttributes(varClassDataAttributes)

	return err
}

type NullableClassDataAttributes struct {
	value *ClassDataAttributes
	isSet bool
}

func (v NullableClassDataAttributes) Get() *ClassDataAttributes {
	return v.value
}

func (v *NullableClassDataAttributes) Set(val *ClassDataAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableClassDataAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableClassDataAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableClassDataAttributes(val *ClassDataAttributes) *NullableClassDataAttributes {
	return &NullableClassDataAttributes{value: val, isSet: true}
}

func (v NullableClassDataAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableClassDataAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


