/*
Place Service API

API for managing places and their classes.

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ConfirmUpdatePlace type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConfirmUpdatePlace{}

// ConfirmUpdatePlace struct for ConfirmUpdatePlace
type ConfirmUpdatePlace struct {
	Data ConfirmUpdatePlaceData `json:"data"`
}

type _ConfirmUpdatePlace ConfirmUpdatePlace

// NewConfirmUpdatePlace instantiates a new ConfirmUpdatePlace object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConfirmUpdatePlace(data ConfirmUpdatePlaceData) *ConfirmUpdatePlace {
	this := ConfirmUpdatePlace{}
	this.Data = data
	return &this
}

// NewConfirmUpdatePlaceWithDefaults instantiates a new ConfirmUpdatePlace object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConfirmUpdatePlaceWithDefaults() *ConfirmUpdatePlace {
	this := ConfirmUpdatePlace{}
	return &this
}

// GetData returns the Data field value
func (o *ConfirmUpdatePlace) GetData() ConfirmUpdatePlaceData {
	if o == nil {
		var ret ConfirmUpdatePlaceData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *ConfirmUpdatePlace) GetDataOk() (*ConfirmUpdatePlaceData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *ConfirmUpdatePlace) SetData(v ConfirmUpdatePlaceData) {
	o.Data = v
}

func (o ConfirmUpdatePlace) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConfirmUpdatePlace) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *ConfirmUpdatePlace) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varConfirmUpdatePlace := _ConfirmUpdatePlace{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varConfirmUpdatePlace)

	if err != nil {
		return err
	}

	*o = ConfirmUpdatePlace(varConfirmUpdatePlace)

	return err
}

type NullableConfirmUpdatePlace struct {
	value *ConfirmUpdatePlace
	isSet bool
}

func (v NullableConfirmUpdatePlace) Get() *ConfirmUpdatePlace {
	return v.value
}

func (v *NullableConfirmUpdatePlace) Set(val *ConfirmUpdatePlace) {
	v.value = val
	v.isSet = true
}

func (v NullableConfirmUpdatePlace) IsSet() bool {
	return v.isSet
}

func (v *NullableConfirmUpdatePlace) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConfirmUpdatePlace(val *ConfirmUpdatePlace) *NullableConfirmUpdatePlace {
	return &NullableConfirmUpdatePlace{value: val, isSet: true}
}

func (v NullableConfirmUpdatePlace) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConfirmUpdatePlace) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


