/*
Place Service API

API for managing places and their classes.

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"github.com/google/uuid"
	"bytes"
	"fmt"
)

// checks if the OpenUpdatePlaceMediaLinksDataRelationshipsPlaceData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OpenUpdatePlaceMediaLinksDataRelationshipsPlaceData{}

// OpenUpdatePlaceMediaLinksDataRelationshipsPlaceData struct for OpenUpdatePlaceMediaLinksDataRelationshipsPlaceData
type OpenUpdatePlaceMediaLinksDataRelationshipsPlaceData struct {
	// place id
	Id uuid.UUID `json:"id"`
	Type string `json:"type"`
}

type _OpenUpdatePlaceMediaLinksDataRelationshipsPlaceData OpenUpdatePlaceMediaLinksDataRelationshipsPlaceData

// NewOpenUpdatePlaceMediaLinksDataRelationshipsPlaceData instantiates a new OpenUpdatePlaceMediaLinksDataRelationshipsPlaceData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOpenUpdatePlaceMediaLinksDataRelationshipsPlaceData(id uuid.UUID, type_ string) *OpenUpdatePlaceMediaLinksDataRelationshipsPlaceData {
	this := OpenUpdatePlaceMediaLinksDataRelationshipsPlaceData{}
	this.Id = id
	this.Type = type_
	return &this
}

// NewOpenUpdatePlaceMediaLinksDataRelationshipsPlaceDataWithDefaults instantiates a new OpenUpdatePlaceMediaLinksDataRelationshipsPlaceData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOpenUpdatePlaceMediaLinksDataRelationshipsPlaceDataWithDefaults() *OpenUpdatePlaceMediaLinksDataRelationshipsPlaceData {
	this := OpenUpdatePlaceMediaLinksDataRelationshipsPlaceData{}
	return &this
}

// GetId returns the Id field value
func (o *OpenUpdatePlaceMediaLinksDataRelationshipsPlaceData) GetId() uuid.UUID {
	if o == nil {
		var ret uuid.UUID
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *OpenUpdatePlaceMediaLinksDataRelationshipsPlaceData) GetIdOk() (*uuid.UUID, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *OpenUpdatePlaceMediaLinksDataRelationshipsPlaceData) SetId(v uuid.UUID) {
	o.Id = v
}

// GetType returns the Type field value
func (o *OpenUpdatePlaceMediaLinksDataRelationshipsPlaceData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *OpenUpdatePlaceMediaLinksDataRelationshipsPlaceData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *OpenUpdatePlaceMediaLinksDataRelationshipsPlaceData) SetType(v string) {
	o.Type = v
}

func (o OpenUpdatePlaceMediaLinksDataRelationshipsPlaceData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OpenUpdatePlaceMediaLinksDataRelationshipsPlaceData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["type"] = o.Type
	return toSerialize, nil
}

func (o *OpenUpdatePlaceMediaLinksDataRelationshipsPlaceData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOpenUpdatePlaceMediaLinksDataRelationshipsPlaceData := _OpenUpdatePlaceMediaLinksDataRelationshipsPlaceData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOpenUpdatePlaceMediaLinksDataRelationshipsPlaceData)

	if err != nil {
		return err
	}

	*o = OpenUpdatePlaceMediaLinksDataRelationshipsPlaceData(varOpenUpdatePlaceMediaLinksDataRelationshipsPlaceData)

	return err
}

type NullableOpenUpdatePlaceMediaLinksDataRelationshipsPlaceData struct {
	value *OpenUpdatePlaceMediaLinksDataRelationshipsPlaceData
	isSet bool
}

func (v NullableOpenUpdatePlaceMediaLinksDataRelationshipsPlaceData) Get() *OpenUpdatePlaceMediaLinksDataRelationshipsPlaceData {
	return v.value
}

func (v *NullableOpenUpdatePlaceMediaLinksDataRelationshipsPlaceData) Set(val *OpenUpdatePlaceMediaLinksDataRelationshipsPlaceData) {
	v.value = val
	v.isSet = true
}

func (v NullableOpenUpdatePlaceMediaLinksDataRelationshipsPlaceData) IsSet() bool {
	return v.isSet
}

func (v *NullableOpenUpdatePlaceMediaLinksDataRelationshipsPlaceData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOpenUpdatePlaceMediaLinksDataRelationshipsPlaceData(val *OpenUpdatePlaceMediaLinksDataRelationshipsPlaceData) *NullableOpenUpdatePlaceMediaLinksDataRelationshipsPlaceData {
	return &NullableOpenUpdatePlaceMediaLinksDataRelationshipsPlaceData{value: val, isSet: true}
}

func (v NullableOpenUpdatePlaceMediaLinksDataRelationshipsPlaceData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOpenUpdatePlaceMediaLinksDataRelationshipsPlaceData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


