/*
Place Service API

API for managing places and their classes.

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"github.com/google/uuid"
	"bytes"
	"fmt"
)

// checks if the UpdatePlaceStatusData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdatePlaceStatusData{}

// UpdatePlaceStatusData struct for UpdatePlaceStatusData
type UpdatePlaceStatusData struct {
	// The unique identifier of the place
	Id uuid.UUID `json:"id"`
	Type string `json:"type"`
	Attributes UpdatePlaceStatusDataAttributes `json:"attributes"`
}

type _UpdatePlaceStatusData UpdatePlaceStatusData

// NewUpdatePlaceStatusData instantiates a new UpdatePlaceStatusData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdatePlaceStatusData(id uuid.UUID, type_ string, attributes UpdatePlaceStatusDataAttributes) *UpdatePlaceStatusData {
	this := UpdatePlaceStatusData{}
	this.Id = id
	this.Type = type_
	this.Attributes = attributes
	return &this
}

// NewUpdatePlaceStatusDataWithDefaults instantiates a new UpdatePlaceStatusData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdatePlaceStatusDataWithDefaults() *UpdatePlaceStatusData {
	this := UpdatePlaceStatusData{}
	return &this
}

// GetId returns the Id field value
func (o *UpdatePlaceStatusData) GetId() uuid.UUID {
	if o == nil {
		var ret uuid.UUID
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *UpdatePlaceStatusData) GetIdOk() (*uuid.UUID, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *UpdatePlaceStatusData) SetId(v uuid.UUID) {
	o.Id = v
}

// GetType returns the Type field value
func (o *UpdatePlaceStatusData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *UpdatePlaceStatusData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *UpdatePlaceStatusData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *UpdatePlaceStatusData) GetAttributes() UpdatePlaceStatusDataAttributes {
	if o == nil {
		var ret UpdatePlaceStatusDataAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *UpdatePlaceStatusData) GetAttributesOk() (*UpdatePlaceStatusDataAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *UpdatePlaceStatusData) SetAttributes(v UpdatePlaceStatusDataAttributes) {
	o.Attributes = v
}

func (o UpdatePlaceStatusData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdatePlaceStatusData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	return toSerialize, nil
}

func (o *UpdatePlaceStatusData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"type",
		"attributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdatePlaceStatusData := _UpdatePlaceStatusData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdatePlaceStatusData)

	if err != nil {
		return err
	}

	*o = UpdatePlaceStatusData(varUpdatePlaceStatusData)

	return err
}

type NullableUpdatePlaceStatusData struct {
	value *UpdatePlaceStatusData
	isSet bool
}

func (v NullableUpdatePlaceStatusData) Get() *UpdatePlaceStatusData {
	return v.value
}

func (v *NullableUpdatePlaceStatusData) Set(val *UpdatePlaceStatusData) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdatePlaceStatusData) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdatePlaceStatusData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdatePlaceStatusData(val *UpdatePlaceStatusData) *NullableUpdatePlaceStatusData {
	return &NullableUpdatePlaceStatusData{value: val, isSet: true}
}

func (v NullableUpdatePlaceStatusData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdatePlaceStatusData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


