/*
Place Service API

API for managing places and their classes.

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"github.com/google/uuid"
)

// checks if the UpdatePlaceDataAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdatePlaceDataAttributes{}

// UpdatePlaceDataAttributes struct for UpdatePlaceDataAttributes
type UpdatePlaceDataAttributes struct {
	// The ID of the class this place belongs to
	ClassId *uuid.UUID `json:"class_id,omitempty"`
	// The status of the place (e.g., active, inactive)
	Status *string `json:"status,omitempty"`
	// The physical address of the place
	Address *string `json:"address,omitempty"`
	// The name of the place
	Name *string `json:"name,omitempty"`
	// A brief description of the place
	Description *string `json:"description,omitempty"`
	// A URL to an icon representing the place
	Icon *string `json:"icon,omitempty"`
	// A URL to a banner image for the place
	Banner *string `json:"banner,omitempty"`
	// The website URL of the place
	Website *string `json:"website,omitempty"`
	// The contact phone number of the place
	Phone *string `json:"phone,omitempty"`
}

// NewUpdatePlaceDataAttributes instantiates a new UpdatePlaceDataAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdatePlaceDataAttributes() *UpdatePlaceDataAttributes {
	this := UpdatePlaceDataAttributes{}
	return &this
}

// NewUpdatePlaceDataAttributesWithDefaults instantiates a new UpdatePlaceDataAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdatePlaceDataAttributesWithDefaults() *UpdatePlaceDataAttributes {
	this := UpdatePlaceDataAttributes{}
	return &this
}

// GetClassId returns the ClassId field value if set, zero value otherwise.
func (o *UpdatePlaceDataAttributes) GetClassId() uuid.UUID {
	if o == nil || IsNil(o.ClassId) {
		var ret uuid.UUID
		return ret
	}
	return *o.ClassId
}

// GetClassIdOk returns a tuple with the ClassId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdatePlaceDataAttributes) GetClassIdOk() (*uuid.UUID, bool) {
	if o == nil || IsNil(o.ClassId) {
		return nil, false
	}
	return o.ClassId, true
}

// HasClassId returns a boolean if a field has been set.
func (o *UpdatePlaceDataAttributes) HasClassId() bool {
	if o != nil && !IsNil(o.ClassId) {
		return true
	}

	return false
}

// SetClassId gets a reference to the given uuid.UUID and assigns it to the ClassId field.
func (o *UpdatePlaceDataAttributes) SetClassId(v uuid.UUID) {
	o.ClassId = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *UpdatePlaceDataAttributes) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdatePlaceDataAttributes) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *UpdatePlaceDataAttributes) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *UpdatePlaceDataAttributes) SetStatus(v string) {
	o.Status = &v
}

// GetAddress returns the Address field value if set, zero value otherwise.
func (o *UpdatePlaceDataAttributes) GetAddress() string {
	if o == nil || IsNil(o.Address) {
		var ret string
		return ret
	}
	return *o.Address
}

// GetAddressOk returns a tuple with the Address field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdatePlaceDataAttributes) GetAddressOk() (*string, bool) {
	if o == nil || IsNil(o.Address) {
		return nil, false
	}
	return o.Address, true
}

// HasAddress returns a boolean if a field has been set.
func (o *UpdatePlaceDataAttributes) HasAddress() bool {
	if o != nil && !IsNil(o.Address) {
		return true
	}

	return false
}

// SetAddress gets a reference to the given string and assigns it to the Address field.
func (o *UpdatePlaceDataAttributes) SetAddress(v string) {
	o.Address = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *UpdatePlaceDataAttributes) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdatePlaceDataAttributes) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *UpdatePlaceDataAttributes) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *UpdatePlaceDataAttributes) SetName(v string) {
	o.Name = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *UpdatePlaceDataAttributes) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdatePlaceDataAttributes) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *UpdatePlaceDataAttributes) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *UpdatePlaceDataAttributes) SetDescription(v string) {
	o.Description = &v
}

// GetIcon returns the Icon field value if set, zero value otherwise.
func (o *UpdatePlaceDataAttributes) GetIcon() string {
	if o == nil || IsNil(o.Icon) {
		var ret string
		return ret
	}
	return *o.Icon
}

// GetIconOk returns a tuple with the Icon field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdatePlaceDataAttributes) GetIconOk() (*string, bool) {
	if o == nil || IsNil(o.Icon) {
		return nil, false
	}
	return o.Icon, true
}

// HasIcon returns a boolean if a field has been set.
func (o *UpdatePlaceDataAttributes) HasIcon() bool {
	if o != nil && !IsNil(o.Icon) {
		return true
	}

	return false
}

// SetIcon gets a reference to the given string and assigns it to the Icon field.
func (o *UpdatePlaceDataAttributes) SetIcon(v string) {
	o.Icon = &v
}

// GetBanner returns the Banner field value if set, zero value otherwise.
func (o *UpdatePlaceDataAttributes) GetBanner() string {
	if o == nil || IsNil(o.Banner) {
		var ret string
		return ret
	}
	return *o.Banner
}

// GetBannerOk returns a tuple with the Banner field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdatePlaceDataAttributes) GetBannerOk() (*string, bool) {
	if o == nil || IsNil(o.Banner) {
		return nil, false
	}
	return o.Banner, true
}

// HasBanner returns a boolean if a field has been set.
func (o *UpdatePlaceDataAttributes) HasBanner() bool {
	if o != nil && !IsNil(o.Banner) {
		return true
	}

	return false
}

// SetBanner gets a reference to the given string and assigns it to the Banner field.
func (o *UpdatePlaceDataAttributes) SetBanner(v string) {
	o.Banner = &v
}

// GetWebsite returns the Website field value if set, zero value otherwise.
func (o *UpdatePlaceDataAttributes) GetWebsite() string {
	if o == nil || IsNil(o.Website) {
		var ret string
		return ret
	}
	return *o.Website
}

// GetWebsiteOk returns a tuple with the Website field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdatePlaceDataAttributes) GetWebsiteOk() (*string, bool) {
	if o == nil || IsNil(o.Website) {
		return nil, false
	}
	return o.Website, true
}

// HasWebsite returns a boolean if a field has been set.
func (o *UpdatePlaceDataAttributes) HasWebsite() bool {
	if o != nil && !IsNil(o.Website) {
		return true
	}

	return false
}

// SetWebsite gets a reference to the given string and assigns it to the Website field.
func (o *UpdatePlaceDataAttributes) SetWebsite(v string) {
	o.Website = &v
}

// GetPhone returns the Phone field value if set, zero value otherwise.
func (o *UpdatePlaceDataAttributes) GetPhone() string {
	if o == nil || IsNil(o.Phone) {
		var ret string
		return ret
	}
	return *o.Phone
}

// GetPhoneOk returns a tuple with the Phone field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdatePlaceDataAttributes) GetPhoneOk() (*string, bool) {
	if o == nil || IsNil(o.Phone) {
		return nil, false
	}
	return o.Phone, true
}

// HasPhone returns a boolean if a field has been set.
func (o *UpdatePlaceDataAttributes) HasPhone() bool {
	if o != nil && !IsNil(o.Phone) {
		return true
	}

	return false
}

// SetPhone gets a reference to the given string and assigns it to the Phone field.
func (o *UpdatePlaceDataAttributes) SetPhone(v string) {
	o.Phone = &v
}

func (o UpdatePlaceDataAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdatePlaceDataAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ClassId) {
		toSerialize["class_id"] = o.ClassId
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Address) {
		toSerialize["address"] = o.Address
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Icon) {
		toSerialize["icon"] = o.Icon
	}
	if !IsNil(o.Banner) {
		toSerialize["banner"] = o.Banner
	}
	if !IsNil(o.Website) {
		toSerialize["website"] = o.Website
	}
	if !IsNil(o.Phone) {
		toSerialize["phone"] = o.Phone
	}
	return toSerialize, nil
}

type NullableUpdatePlaceDataAttributes struct {
	value *UpdatePlaceDataAttributes
	isSet bool
}

func (v NullableUpdatePlaceDataAttributes) Get() *UpdatePlaceDataAttributes {
	return v.value
}

func (v *NullableUpdatePlaceDataAttributes) Set(val *UpdatePlaceDataAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdatePlaceDataAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdatePlaceDataAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdatePlaceDataAttributes(val *UpdatePlaceDataAttributes) *NullableUpdatePlaceDataAttributes {
	return &NullableUpdatePlaceDataAttributes{value: val, isSet: true}
}

func (v NullableUpdatePlaceDataAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdatePlaceDataAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


