/*
Place Service API

API for managing places and their classes.

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
)

// checks if the OpenUpdatePlaceMediaLinksDataRelationships type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OpenUpdatePlaceMediaLinksDataRelationships{}

// OpenUpdatePlaceMediaLinksDataRelationships struct for OpenUpdatePlaceMediaLinksDataRelationships
type OpenUpdatePlaceMediaLinksDataRelationships struct {
	Place *OpenUpdatePlaceMediaLinksDataRelationshipsPlace `json:"place,omitempty"`
}

// NewOpenUpdatePlaceMediaLinksDataRelationships instantiates a new OpenUpdatePlaceMediaLinksDataRelationships object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOpenUpdatePlaceMediaLinksDataRelationships() *OpenUpdatePlaceMediaLinksDataRelationships {
	this := OpenUpdatePlaceMediaLinksDataRelationships{}
	return &this
}

// NewOpenUpdatePlaceMediaLinksDataRelationshipsWithDefaults instantiates a new OpenUpdatePlaceMediaLinksDataRelationships object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOpenUpdatePlaceMediaLinksDataRelationshipsWithDefaults() *OpenUpdatePlaceMediaLinksDataRelationships {
	this := OpenUpdatePlaceMediaLinksDataRelationships{}
	return &this
}

// GetPlace returns the Place field value if set, zero value otherwise.
func (o *OpenUpdatePlaceMediaLinksDataRelationships) GetPlace() OpenUpdatePlaceMediaLinksDataRelationshipsPlace {
	if o == nil || IsNil(o.Place) {
		var ret OpenUpdatePlaceMediaLinksDataRelationshipsPlace
		return ret
	}
	return *o.Place
}

// GetPlaceOk returns a tuple with the Place field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OpenUpdatePlaceMediaLinksDataRelationships) GetPlaceOk() (*OpenUpdatePlaceMediaLinksDataRelationshipsPlace, bool) {
	if o == nil || IsNil(o.Place) {
		return nil, false
	}
	return o.Place, true
}

// HasPlace returns a boolean if a field has been set.
func (o *OpenUpdatePlaceMediaLinksDataRelationships) HasPlace() bool {
	if o != nil && !IsNil(o.Place) {
		return true
	}

	return false
}

// SetPlace gets a reference to the given OpenUpdatePlaceMediaLinksDataRelationshipsPlace and assigns it to the Place field.
func (o *OpenUpdatePlaceMediaLinksDataRelationships) SetPlace(v OpenUpdatePlaceMediaLinksDataRelationshipsPlace) {
	o.Place = &v
}

func (o OpenUpdatePlaceMediaLinksDataRelationships) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OpenUpdatePlaceMediaLinksDataRelationships) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Place) {
		toSerialize["place"] = o.Place
	}
	return toSerialize, nil
}

type NullableOpenUpdatePlaceMediaLinksDataRelationships struct {
	value *OpenUpdatePlaceMediaLinksDataRelationships
	isSet bool
}

func (v NullableOpenUpdatePlaceMediaLinksDataRelationships) Get() *OpenUpdatePlaceMediaLinksDataRelationships {
	return v.value
}

func (v *NullableOpenUpdatePlaceMediaLinksDataRelationships) Set(val *OpenUpdatePlaceMediaLinksDataRelationships) {
	v.value = val
	v.isSet = true
}

func (v NullableOpenUpdatePlaceMediaLinksDataRelationships) IsSet() bool {
	return v.isSet
}

func (v *NullableOpenUpdatePlaceMediaLinksDataRelationships) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOpenUpdatePlaceMediaLinksDataRelationships(val *OpenUpdatePlaceMediaLinksDataRelationships) *NullableOpenUpdatePlaceMediaLinksDataRelationships {
	return &NullableOpenUpdatePlaceMediaLinksDataRelationships{value: val, isSet: true}
}

func (v NullableOpenUpdatePlaceMediaLinksDataRelationships) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOpenUpdatePlaceMediaLinksDataRelationships) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


