/*
Place Service API

API for managing places and their classes.

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package resources

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the OpenUpdatePlaceClassMediaLinksDataAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OpenUpdatePlaceClassMediaLinksDataAttributes{}

// OpenUpdatePlaceClassMediaLinksDataAttributes struct for OpenUpdatePlaceClassMediaLinksDataAttributes
type OpenUpdatePlaceClassMediaLinksDataAttributes struct {
	// JWT upload session token
	UploadToken string `json:"upload_token"`
	// Pre-signed PUT URL for icon upload
	IconUploadUrl string `json:"icon_upload_url"`
	// Pre-signed GET URL to read uploaded icon
	IconGetUrl string `json:"icon_get_url"`
}

type _OpenUpdatePlaceClassMediaLinksDataAttributes OpenUpdatePlaceClassMediaLinksDataAttributes

// NewOpenUpdatePlaceClassMediaLinksDataAttributes instantiates a new OpenUpdatePlaceClassMediaLinksDataAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOpenUpdatePlaceClassMediaLinksDataAttributes(uploadToken string, iconUploadUrl string, iconGetUrl string) *OpenUpdatePlaceClassMediaLinksDataAttributes {
	this := OpenUpdatePlaceClassMediaLinksDataAttributes{}
	this.UploadToken = uploadToken
	this.IconUploadUrl = iconUploadUrl
	this.IconGetUrl = iconGetUrl
	return &this
}

// NewOpenUpdatePlaceClassMediaLinksDataAttributesWithDefaults instantiates a new OpenUpdatePlaceClassMediaLinksDataAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOpenUpdatePlaceClassMediaLinksDataAttributesWithDefaults() *OpenUpdatePlaceClassMediaLinksDataAttributes {
	this := OpenUpdatePlaceClassMediaLinksDataAttributes{}
	return &this
}

// GetUploadToken returns the UploadToken field value
func (o *OpenUpdatePlaceClassMediaLinksDataAttributes) GetUploadToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UploadToken
}

// GetUploadTokenOk returns a tuple with the UploadToken field value
// and a boolean to check if the value has been set.
func (o *OpenUpdatePlaceClassMediaLinksDataAttributes) GetUploadTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UploadToken, true
}

// SetUploadToken sets field value
func (o *OpenUpdatePlaceClassMediaLinksDataAttributes) SetUploadToken(v string) {
	o.UploadToken = v
}

// GetIconUploadUrl returns the IconUploadUrl field value
func (o *OpenUpdatePlaceClassMediaLinksDataAttributes) GetIconUploadUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.IconUploadUrl
}

// GetIconUploadUrlOk returns a tuple with the IconUploadUrl field value
// and a boolean to check if the value has been set.
func (o *OpenUpdatePlaceClassMediaLinksDataAttributes) GetIconUploadUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IconUploadUrl, true
}

// SetIconUploadUrl sets field value
func (o *OpenUpdatePlaceClassMediaLinksDataAttributes) SetIconUploadUrl(v string) {
	o.IconUploadUrl = v
}

// GetIconGetUrl returns the IconGetUrl field value
func (o *OpenUpdatePlaceClassMediaLinksDataAttributes) GetIconGetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.IconGetUrl
}

// GetIconGetUrlOk returns a tuple with the IconGetUrl field value
// and a boolean to check if the value has been set.
func (o *OpenUpdatePlaceClassMediaLinksDataAttributes) GetIconGetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IconGetUrl, true
}

// SetIconGetUrl sets field value
func (o *OpenUpdatePlaceClassMediaLinksDataAttributes) SetIconGetUrl(v string) {
	o.IconGetUrl = v
}

func (o OpenUpdatePlaceClassMediaLinksDataAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OpenUpdatePlaceClassMediaLinksDataAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["upload_token"] = o.UploadToken
	toSerialize["icon_upload_url"] = o.IconUploadUrl
	toSerialize["icon_get_url"] = o.IconGetUrl
	return toSerialize, nil
}

func (o *OpenUpdatePlaceClassMediaLinksDataAttributes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"upload_token",
		"icon_upload_url",
		"icon_get_url",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOpenUpdatePlaceClassMediaLinksDataAttributes := _OpenUpdatePlaceClassMediaLinksDataAttributes{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOpenUpdatePlaceClassMediaLinksDataAttributes)

	if err != nil {
		return err
	}

	*o = OpenUpdatePlaceClassMediaLinksDataAttributes(varOpenUpdatePlaceClassMediaLinksDataAttributes)

	return err
}

type NullableOpenUpdatePlaceClassMediaLinksDataAttributes struct {
	value *OpenUpdatePlaceClassMediaLinksDataAttributes
	isSet bool
}

func (v NullableOpenUpdatePlaceClassMediaLinksDataAttributes) Get() *OpenUpdatePlaceClassMediaLinksDataAttributes {
	return v.value
}

func (v *NullableOpenUpdatePlaceClassMediaLinksDataAttributes) Set(val *OpenUpdatePlaceClassMediaLinksDataAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableOpenUpdatePlaceClassMediaLinksDataAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableOpenUpdatePlaceClassMediaLinksDataAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOpenUpdatePlaceClassMediaLinksDataAttributes(val *OpenUpdatePlaceClassMediaLinksDataAttributes) *NullableOpenUpdatePlaceClassMediaLinksDataAttributes {
	return &NullableOpenUpdatePlaceClassMediaLinksDataAttributes{value: val, isSet: true}
}

func (v NullableOpenUpdatePlaceClassMediaLinksDataAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOpenUpdatePlaceClassMediaLinksDataAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


