openapi: 3.1.0
info:
  title: Place Service API
  description: API for managing places and their classes.
  version: 0.0.1
paths:
  /test:
    post:
      tags:
        - Test
      description: Test
      responses:
        '201':
          description: successfully
components:
  schemas:
    CreatePlace:
      type: object
      required:
        - data
      properties:
        data:
          type: object
          required:
            - type
            - attributes
          properties:
            type:
              type: string
              enum:
                - create_place
            attributes:
              type: object
              required:
                - class_id
                - point
                - address
                - name
              properties:
                class_id:
                  type: string
                  format: uuid
                  description: The ID of the class this place belongs to
                organization_id:
                  type: string
                  format: uuid
                  description: The ID of the organization this place belongs to
                point:
                  type: object
                  required:
                    - latitude
                    - longitude
                  properties:
                    latitude:
                      type: number
                      format: float64
                      description: The latitude coordinate of the place
                    longitude:
                      type: number
                      format: float64
                      description: The longitude coordinate of the place
                address:
                  type: string
                  description: The physical address of the place
                name:
                  type: string
                  description: The name of the place
                description:
                  type: string
                  description: A brief description of the place
                icon:
                  type: string
                  format: uri
                  description: A URL to an icon representing the place
                banner:
                  type: string
                  format: uri
                  description: A URL to a banner image for the place
                website:
                  type: string
                  format: uri
                  description: The website URL of the place
                phone:
                  type: string
                  description: The contact phone number of the place
    UpdatePlace:
      type: object
      required:
        - data
      properties:
        data:
          type: object
          required:
            - id
            - type
            - attributes
          properties:
            id:
              type: string
              format: uuid
              description: The unique identifier of the place to be updated
            type:
              type: string
              enum:
                - update_place
            attributes:
              type: object
              properties:
                class_id:
                  type: string
                  format: uuid
                  description: The ID of the class this place belongs to
                status:
                  type: string
                  description: 'The status of the place (e.g., active, inactive)'
                address:
                  type: string
                  description: The physical address of the place
                name:
                  type: string
                  description: The name of the place
                description:
                  type: string
                  description: A brief description of the place
                icon:
                  type: string
                  format: uri
                  description: A URL to an icon representing the place
                banner:
                  type: string
                  format: uri
                  description: A URL to a banner image for the place
                website:
                  type: string
                  format: uri
                  description: The website URL of the place
                phone:
                  type: string
                  description: The contact phone number of the place
    UpdateClassForPlace:
      type: object
      required:
        - data
      properties:
        data:
          type: object
          required:
            - id
            - type
            - attributes
          properties:
            id:
              type: string
              format: uuid
              description: The ID of the place to update
            type:
              type: string
              enum:
                - update_place_class
            attributes:
              type: object
              required:
                - class_id
              properties:
                class_id:
                  type: string
                  format: uuid
                  description: The ID of the class this place belongs to
    VerifyPlace:
      type: object
      required:
        - data
      properties:
        data:
          type: object
          required:
            - type
            - attributes
          properties:
            type:
              type: string
              enum:
                - update_place_verify
            attributes:
              type: object
              required:
                - verify
              properties:
                verify:
                  type: boolean
                  description: Indicates whether the place has been verified
    UpdatePlaceStatus:
      type: object
      required:
        - data
      properties:
        data:
          type: object
          required:
            - id
            - type
            - attributes
          properties:
            id:
              type: string
              format: uuid
              description: The unique identifier of the place
            type:
              type: string
              enum:
                - update_place_status
            attributes:
              type: object
              required:
                - status
              properties:
                status:
                  type: string
                  description: The new status of the place
    UpdatePlaceVerify:
      type: object
      required:
        - data
      properties:
        data:
          type: object
          required:
            - id
            - type
            - attributes
          properties:
            id:
              type: string
              format: uuid
              description: The unique identifier of the place
            type:
              type: string
              enum:
                - update_place_verify
            attributes:
              type: object
              required:
                - verify
              properties:
                verify:
                  type: boolean
                  description: The new verify status of the place
    CreatePlaceClass:
      type: object
      required:
        - data
      properties:
        data:
          type: object
          required:
            - id
            - type
            - attributes
          properties:
            id:
              type: string
              format: uuid
              description: place ID
            type:
              type: string
              enum:
                - place_class_create
            attributes:
              type: object
              required:
                - code
                - name
                - description
              properties:
                parent_id:
                  type: string
                  format: uuid
                  description: 'The ID of the parent class, if any'
                code:
                  type: string
                  description: The unique code of the class
                  example: japanese_cuisine
                name:
                  type: string
                  description: The name of the class
                description:
                  type: string
                  description: A brief description of the class
                icon:
                  type: string
                  format: uri
                  description: A URL to an icon representing the class
    UpdatePlaceClass:
      type: object
      required:
        - data
      properties:
        data:
          type: object
          required:
            - id
            - type
            - attributes
          properties:
            id:
              type: string
              format: uuid
              description: place ID
            type:
              type: string
              enum:
                - place_class_update
            attributes:
              type: object
              properties:
                parent_id:
                  type: string
                  format: uuid
                  description: The ID of the parent class
                code:
                  type: string
                  description: The unique code of the class
                  example: japanese_cuisine
                name:
                  type: string
                  description: The name of the class
                description:
                  type: string
                  description: A brief description of the class
                icon:
                  type: string
                  format: uri
                  description: A URL to an icon representing the class
    ReplacePlaceClass:
      type: object
      required:
        - data
      properties:
        data:
          type: object
          required:
            - id
            - type
            - attributes
          properties:
            id:
              type: string
              format: uuid
              description: The unique identifier for the replace place class operation
            type:
              type: string
              enum:
                - replace_place_class
            attributes:
              type: object
              required:
                - class_replace_id
              properties:
                class_replace_id:
                  type: string
                  format: uuid
                  description: The ID of the class to replace with
    PaginationData:
      type: object
      required:
        - self
      properties:
        self:
          type: string
          format: uri
          description: link to the current page
        first:
          type: string
          format: uri
          description: link to the first page
        last:
          type: string
          format: uri
          description: link to the last page
        prev:
          type: string
          format: uri
          description: link to the previous page
        next:
          type: string
          format: uri
          description: link to the next page
    Place:
      type: object
      required:
        - data
      properties:
        data:
          type: object
          required:
            - id
            - type
            - attributes
            - relationships
          properties:
            id:
              type: string
              format: uuid
              description: place ID
            type:
              type: string
              enum:
                - place
            attributes:
              type: object
              required:
                - status
                - verified
                - point
                - address
                - name
                - created_at
                - updated_at
              properties:
                status:
                  type: string
                  description: 'The status of the place (e.g., active, inactive)'
                verified:
                  type: boolean
                  description: Indicates if the place has been verified
                point:
                  $ref: '#/components/schemas/CreatePlace/properties/data/properties/attributes/properties/point'
                address:
                  type: string
                  description: The physical address of the place
                name:
                  type: string
                  description: The name of the place
                description:
                  type: string
                  description: A brief description of the place
                icon:
                  type: string
                  format: uri
                  description: A URL to an icon representing the place
                banner:
                  type: string
                  format: uri
                  description: A URL to a banner image for the place
                website:
                  type: string
                  format: uri
                  description: The website URL of the place
                phone:
                  type: string
                  description: The contact phone number of the place
                created_at:
                  type: string
                  format: date-time
                  description: The date and time when the place was created
                updated_at:
                  type: string
                  format: date-time
                  description: The date and time when the place was last updated
            relationships:
              type: object
              required:
                - class
              properties:
                organization:
                  type: object
                  required:
                    - id
                    - type
                  properties:
                    id:
                      type: string
                      format: uuid
                      description: The ID of the organization associated with the place
                    type:
                      type: string
                      enum:
                        - organization
                class:
                  type: object
                  required:
                    - id
                    - type
                  properties:
                    id:
                      type: string
                      format: uuid
                      description: The ID of the class associated with the place
                    type:
                      type: string
                      enum:
                        - place_class
    PlacesCollection:
      type: object
      required:
        - data
        - links
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/Place/properties/data'
        links:
          $ref: '#/components/schemas/PaginationData'
    Class:
      type: object
      required:
        - data
      properties:
        data:
          type: object
          required:
            - id
            - type
            - attributes
          properties:
            id:
              type: string
              format: uuid
              description: place ID
            type:
              type: string
              enum:
                - place_class
            attributes:
              type: object
              required:
                - code
                - name
                - description
                - updated_at
                - created_at
              properties:
                code:
                  type: string
                  description: The unique code of the class
                  example: japanese_cuisine
                name:
                  type: string
                  description: The name of the class
                description:
                  type: string
                  description: A brief description of the class
                icon:
                  type: string
                  format: uri
                  description: A URL to an icon representing the class
                updated_at:
                  type: string
                  format: date-time
                  description: The date and time when the class was last updated
                created_at:
                  type: string
                  format: date-time
                  description: The date and time when the class was created
            relationships:
              type: object
              properties:
                parent:
                  type: object
                  required:
                    - id
                    - type
                  properties:
                    id:
                      type: string
                      format: uuid
                      description: The ID of the parent class
                    type:
                      type: string
                      enum:
                        - place_class
    ClassesCollection:
      type: object
      required:
        - data
        - links
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/Class/properties/data'
        links:
          $ref: '#/components/schemas/PaginationData'
