openapi: 3.1.0
info:
  title: Place Service API
  description: API for managing places and their classes.
  version: 0.0.1

paths:
  /test:
    post:
      tags:
        - Test
      description: Test
      responses:
        '201':
          description: successfully

components:
  schemas:
    # requests:
    CreatePlace:
      $ref: './spec/components/schemas/requests/CreatePlace.yaml'
    ConfirmUpdatePlace:
      $ref: './spec/components/schemas/requests/ConfirmUpdatePlace.yaml'
    UpdateClassForPlace:
      $ref: './spec/components/schemas/requests/UpdateClassForPlace.yaml'
    VerifyPlace:
      $ref: './spec/components/schemas/requests/VerifyPlace.yaml'
    UpdatePlaceStatus:
      $ref: './spec/components/schemas/requests/UpdatePlaceStatus.yaml'
    UpdatePlaceVerify:
      $ref: './spec/components/schemas/requests/UpdatePlaceVerify.yaml'

    CreatePlaceClass:
      $ref: './spec/components/schemas/requests/CreatePlaceClass.yaml'
    ConfirmUpdatePlaceClass:
      $ref: './spec/components/schemas/requests/ConfirmUpdatePlaceClass.yaml'
    ReplacePlaceClass:
      $ref: './spec/components/schemas/requests/ReplacePlaceClass.yaml'

    # responses:
    PaginationData:
      $ref: './spec/components/schemas/responses/PaginationData.yaml'
    Place:
      $ref: './spec/components/schemas/responses/Place.yaml'
    PlacesCollection:
      $ref: './spec/components/schemas/responses/PlacesCollection.yaml'
    PlaceClass:
      $ref: './spec/components/schemas/responses/PlaceClass.yaml'
    PlaceClassesCollection:
      $ref: './spec/components/schemas/responses/PlaceClassesCollection.yaml'
    OpenUpdatePlaceClassMediaLinks:
      $ref: './spec/components/schemas/responses/OpenUpdatePlaceClassMediaLinks.yaml'
    OpenUpdatePlaceMediaLinks:
      $ref: './spec/components/schemas/responses/OpenUpdatePlaceMediaLinks.yaml'
      