openapi: 3.1.0
info:
  title: Place Service API
  description: API for managing places and their classes.
  version: 0.0.1

paths:
  /test:
    post:
      tags:
        - Test
      description: Test
      responses:
        '201':
          description: successfully

components:
  schemas: