openapi: 3.1.0
info:
  title: Place Service API
  description: API for managing places and their classes.
  version: 0.0.1

paths:
  /test:
    post:
      tags:
        - Test
      description: Test
      responses:
        '201':
          description: successfully

components:
  schemas:
    # requests:
    CreatePlace:
      $ref: './spec/components/schemas/requests/CreatePlace.yaml'
    UpdatePlace:
      $ref: './spec/components/schemas/requests/UpdatePlace.yaml'
    UpdatePlaceClass:
      $ref: './spec/components/schemas/requests/UpdatePlaceClass.yaml'
    UpdatePlaceStatus:
      $ref: './spec/components/schemas/requests/UpdatePlaceStatus.yaml'
    UpdatePlaceVerify:
      $ref: './spec/components/schemas/requests/UpdatePlaceVerify.yaml'

    CreatePlaceClass:
      $ref: './spec/components/schemas/requests/CreatePlaceClass.yaml'
    DeprecatedPlaceClass:
      $ref: './spec/components/schemas/requests/DeprecatedPlaceClass.yaml'

    DeleteUploadPlaceIcon:
      $ref: './spec/components/schemas/requests/DeleteUploadPlaceIcon.yaml'
    DeleteUploadPlaceBanner:
      $ref: './spec/components/schemas/requests/DeleteUploadPlaceBanner.yaml'
    DeleteUploadPlaceClassIcon:
      $ref: './spec/components/schemas/requests/DeleteUploadPlaceClassIcon.yaml'

    # responses:
    PaginationData:
      $ref: './spec/components/schemas/responses/PaginationData.yaml'
    Place:
      $ref: './spec/components/schemas/responses/Place.yaml'
    PlacesCollection:
      $ref: './spec/components/schemas/responses/PlacesCollection.yaml'
    PlaceClass:
      $ref: './spec/components/schemas/responses/PlaceClass.yaml'
    PlaceClassData:
      $ref: './spec/components/schemas/responses/PlaceClassData.yaml'
    PlaceClassesCollection:
      $ref: './spec/components/schemas/responses/PlaceClassesCollection.yaml'

    Organization:
      $ref: './spec/components/schemas/responses/Organization.yaml'
    OrganizationData:
      $ref: './spec/components/schemas/responses/OrganizationData.yaml'

    UploadPlaceClassMediaLinks:
      $ref: './spec/components/schemas/responses/UploadPlaceClassMediaLinks.yaml'
    UploadPlaceMediaLinks:
      $ref: './spec/components/schemas/responses/UploadPlaceMediaLinks.yaml'
    UploadResourcesLink:
      $ref: './spec/components/schemas/responses/UploadResourcesLink.yaml'
      